// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: podium/v1/admin.proto

package podiumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status          NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=podium.v1.NodeStatus" json:"status,omitempty"`
	Labels          []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Capacity        *NodeCapacity          `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RunningTasks    int32                  `protobuf:"varint,6,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	FreeSlots       int32                  `protobuf:"varint,7,opt,name=free_slots,json=freeSlots,proto3" json:"free_slots,omitempty"`
	Version         string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ts_stable_id is the Tailscale device this node is bound to, empty when it is unbound
	// (never enrolled over a tailnet, or rekeyed).
	TsStableId string `protobuf:"bytes,11,opt,name=ts_stable_id,json=tsStableId,proto3" json:"ts_stable_id,omitempty"`
	// draining is the operator's standing instruction that this node takes no new work. It
	// survives a node restart and a server restart; status is DRAINING while it is connected.
	Draining bool `protobuf:"varint,12,opt,name=draining,proto3" json:"draining,omitempty"`
	// max_tasks_override is the slot count an operator set from the control plane. Unset means
	// the node's own max_tasks decides, which is what capacity.max_tasks reports; when it IS
	// set it is the number the scheduler and the node both budget against, and capacity is
	// still what the node's configuration says.
	MaxTasksOverride *int32 `protobuf:"varint,13,opt,name=max_tasks_override,json=maxTasksOverride,proto3,oneof" json:"max_tasks_override,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_podium_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Node) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Node) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *Node) GetFreeSlots() int32 {
	if x != nil {
		return x.FreeSlots
	}
	return 0
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Node) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetTsStableId() string {
	if x != nil {
		return x.TsStableId
	}
	return ""
}

func (x *Node) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

func (x *Node) GetMaxTasksOverride() int32 {
	if x != nil && x.MaxTasksOverride != nil {
		return *x.MaxTasksOverride
	}
	return 0
}

type CreateEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenRequest) Reset() {
	*x = CreateEnrollmentTokenRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenRequest) ProtoMessage() {}

func (x *CreateEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnrollmentTokenRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateEnrollmentTokenRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type CreateEnrollmentTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SENSITIVE: never log. Returned once; the server keeps only its SHA-256.
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenResponse) Reset() {
	*x = CreateEnrollmentTokenResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenResponse) ProtoMessage() {}

func (x *CreateEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnrollmentTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateEnrollmentTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{3}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RekeyNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyNodeRequest) Reset() {
	*x = RekeyNodeRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyNodeRequest) ProtoMessage() {}

func (x *RekeyNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyNodeRequest.ProtoReflect.Descriptor instead.
func (*RekeyNodeRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RekeyNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RekeyNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyNodeResponse) Reset() {
	*x = RekeyNodeResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyNodeResponse) ProtoMessage() {}

func (x *RekeyNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyNodeResponse.ProtoReflect.Descriptor instead.
func (*RekeyNodeResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *RekeyNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DrainNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UndrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndrainNodeRequest) Reset() {
	*x = UndrainNodeRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndrainNodeRequest) ProtoMessage() {}

func (x *UndrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndrainNodeRequest.ProtoReflect.Descriptor instead.
func (*UndrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UndrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UndrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndrainNodeResponse) Reset() {
	*x = UndrainNodeResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndrainNodeResponse) ProtoMessage() {}

func (x *UndrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndrainNodeResponse.ProtoReflect.Descriptor instead.
func (*UndrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UndrainNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type SetNodeSlotsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// max_tasks is how many tasks this node may run at once. Zero clears the override, which
	// returns the node to the max_tasks in its own configuration file.
	MaxTasks      int32 `protobuf:"varint,2,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeSlotsRequest) Reset() {
	*x = SetNodeSlotsRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeSlotsRequest) ProtoMessage() {}

func (x *SetNodeSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeSlotsRequest.ProtoReflect.Descriptor instead.
func (*SetNodeSlotsRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *SetNodeSlotsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetNodeSlotsRequest) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

type SetNodeSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeSlotsResponse) Reset() {
	*x = SetNodeSlotsResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeSlotsResponse) ProtoMessage() {}

func (x *SetNodeSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeSlotsResponse.ProtoReflect.Descriptor instead.
func (*SetNodeSlotsResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *SetNodeSlotsResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeleteNodeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// force deletes a node that is still online. It does not stop what it is running.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_podium_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeleteNodeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_podium_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_podium_v1_admin_proto_rawDescGZIP(), []int{14}
}

var File_podium_v1_admin_proto protoreflect.FileDescriptor

const file_podium_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x15podium/v1/admin.proto\x12\tpodium.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16podium/v1/common.proto\"\x8f\x04\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.podium.v1.NodeStatusR\x06status\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x123\n" +
	"\bcapacity\x18\x05 \x01(\v2\x17.podium.v1.NodeCapacityR\bcapacity\x12#\n" +
	"\rrunning_tasks\x18\x06 \x01(\x05R\frunningTasks\x12\x1d\n" +
	"\n" +
	"free_slots\x18\a \x01(\x05R\tfreeSlots\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12F\n" +
	"\x11last_heartbeat_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\fts_stable_id\x18\v \x01(\tR\n" +
	"tsStableId\x12\x1a\n" +
	"\bdraining\x18\f \x01(\bR\bdraining\x121\n" +
	"\x12max_tasks_override\x18\r \x01(\x05H\x00R\x10maxTasksOverride\x88\x01\x01B\x15\n" +
	"\x13_max_tasks_override\"c\n" +
	"\x1cCreateEnrollmentTokenRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"p\n" +
	"\x1dCreateEnrollmentTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x12\n" +
	"\x10ListNodesRequest\":\n" +
	"\x11ListNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.podium.v1.NodeR\x05nodes\"+\n" +
	"\x10RekeyNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"8\n" +
	"\x11RekeyNodeResponse\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.podium.v1.NodeR\x04node\"+\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"8\n" +
	"\x11DrainNodeResponse\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.podium.v1.NodeR\x04node\"-\n" +
	"\x12UndrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\":\n" +
	"\x13UndrainNodeResponse\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.podium.v1.NodeR\x04node\"K\n" +
	"\x13SetNodeSlotsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tmax_tasks\x18\x02 \x01(\x05R\bmaxTasks\";\n" +
	"\x14SetNodeSlotsResponse\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.podium.v1.NodeR\x04node\"B\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x14\n" +
	"\x12DeleteNodeResponse2\xc0\x04\n" +
	"\x10NodeAdminService\x12j\n" +
	"\x15CreateEnrollmentToken\x12'.podium.v1.CreateEnrollmentTokenRequest\x1a(.podium.v1.CreateEnrollmentTokenResponse\x12F\n" +
	"\tListNodes\x12\x1b.podium.v1.ListNodesRequest\x1a\x1c.podium.v1.ListNodesResponse\x12F\n" +
	"\tRekeyNode\x12\x1b.podium.v1.RekeyNodeRequest\x1a\x1c.podium.v1.RekeyNodeResponse\x12F\n" +
	"\tDrainNode\x12\x1b.podium.v1.DrainNodeRequest\x1a\x1c.podium.v1.DrainNodeResponse\x12L\n" +
	"\vUndrainNode\x12\x1d.podium.v1.UndrainNodeRequest\x1a\x1e.podium.v1.UndrainNodeResponse\x12O\n" +
	"\fSetNodeSlots\x12\x1e.podium.v1.SetNodeSlotsRequest\x1a\x1f.podium.v1.SetNodeSlotsResponse\x12I\n" +
	"\n" +
	"DeleteNode\x12\x1c.podium.v1.DeleteNodeRequest\x1a\x1d.podium.v1.DeleteNodeResponseB\xa4\x01\n" +
	"\rcom.podium.v1B\n" +
	"AdminProtoP\x01ZBgithub.com/alvaroibarguen/podium/internal/proto/podium/v1;podiumv1\xa2\x02\x03PXX\xaa\x02\tPodium.V1\xca\x02\tPodium\\V1\xe2\x02\x15Podium\\V1\\GPBMetadata\xea\x02\n" +
	"Podium::V1b\x06proto3"

var (
	file_podium_v1_admin_proto_rawDescOnce sync.Once
	file_podium_v1_admin_proto_rawDescData []byte
)

func file_podium_v1_admin_proto_rawDescGZIP() []byte {
	file_podium_v1_admin_proto_rawDescOnce.Do(func() {
		file_podium_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podium_v1_admin_proto_rawDesc), len(file_podium_v1_admin_proto_rawDesc)))
	})
	return file_podium_v1_admin_proto_rawDescData
}

var file_podium_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_podium_v1_admin_proto_goTypes = []any{
	(*Node)(nil),                          // 0: podium.v1.Node
	(*CreateEnrollmentTokenRequest)(nil),  // 1: podium.v1.CreateEnrollmentTokenRequest
	(*CreateEnrollmentTokenResponse)(nil), // 2: podium.v1.CreateEnrollmentTokenResponse
	(*ListNodesRequest)(nil),              // 3: podium.v1.ListNodesRequest
	(*ListNodesResponse)(nil),             // 4: podium.v1.ListNodesResponse
	(*RekeyNodeRequest)(nil),              // 5: podium.v1.RekeyNodeRequest
	(*RekeyNodeResponse)(nil),             // 6: podium.v1.RekeyNodeResponse
	(*DrainNodeRequest)(nil),              // 7: podium.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),             // 8: podium.v1.DrainNodeResponse
	(*UndrainNodeRequest)(nil),            // 9: podium.v1.UndrainNodeRequest
	(*UndrainNodeResponse)(nil),           // 10: podium.v1.UndrainNodeResponse
	(*SetNodeSlotsRequest)(nil),           // 11: podium.v1.SetNodeSlotsRequest
	(*SetNodeSlotsResponse)(nil),          // 12: podium.v1.SetNodeSlotsResponse
	(*DeleteNodeRequest)(nil),             // 13: podium.v1.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),            // 14: podium.v1.DeleteNodeResponse
	(NodeStatus)(0),                       // 15: podium.v1.NodeStatus
	(*NodeCapacity)(nil),                  // 16: podium.v1.NodeCapacity
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),           // 18: google.protobuf.Duration
}
var file_podium_v1_admin_proto_depIdxs = []int32{
	15, // 0: podium.v1.Node.status:type_name -> podium.v1.NodeStatus
	16, // 1: podium.v1.Node.capacity:type_name -> podium.v1.NodeCapacity
	17, // 2: podium.v1.Node.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	17, // 3: podium.v1.Node.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: podium.v1.CreateEnrollmentTokenRequest.ttl:type_name -> google.protobuf.Duration
	17, // 5: podium.v1.CreateEnrollmentTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: podium.v1.ListNodesResponse.nodes:type_name -> podium.v1.Node
	0,  // 7: podium.v1.RekeyNodeResponse.node:type_name -> podium.v1.Node
	0,  // 8: podium.v1.DrainNodeResponse.node:type_name -> podium.v1.Node
	0,  // 9: podium.v1.UndrainNodeResponse.node:type_name -> podium.v1.Node
	0,  // 10: podium.v1.SetNodeSlotsResponse.node:type_name -> podium.v1.Node
	1,  // 11: podium.v1.NodeAdminService.CreateEnrollmentToken:input_type -> podium.v1.CreateEnrollmentTokenRequest
	3,  // 12: podium.v1.NodeAdminService.ListNodes:input_type -> podium.v1.ListNodesRequest
	5,  // 13: podium.v1.NodeAdminService.RekeyNode:input_type -> podium.v1.RekeyNodeRequest
	7,  // 14: podium.v1.NodeAdminService.DrainNode:input_type -> podium.v1.DrainNodeRequest
	9,  // 15: podium.v1.NodeAdminService.UndrainNode:input_type -> podium.v1.UndrainNodeRequest
	11, // 16: podium.v1.NodeAdminService.SetNodeSlots:input_type -> podium.v1.SetNodeSlotsRequest
	13, // 17: podium.v1.NodeAdminService.DeleteNode:input_type -> podium.v1.DeleteNodeRequest
	2,  // 18: podium.v1.NodeAdminService.CreateEnrollmentToken:output_type -> podium.v1.CreateEnrollmentTokenResponse
	4,  // 19: podium.v1.NodeAdminService.ListNodes:output_type -> podium.v1.ListNodesResponse
	6,  // 20: podium.v1.NodeAdminService.RekeyNode:output_type -> podium.v1.RekeyNodeResponse
	8,  // 21: podium.v1.NodeAdminService.DrainNode:output_type -> podium.v1.DrainNodeResponse
	10, // 22: podium.v1.NodeAdminService.UndrainNode:output_type -> podium.v1.UndrainNodeResponse
	12, // 23: podium.v1.NodeAdminService.SetNodeSlots:output_type -> podium.v1.SetNodeSlotsResponse
	14, // 24: podium.v1.NodeAdminService.DeleteNode:output_type -> podium.v1.DeleteNodeResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_podium_v1_admin_proto_init() }
func file_podium_v1_admin_proto_init() {
	if File_podium_v1_admin_proto != nil {
		return
	}
	file_podium_v1_common_proto_init()
	file_podium_v1_admin_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podium_v1_admin_proto_rawDesc), len(file_podium_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podium_v1_admin_proto_goTypes,
		DependencyIndexes: file_podium_v1_admin_proto_depIdxs,
		MessageInfos:      file_podium_v1_admin_proto_msgTypes,
	}.Build()
	File_podium_v1_admin_proto = out.File
	file_podium_v1_admin_proto_goTypes = nil
	file_podium_v1_admin_proto_depIdxs = nil
}
