// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alvaroibarguen/podium/internal/proto/podium/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "podium.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceListSessionsProcedure is the fully-qualified name of the AgentService's ListSessions
	// RPC.
	AgentServiceListSessionsProcedure = "/podium.agent.v1.AgentService/ListSessions"
	// AgentServiceGetSessionProcedure is the fully-qualified name of the AgentService's GetSession RPC.
	AgentServiceGetSessionProcedure = "/podium.agent.v1.AgentService/GetSession"
	// AgentServiceListTurnsProcedure is the fully-qualified name of the AgentService's ListTurns RPC.
	AgentServiceListTurnsProcedure = "/podium.agent.v1.AgentService/ListTurns"
	// AgentServiceGetSettingsProcedure is the fully-qualified name of the AgentService's GetSettings
	// RPC.
	AgentServiceGetSettingsProcedure = "/podium.agent.v1.AgentService/GetSettings"
	// AgentServiceSetProviderKeyProcedure is the fully-qualified name of the AgentService's
	// SetProviderKey RPC.
	AgentServiceSetProviderKeyProcedure = "/podium.agent.v1.AgentService/SetProviderKey"
	// AgentServiceClearProviderKeyProcedure is the fully-qualified name of the AgentService's
	// ClearProviderKey RPC.
	AgentServiceClearProviderKeyProcedure = "/podium.agent.v1.AgentService/ClearProviderKey"
	// AgentServiceListMemoriesProcedure is the fully-qualified name of the AgentService's ListMemories
	// RPC.
	AgentServiceListMemoriesProcedure = "/podium.agent.v1.AgentService/ListMemories"
	// AgentServiceSearchMemoriesProcedure is the fully-qualified name of the AgentService's
	// SearchMemories RPC.
	AgentServiceSearchMemoriesProcedure = "/podium.agent.v1.AgentService/SearchMemories"
	// AgentServiceDeleteMemoryProcedure is the fully-qualified name of the AgentService's DeleteMemory
	// RPC.
	AgentServiceDeleteMemoryProcedure = "/podium.agent.v1.AgentService/DeleteMemory"
	// AgentServiceListSkillsProcedure is the fully-qualified name of the AgentService's ListSkills RPC.
	AgentServiceListSkillsProcedure = "/podium.agent.v1.AgentService/ListSkills"
	// AgentServiceGetProfileProcedure is the fully-qualified name of the AgentService's GetProfile RPC.
	AgentServiceGetProfileProcedure = "/podium.agent.v1.AgentService/GetProfile"
	// AgentServiceUpdateProfileProcedure is the fully-qualified name of the AgentService's
	// UpdateProfile RPC.
	AgentServiceUpdateProfileProcedure = "/podium.agent.v1.AgentService/UpdateProfile"
	// AgentServiceCreateSkillProcedure is the fully-qualified name of the AgentService's CreateSkill
	// RPC.
	AgentServiceCreateSkillProcedure = "/podium.agent.v1.AgentService/CreateSkill"
	// AgentServiceUpdateSkillProcedure is the fully-qualified name of the AgentService's UpdateSkill
	// RPC.
	AgentServiceUpdateSkillProcedure = "/podium.agent.v1.AgentService/UpdateSkill"
	// AgentServiceDeleteSkillProcedure is the fully-qualified name of the AgentService's DeleteSkill
	// RPC.
	AgentServiceDeleteSkillProcedure = "/podium.agent.v1.AgentService/DeleteSkill"
	// AgentServiceCreateChatProcedure is the fully-qualified name of the AgentService's CreateChat RPC.
	AgentServiceCreateChatProcedure = "/podium.agent.v1.AgentService/CreateChat"
	// AgentServiceListChatsProcedure is the fully-qualified name of the AgentService's ListChats RPC.
	AgentServiceListChatsProcedure = "/podium.agent.v1.AgentService/ListChats"
	// AgentServiceSendChatMessageProcedure is the fully-qualified name of the AgentService's
	// SendChatMessage RPC.
	AgentServiceSendChatMessageProcedure = "/podium.agent.v1.AgentService/SendChatMessage"
	// AgentServiceStreamChatProcedure is the fully-qualified name of the AgentService's StreamChat RPC.
	AgentServiceStreamChatProcedure = "/podium.agent.v1.AgentService/StreamChat"
)

// AgentServiceClient is a client for the podium.agent.v1.AgentService service.
type AgentServiceClient interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
	// GetSettings reports what the conductor is configured with. It reads no secret value:
	// there is no read endpoint on the secret store, by design.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// SetProviderKey validates a provider key with the provider itself and, only if that
	// succeeds, stores it as a Podium secret. An unvalidated key is never saved.
	SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error)
	// ClearProviderKey removes the secret and the metadata. Calling it twice is not an error.
	ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error)
	// ListMemories pages through the shared memory, newest first.
	ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error)
	// SearchMemories is a semantic search of the same memory.
	SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error)
	// DeleteMemory takes one memory out of every future recall. It is a tombstone rather
	// than a row deletion: the memory engine keeps the record for audit and stops serving it.
	DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error)
	// ListSkills reports the profile's skills so the chat can offer them. Nothing secret:
	// a name, an image and which one the chat starts with.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// GetProfile reports the profile a turn actually runs from — profile.yaml and skills/
	// merged with what the conductor's database holds — and every skill in full, so a
	// browser can manage them.
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	// UpdateProfile overrides profile.yaml's display name, model and default skills. An
	// empty field clears the override and returns that field to the file's value.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// CreateSkill stores a new skill in the conductor's database. A name a skills/*.yaml
	// already defines is refused: the files are authoritative for the names they hold.
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	// UpdateSkill replaces a stored skill. A file-defined skill is refused.
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	// DeleteSkill removes a stored skill. A file-defined skill is refused; deleting a
	// stored skill that is not there is not an error.
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	// CreateChat opens a new web-chat conversation owned by the calling login.
	CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error)
	// ListChats returns the caller's own chats, newest first. Another login's chats are
	// never returned.
	ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error)
	// SendChatMessage stores one human message and starts a turn on it. It is refused with
	// FailedPrecondition while a turn for that chat is already running: one turn at a time
	// per conversation is the whole model.
	SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error)
	// StreamChat replays a chat from from_seq and then follows it live. It never ends on its
	// own; the client cancels. Progress frames are ephemeral and are not replayed.
	StreamChat(context.Context, *connect.Request[v1.StreamChatRequest]) (*connect.ServerStreamForClient[v1.ChatFrame], error)
}

// NewAgentServiceClient constructs a client for the podium.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+AgentServiceListSessionsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+AgentServiceGetSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listTurns: connect.NewClient[v1.ListTurnsRequest, v1.ListTurnsResponse](
			httpClient,
			baseURL+AgentServiceListTurnsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[v1.GetSettingsRequest, v1.GetSettingsResponse](
			httpClient,
			baseURL+AgentServiceGetSettingsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		setProviderKey: connect.NewClient[v1.SetProviderKeyRequest, v1.SetProviderKeyResponse](
			httpClient,
			baseURL+AgentServiceSetProviderKeyProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetProviderKey")),
			connect.WithClientOptions(opts...),
		),
		clearProviderKey: connect.NewClient[v1.ClearProviderKeyRequest, v1.ClearProviderKeyResponse](
			httpClient,
			baseURL+AgentServiceClearProviderKeyProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ClearProviderKey")),
			connect.WithClientOptions(opts...),
		),
		listMemories: connect.NewClient[v1.ListMemoriesRequest, v1.ListMemoriesResponse](
			httpClient,
			baseURL+AgentServiceListMemoriesProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListMemories")),
			connect.WithClientOptions(opts...),
		),
		searchMemories: connect.NewClient[v1.SearchMemoriesRequest, v1.SearchMemoriesResponse](
			httpClient,
			baseURL+AgentServiceSearchMemoriesProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SearchMemories")),
			connect.WithClientOptions(opts...),
		),
		deleteMemory: connect.NewClient[v1.DeleteMemoryRequest, v1.DeleteMemoryResponse](
			httpClient,
			baseURL+AgentServiceDeleteMemoryProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteMemory")),
			connect.WithClientOptions(opts...),
		),
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+AgentServiceListSkillsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListSkills")),
			connect.WithClientOptions(opts...),
		),
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.GetProfileResponse](
			httpClient,
			baseURL+AgentServiceGetProfileProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+AgentServiceUpdateProfileProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		createSkill: connect.NewClient[v1.CreateSkillRequest, v1.CreateSkillResponse](
			httpClient,
			baseURL+AgentServiceCreateSkillProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateSkill")),
			connect.WithClientOptions(opts...),
		),
		updateSkill: connect.NewClient[v1.UpdateSkillRequest, v1.UpdateSkillResponse](
			httpClient,
			baseURL+AgentServiceUpdateSkillProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateSkill")),
			connect.WithClientOptions(opts...),
		),
		deleteSkill: connect.NewClient[v1.DeleteSkillRequest, v1.DeleteSkillResponse](
			httpClient,
			baseURL+AgentServiceDeleteSkillProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteSkill")),
			connect.WithClientOptions(opts...),
		),
		createChat: connect.NewClient[v1.CreateChatRequest, v1.CreateChatResponse](
			httpClient,
			baseURL+AgentServiceCreateChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateChat")),
			connect.WithClientOptions(opts...),
		),
		listChats: connect.NewClient[v1.ListChatsRequest, v1.ListChatsResponse](
			httpClient,
			baseURL+AgentServiceListChatsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListChats")),
			connect.WithClientOptions(opts...),
		),
		sendChatMessage: connect.NewClient[v1.SendChatMessageRequest, v1.SendChatMessageResponse](
			httpClient,
			baseURL+AgentServiceSendChatMessageProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SendChatMessage")),
			connect.WithClientOptions(opts...),
		),
		streamChat: connect.NewClient[v1.StreamChatRequest, v1.ChatFrame](
			httpClient,
			baseURL+AgentServiceStreamChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamChat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	listSessions     *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession       *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	listTurns        *connect.Client[v1.ListTurnsRequest, v1.ListTurnsResponse]
	getSettings      *connect.Client[v1.GetSettingsRequest, v1.GetSettingsResponse]
	setProviderKey   *connect.Client[v1.SetProviderKeyRequest, v1.SetProviderKeyResponse]
	clearProviderKey *connect.Client[v1.ClearProviderKeyRequest, v1.ClearProviderKeyResponse]
	listMemories     *connect.Client[v1.ListMemoriesRequest, v1.ListMemoriesResponse]
	searchMemories   *connect.Client[v1.SearchMemoriesRequest, v1.SearchMemoriesResponse]
	deleteMemory     *connect.Client[v1.DeleteMemoryRequest, v1.DeleteMemoryResponse]
	listSkills       *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	getProfile       *connect.Client[v1.GetProfileRequest, v1.GetProfileResponse]
	updateProfile    *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
	createSkill      *connect.Client[v1.CreateSkillRequest, v1.CreateSkillResponse]
	updateSkill      *connect.Client[v1.UpdateSkillRequest, v1.UpdateSkillResponse]
	deleteSkill      *connect.Client[v1.DeleteSkillRequest, v1.DeleteSkillResponse]
	createChat       *connect.Client[v1.CreateChatRequest, v1.CreateChatResponse]
	listChats        *connect.Client[v1.ListChatsRequest, v1.ListChatsResponse]
	sendChatMessage  *connect.Client[v1.SendChatMessageRequest, v1.SendChatMessageResponse]
	streamChat       *connect.Client[v1.StreamChatRequest, v1.ChatFrame]
}

// ListSessions calls podium.agent.v1.AgentService.ListSessions.
func (c *agentServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls podium.agent.v1.AgentService.GetSession.
func (c *agentServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListTurns calls podium.agent.v1.AgentService.ListTurns.
func (c *agentServiceClient) ListTurns(ctx context.Context, req *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return c.listTurns.CallUnary(ctx, req)
}

// GetSettings calls podium.agent.v1.AgentService.GetSettings.
func (c *agentServiceClient) GetSettings(ctx context.Context, req *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return c.getSettings.CallUnary(ctx, req)
}

// SetProviderKey calls podium.agent.v1.AgentService.SetProviderKey.
func (c *agentServiceClient) SetProviderKey(ctx context.Context, req *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error) {
	return c.setProviderKey.CallUnary(ctx, req)
}

// ClearProviderKey calls podium.agent.v1.AgentService.ClearProviderKey.
func (c *agentServiceClient) ClearProviderKey(ctx context.Context, req *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error) {
	return c.clearProviderKey.CallUnary(ctx, req)
}

// ListMemories calls podium.agent.v1.AgentService.ListMemories.
func (c *agentServiceClient) ListMemories(ctx context.Context, req *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error) {
	return c.listMemories.CallUnary(ctx, req)
}

// SearchMemories calls podium.agent.v1.AgentService.SearchMemories.
func (c *agentServiceClient) SearchMemories(ctx context.Context, req *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error) {
	return c.searchMemories.CallUnary(ctx, req)
}

// DeleteMemory calls podium.agent.v1.AgentService.DeleteMemory.
func (c *agentServiceClient) DeleteMemory(ctx context.Context, req *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error) {
	return c.deleteMemory.CallUnary(ctx, req)
}

// ListSkills calls podium.agent.v1.AgentService.ListSkills.
func (c *agentServiceClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// GetProfile calls podium.agent.v1.AgentService.GetProfile.
func (c *agentServiceClient) GetProfile(ctx context.Context, req *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// UpdateProfile calls podium.agent.v1.AgentService.UpdateProfile.
func (c *agentServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// CreateSkill calls podium.agent.v1.AgentService.CreateSkill.
func (c *agentServiceClient) CreateSkill(ctx context.Context, req *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return c.createSkill.CallUnary(ctx, req)
}

// UpdateSkill calls podium.agent.v1.AgentService.UpdateSkill.
func (c *agentServiceClient) UpdateSkill(ctx context.Context, req *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return c.updateSkill.CallUnary(ctx, req)
}

// DeleteSkill calls podium.agent.v1.AgentService.DeleteSkill.
func (c *agentServiceClient) DeleteSkill(ctx context.Context, req *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return c.deleteSkill.CallUnary(ctx, req)
}

// CreateChat calls podium.agent.v1.AgentService.CreateChat.
func (c *agentServiceClient) CreateChat(ctx context.Context, req *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error) {
	return c.createChat.CallUnary(ctx, req)
}

// ListChats calls podium.agent.v1.AgentService.ListChats.
func (c *agentServiceClient) ListChats(ctx context.Context, req *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error) {
	return c.listChats.CallUnary(ctx, req)
}

// SendChatMessage calls podium.agent.v1.AgentService.SendChatMessage.
func (c *agentServiceClient) SendChatMessage(ctx context.Context, req *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error) {
	return c.sendChatMessage.CallUnary(ctx, req)
}

// StreamChat calls podium.agent.v1.AgentService.StreamChat.
func (c *agentServiceClient) StreamChat(ctx context.Context, req *connect.Request[v1.StreamChatRequest]) (*connect.ServerStreamForClient[v1.ChatFrame], error) {
	return c.streamChat.CallServerStream(ctx, req)
}

// AgentServiceHandler is an implementation of the podium.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
	// GetSettings reports what the conductor is configured with. It reads no secret value:
	// there is no read endpoint on the secret store, by design.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// SetProviderKey validates a provider key with the provider itself and, only if that
	// succeeds, stores it as a Podium secret. An unvalidated key is never saved.
	SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error)
	// ClearProviderKey removes the secret and the metadata. Calling it twice is not an error.
	ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error)
	// ListMemories pages through the shared memory, newest first.
	ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error)
	// SearchMemories is a semantic search of the same memory.
	SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error)
	// DeleteMemory takes one memory out of every future recall. It is a tombstone rather
	// than a row deletion: the memory engine keeps the record for audit and stops serving it.
	DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error)
	// ListSkills reports the profile's skills so the chat can offer them. Nothing secret:
	// a name, an image and which one the chat starts with.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// GetProfile reports the profile a turn actually runs from — profile.yaml and skills/
	// merged with what the conductor's database holds — and every skill in full, so a
	// browser can manage them.
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	// UpdateProfile overrides profile.yaml's display name, model and default skills. An
	// empty field clears the override and returns that field to the file's value.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// CreateSkill stores a new skill in the conductor's database. A name a skills/*.yaml
	// already defines is refused: the files are authoritative for the names they hold.
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	// UpdateSkill replaces a stored skill. A file-defined skill is refused.
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	// DeleteSkill removes a stored skill. A file-defined skill is refused; deleting a
	// stored skill that is not there is not an error.
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	// CreateChat opens a new web-chat conversation owned by the calling login.
	CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error)
	// ListChats returns the caller's own chats, newest first. Another login's chats are
	// never returned.
	ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error)
	// SendChatMessage stores one human message and starts a turn on it. It is refused with
	// FailedPrecondition while a turn for that chat is already running: one turn at a time
	// per conversation is the whole model.
	SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error)
	// StreamChat replays a chat from from_seq and then follows it live. It never ends on its
	// own; the client cancels. Progress frames are ephemeral and are not replayed.
	StreamChat(context.Context, *connect.Request[v1.StreamChatRequest], *connect.ServerStream[v1.ChatFrame]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceListSessionsHandler := connect.NewUnaryHandler(
		AgentServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSessionHandler := connect.NewUnaryHandler(
		AgentServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(agentServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListTurnsHandler := connect.NewUnaryHandler(
		AgentServiceListTurnsProcedure,
		svc.ListTurns,
		connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSettingsHandler := connect.NewUnaryHandler(
		AgentServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(agentServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetProviderKeyHandler := connect.NewUnaryHandler(
		AgentServiceSetProviderKeyProcedure,
		svc.SetProviderKey,
		connect.WithSchema(agentServiceMethods.ByName("SetProviderKey")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceClearProviderKeyHandler := connect.NewUnaryHandler(
		AgentServiceClearProviderKeyProcedure,
		svc.ClearProviderKey,
		connect.WithSchema(agentServiceMethods.ByName("ClearProviderKey")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListMemoriesHandler := connect.NewUnaryHandler(
		AgentServiceListMemoriesProcedure,
		svc.ListMemories,
		connect.WithSchema(agentServiceMethods.ByName("ListMemories")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSearchMemoriesHandler := connect.NewUnaryHandler(
		AgentServiceSearchMemoriesProcedure,
		svc.SearchMemories,
		connect.WithSchema(agentServiceMethods.ByName("SearchMemories")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteMemoryHandler := connect.NewUnaryHandler(
		AgentServiceDeleteMemoryProcedure,
		svc.DeleteMemory,
		connect.WithSchema(agentServiceMethods.ByName("DeleteMemory")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListSkillsHandler := connect.NewUnaryHandler(
		AgentServiceListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(agentServiceMethods.ByName("ListSkills")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetProfileHandler := connect.NewUnaryHandler(
		AgentServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(agentServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateProfileHandler := connect.NewUnaryHandler(
		AgentServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(agentServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCreateSkillHandler := connect.NewUnaryHandler(
		AgentServiceCreateSkillProcedure,
		svc.CreateSkill,
		connect.WithSchema(agentServiceMethods.ByName("CreateSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateSkillHandler := connect.NewUnaryHandler(
		AgentServiceUpdateSkillProcedure,
		svc.UpdateSkill,
		connect.WithSchema(agentServiceMethods.ByName("UpdateSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteSkillHandler := connect.NewUnaryHandler(
		AgentServiceDeleteSkillProcedure,
		svc.DeleteSkill,
		connect.WithSchema(agentServiceMethods.ByName("DeleteSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCreateChatHandler := connect.NewUnaryHandler(
		AgentServiceCreateChatProcedure,
		svc.CreateChat,
		connect.WithSchema(agentServiceMethods.ByName("CreateChat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListChatsHandler := connect.NewUnaryHandler(
		AgentServiceListChatsProcedure,
		svc.ListChats,
		connect.WithSchema(agentServiceMethods.ByName("ListChats")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSendChatMessageHandler := connect.NewUnaryHandler(
		AgentServiceSendChatMessageProcedure,
		svc.SendChatMessage,
		connect.WithSchema(agentServiceMethods.ByName("SendChatMessage")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamChatHandler := connect.NewServerStreamHandler(
		AgentServiceStreamChatProcedure,
		svc.StreamChat,
		connect.WithSchema(agentServiceMethods.ByName("StreamChat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListSessionsProcedure:
			agentServiceListSessionsHandler.ServeHTTP(w, r)
		case AgentServiceGetSessionProcedure:
			agentServiceGetSessionHandler.ServeHTTP(w, r)
		case AgentServiceListTurnsProcedure:
			agentServiceListTurnsHandler.ServeHTTP(w, r)
		case AgentServiceGetSettingsProcedure:
			agentServiceGetSettingsHandler.ServeHTTP(w, r)
		case AgentServiceSetProviderKeyProcedure:
			agentServiceSetProviderKeyHandler.ServeHTTP(w, r)
		case AgentServiceClearProviderKeyProcedure:
			agentServiceClearProviderKeyHandler.ServeHTTP(w, r)
		case AgentServiceListMemoriesProcedure:
			agentServiceListMemoriesHandler.ServeHTTP(w, r)
		case AgentServiceSearchMemoriesProcedure:
			agentServiceSearchMemoriesHandler.ServeHTTP(w, r)
		case AgentServiceDeleteMemoryProcedure:
			agentServiceDeleteMemoryHandler.ServeHTTP(w, r)
		case AgentServiceListSkillsProcedure:
			agentServiceListSkillsHandler.ServeHTTP(w, r)
		case AgentServiceGetProfileProcedure:
			agentServiceGetProfileHandler.ServeHTTP(w, r)
		case AgentServiceUpdateProfileProcedure:
			agentServiceUpdateProfileHandler.ServeHTTP(w, r)
		case AgentServiceCreateSkillProcedure:
			agentServiceCreateSkillHandler.ServeHTTP(w, r)
		case AgentServiceUpdateSkillProcedure:
			agentServiceUpdateSkillHandler.ServeHTTP(w, r)
		case AgentServiceDeleteSkillProcedure:
			agentServiceDeleteSkillHandler.ServeHTTP(w, r)
		case AgentServiceCreateChatProcedure:
			agentServiceCreateChatHandler.ServeHTTP(w, r)
		case AgentServiceListChatsProcedure:
			agentServiceListChatsHandler.ServeHTTP(w, r)
		case AgentServiceSendChatMessageProcedure:
			agentServiceSendChatMessageHandler.ServeHTTP(w, r)
		case AgentServiceStreamChatProcedure:
			agentServiceStreamChatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListSessions is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListTurns is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetSettings is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SetProviderKey is not implemented"))
}

func (UnimplementedAgentServiceHandler) ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ClearProviderKey is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListMemories is not implemented"))
}

func (UnimplementedAgentServiceHandler) SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SearchMemories is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DeleteMemory is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListSkills is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetProfile is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.UpdateProfile is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.CreateSkill is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.UpdateSkill is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DeleteSkill is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.CreateChat is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListChats is not implemented"))
}

func (UnimplementedAgentServiceHandler) SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SendChatMessage is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamChat(context.Context, *connect.Request[v1.StreamChatRequest], *connect.ServerStream[v1.ChatFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.StreamChat is not implemented"))
}
