// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alvaroibarguen/podium/internal/proto/podium/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "podium.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceListSessionsProcedure is the fully-qualified name of the AgentService's ListSessions
	// RPC.
	AgentServiceListSessionsProcedure = "/podium.agent.v1.AgentService/ListSessions"
	// AgentServiceGetSessionProcedure is the fully-qualified name of the AgentService's GetSession RPC.
	AgentServiceGetSessionProcedure = "/podium.agent.v1.AgentService/GetSession"
	// AgentServiceListTurnsProcedure is the fully-qualified name of the AgentService's ListTurns RPC.
	AgentServiceListTurnsProcedure = "/podium.agent.v1.AgentService/ListTurns"
)

// AgentServiceClient is a client for the podium.agent.v1.AgentService service.
type AgentServiceClient interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
}

// NewAgentServiceClient constructs a client for the podium.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+AgentServiceListSessionsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+AgentServiceGetSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listTurns: connect.NewClient[v1.ListTurnsRequest, v1.ListTurnsResponse](
			httpClient,
			baseURL+AgentServiceListTurnsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	listSessions *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession   *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	listTurns    *connect.Client[v1.ListTurnsRequest, v1.ListTurnsResponse]
}

// ListSessions calls podium.agent.v1.AgentService.ListSessions.
func (c *agentServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls podium.agent.v1.AgentService.GetSession.
func (c *agentServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListTurns calls podium.agent.v1.AgentService.ListTurns.
func (c *agentServiceClient) ListTurns(ctx context.Context, req *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return c.listTurns.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the podium.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceListSessionsHandler := connect.NewUnaryHandler(
		AgentServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSessionHandler := connect.NewUnaryHandler(
		AgentServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(agentServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListTurnsHandler := connect.NewUnaryHandler(
		AgentServiceListTurnsProcedure,
		svc.ListTurns,
		connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListSessionsProcedure:
			agentServiceListSessionsHandler.ServeHTTP(w, r)
		case AgentServiceGetSessionProcedure:
			agentServiceGetSessionHandler.ServeHTTP(w, r)
		case AgentServiceListTurnsProcedure:
			agentServiceListTurnsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListSessions is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListTurns is not implemented"))
}
