// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/podium-ade/podium/internal/proto/podium/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "podium.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceListSessionsProcedure is the fully-qualified name of the AgentService's ListSessions
	// RPC.
	AgentServiceListSessionsProcedure = "/podium.agent.v1.AgentService/ListSessions"
	// AgentServiceGetSessionProcedure is the fully-qualified name of the AgentService's GetSession RPC.
	AgentServiceGetSessionProcedure = "/podium.agent.v1.AgentService/GetSession"
	// AgentServiceListTurnsProcedure is the fully-qualified name of the AgentService's ListTurns RPC.
	AgentServiceListTurnsProcedure = "/podium.agent.v1.AgentService/ListTurns"
	// AgentServiceGetUsageProcedure is the fully-qualified name of the AgentService's GetUsage RPC.
	AgentServiceGetUsageProcedure = "/podium.agent.v1.AgentService/GetUsage"
	// AgentServiceGetSettingsProcedure is the fully-qualified name of the AgentService's GetSettings
	// RPC.
	AgentServiceGetSettingsProcedure = "/podium.agent.v1.AgentService/GetSettings"
	// AgentServiceSetProviderKeyProcedure is the fully-qualified name of the AgentService's
	// SetProviderKey RPC.
	AgentServiceSetProviderKeyProcedure = "/podium.agent.v1.AgentService/SetProviderKey"
	// AgentServiceClearProviderKeyProcedure is the fully-qualified name of the AgentService's
	// ClearProviderKey RPC.
	AgentServiceClearProviderKeyProcedure = "/podium.agent.v1.AgentService/ClearProviderKey"
	// AgentServiceStartProviderOAuthProcedure is the fully-qualified name of the AgentService's
	// StartProviderOAuth RPC.
	AgentServiceStartProviderOAuthProcedure = "/podium.agent.v1.AgentService/StartProviderOAuth"
	// AgentServicePollProviderOAuthProcedure is the fully-qualified name of the AgentService's
	// PollProviderOAuth RPC.
	AgentServicePollProviderOAuthProcedure = "/podium.agent.v1.AgentService/PollProviderOAuth"
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/podium.agent.v1.AgentService/ListAgents"
	// AgentServiceListMemoriesProcedure is the fully-qualified name of the AgentService's ListMemories
	// RPC.
	AgentServiceListMemoriesProcedure = "/podium.agent.v1.AgentService/ListMemories"
	// AgentServiceSearchMemoriesProcedure is the fully-qualified name of the AgentService's
	// SearchMemories RPC.
	AgentServiceSearchMemoriesProcedure = "/podium.agent.v1.AgentService/SearchMemories"
	// AgentServiceDeleteMemoryProcedure is the fully-qualified name of the AgentService's DeleteMemory
	// RPC.
	AgentServiceDeleteMemoryProcedure = "/podium.agent.v1.AgentService/DeleteMemory"
	// AgentServiceListPlaybooksProcedure is the fully-qualified name of the AgentService's
	// ListPlaybooks RPC.
	AgentServiceListPlaybooksProcedure = "/podium.agent.v1.AgentService/ListPlaybooks"
	// AgentServiceGetProfileProcedure is the fully-qualified name of the AgentService's GetProfile RPC.
	AgentServiceGetProfileProcedure = "/podium.agent.v1.AgentService/GetProfile"
	// AgentServiceUpdateProfileProcedure is the fully-qualified name of the AgentService's
	// UpdateProfile RPC.
	AgentServiceUpdateProfileProcedure = "/podium.agent.v1.AgentService/UpdateProfile"
	// AgentServiceReloadProfileDirProcedure is the fully-qualified name of the AgentService's
	// ReloadProfileDir RPC.
	AgentServiceReloadProfileDirProcedure = "/podium.agent.v1.AgentService/ReloadProfileDir"
	// AgentServiceListSkillsProcedure is the fully-qualified name of the AgentService's ListSkills RPC.
	AgentServiceListSkillsProcedure = "/podium.agent.v1.AgentService/ListSkills"
	// AgentServiceListMcpServersProcedure is the fully-qualified name of the AgentService's
	// ListMcpServers RPC.
	AgentServiceListMcpServersProcedure = "/podium.agent.v1.AgentService/ListMcpServers"
	// AgentServiceCreateMcpServerProcedure is the fully-qualified name of the AgentService's
	// CreateMcpServer RPC.
	AgentServiceCreateMcpServerProcedure = "/podium.agent.v1.AgentService/CreateMcpServer"
	// AgentServiceUpdateMcpServerProcedure is the fully-qualified name of the AgentService's
	// UpdateMcpServer RPC.
	AgentServiceUpdateMcpServerProcedure = "/podium.agent.v1.AgentService/UpdateMcpServer"
	// AgentServiceDeleteMcpServerProcedure is the fully-qualified name of the AgentService's
	// DeleteMcpServer RPC.
	AgentServiceDeleteMcpServerProcedure = "/podium.agent.v1.AgentService/DeleteMcpServer"
	// AgentServiceSetMcpServerTokenProcedure is the fully-qualified name of the AgentService's
	// SetMcpServerToken RPC.
	AgentServiceSetMcpServerTokenProcedure = "/podium.agent.v1.AgentService/SetMcpServerToken"
	// AgentServiceClearMcpServerTokenProcedure is the fully-qualified name of the AgentService's
	// ClearMcpServerToken RPC.
	AgentServiceClearMcpServerTokenProcedure = "/podium.agent.v1.AgentService/ClearMcpServerToken"
	// AgentServiceStartMcpOAuthProcedure is the fully-qualified name of the AgentService's
	// StartMcpOAuth RPC.
	AgentServiceStartMcpOAuthProcedure = "/podium.agent.v1.AgentService/StartMcpOAuth"
	// AgentServiceCompleteMcpOAuthProcedure is the fully-qualified name of the AgentService's
	// CompleteMcpOAuth RPC.
	AgentServiceCompleteMcpOAuthProcedure = "/podium.agent.v1.AgentService/CompleteMcpOAuth"
	// AgentServiceCreateChatProcedure is the fully-qualified name of the AgentService's CreateChat RPC.
	AgentServiceCreateChatProcedure = "/podium.agent.v1.AgentService/CreateChat"
	// AgentServiceListChatsProcedure is the fully-qualified name of the AgentService's ListChats RPC.
	AgentServiceListChatsProcedure = "/podium.agent.v1.AgentService/ListChats"
	// AgentServiceRenameChatProcedure is the fully-qualified name of the AgentService's RenameChat RPC.
	AgentServiceRenameChatProcedure = "/podium.agent.v1.AgentService/RenameChat"
	// AgentServiceDeleteChatProcedure is the fully-qualified name of the AgentService's DeleteChat RPC.
	AgentServiceDeleteChatProcedure = "/podium.agent.v1.AgentService/DeleteChat"
	// AgentServiceSendChatMessageProcedure is the fully-qualified name of the AgentService's
	// SendChatMessage RPC.
	AgentServiceSendChatMessageProcedure = "/podium.agent.v1.AgentService/SendChatMessage"
	// AgentServiceStreamChatProcedure is the fully-qualified name of the AgentService's StreamChat RPC.
	AgentServiceStreamChatProcedure = "/podium.agent.v1.AgentService/StreamChat"
	// AgentServiceAttachChatPullRequestProcedure is the fully-qualified name of the AgentService's
	// AttachChatPullRequest RPC.
	AgentServiceAttachChatPullRequestProcedure = "/podium.agent.v1.AgentService/AttachChatPullRequest"
	// AgentServiceDetachChatPullRequestProcedure is the fully-qualified name of the AgentService's
	// DetachChatPullRequest RPC.
	AgentServiceDetachChatPullRequestProcedure = "/podium.agent.v1.AgentService/DetachChatPullRequest"
)

// AgentServiceClient is a client for the podium.agent.v1.AgentService service.
type AgentServiceClient interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
	// GetUsage reports what the conductor spent over a range: a total per day for the
	// calendar, and the cost of each individual turn keyed by the task it ran as.
	//
	// It answers only for turns. The tasks themselves live in the control plane's database,
	// which this one deliberately does not reference, so the browser asks both and joins them
	// on task_id — that is why a task with no turn behind it simply has no cost, rather than
	// a cost of zero.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
	// GetSettings reports what the conductor is configured with. It reads no secret value:
	// there is no read endpoint on the secret store, by design.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// SetProviderKey validates a provider key with the provider itself and, only if that
	// succeeds, stores it as a Podium secret. An unvalidated key is never saved.
	SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error)
	// ClearProviderKey removes the secret and the metadata. Calling it twice is not an error.
	ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error)
	// StartProviderOAuth begins a device-authorisation sign-in for a provider that takes a
	// subscription instead of an API key. It stores nothing: it returns the code and the URL
	// a human has to visit, and PollProviderOAuth is what finishes.
	StartProviderOAuth(context.Context, *connect.Request[v1.StartProviderOAuthRequest]) (*connect.Response[v1.StartProviderOAuthResponse], error)
	// PollProviderOAuth asks the provider whether the human has approved the sign-in yet. It
	// is the browser that polls, at the interval the start response asked for. Only the call
	// that comes back authorised stores anything.
	PollProviderOAuth(context.Context, *connect.Request[v1.PollProviderOAuthRequest]) (*connect.Response[v1.PollProviderOAuthResponse], error)
	// ListAgents reports the agent backends this conductor can run a turn on, the models each
	// offers and the effort levels each model accepts. It is the catalogue behind the UI's
	// picker, and it is the same list the write RPCs validate against.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// ListMemories pages through the shared memory, newest first.
	ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error)
	// SearchMemories is a semantic search of the same memory.
	SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error)
	// DeleteMemory takes one memory out of every future recall. It is a tombstone rather
	// than a row deletion: the memory engine keeps the record for audit and stops serving it.
	DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error)
	// ListPlaybooks reports the profile's playbooks so the chat can offer them. Nothing secret:
	// a name, an image and which one the chat starts with.
	ListPlaybooks(context.Context, *connect.Request[v1.ListPlaybooksRequest]) (*connect.Response[v1.ListPlaybooksResponse], error)
	// GetProfile reports the profile a turn actually runs from — profile.yaml and
	// playbooks/*.yaml, with the Assistant-screen overrides on top — and every playbook in
	// full, so a browser can read them. Playbooks are files; this RPC does not write one.
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	// UpdateProfile overrides profile.yaml's display name, model and default playbooks. An
	// empty field clears the override and returns that field to the file's value.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// ReloadProfileDir re-reads the conductor's profile directory — profile.yaml, every
	// playbooks/*.yaml and every prompt file they name — and swaps what it finds into the
	// running profile.
	//
	// It is what an operator who has just edited that YAML does instead of restarting the
	// process. Only an operator asks: a directory halfway through being saved does not load,
	// and a load failure is refused here and changes nothing, so a conductor is never left
	// running half a profile.
	ReloadProfileDir(context.Context, *connect.Request[v1.ReloadProfileDirRequest]) (*connect.Response[v1.ReloadProfileDirResponse], error)
	// ListSkills reports every Agent Skill under PODIUM_AGENT_SKILLS_DIR on this host. Skills
	// are directories with a SKILL.md; this RPC does not write one.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// ListMcpServers reports every MCP server registered on this conductor, with which
	// playbooks name each one. It never carries a token: a server's credential is a Podium
	// secret and the last four characters kept at save time are all any client ever sees.
	ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error)
	// CreateMcpServer registers a new one. The URL is validated as an absolute http(s) URL and
	// nothing else about it is assumed: whether the server answers is found out by a turn.
	CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error)
	// UpdateMcpServer replaces a registered server's definition, leaving its token alone.
	UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error)
	// DeleteMcpServer removes one and its stored token. A playbook that still names it fails
	// its turns saying so, which is why ListMcpServers reports who names what.
	DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error)
	// SetMcpServerToken stores the credential this server authenticates with, as a Podium
	// secret. It is never read back and never written into a turn's config file — the config
	// names the environment variable the conductor delivers it in.
	SetMcpServerToken(context.Context, *connect.Request[v1.SetMcpServerTokenRequest]) (*connect.Response[v1.SetMcpServerTokenResponse], error)
	// ClearMcpServerToken removes it. The server stays registered and reaches its turns with
	// no authorization header at all, which is what an unauthenticated server wants.
	ClearMcpServerToken(context.Context, *connect.Request[v1.ClearMcpServerTokenRequest]) (*connect.Response[v1.ClearMcpServerTokenResponse], error)
	// StartMcpOAuth begins an OAuth sign-in against an MCP server that wants one, and answers
	// with the URL to send the operator's browser to. Everything about the server's OAuth is
	// DISCOVERED — the protected-resource metadata names its authorization server, and that
	// server's own metadata names its endpoints — and the client is registered dynamically, so
	// no part of it is configuration an operator has to supply.
	//
	// The PKCE verifier stays on the conductor. A browser is handed a flow id and a URL, which
	// name a sign-in rather than bearing one.
	StartMcpOAuth(context.Context, *connect.Request[v1.StartMcpOAuthRequest]) (*connect.Response[v1.StartMcpOAuthResponse], error)
	// CompleteMcpOAuth trades the authorization code the browser came back with for a token,
	// and stores it exactly as a pasted one is stored. The code arrives over this API rather
	// than on a redirect the server would have to serve unauthenticated — see
	// docs/agent.md#signing-in-to-an-mcp-server.
	CompleteMcpOAuth(context.Context, *connect.Request[v1.CompleteMcpOAuthRequest]) (*connect.Response[v1.CompleteMcpOAuthResponse], error)
	// CreateChat opens a new web-chat conversation owned by the calling login.
	CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error)
	// ListChats returns the caller's own chats, newest first. Another login's chats are
	// never returned.
	ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error)
	// RenameChat changes the title of one of the caller's chats. Another login's chat is
	// not_found, the same as every other chat RPC. An empty title is refused.
	RenameChat(context.Context, *connect.Request[v1.RenameChatRequest]) (*connect.Response[v1.RenameChatResponse], error)
	// DeleteChat removes one of the caller's chats and every message in it. Another
	// login's chat is not_found, the same as a chat that is not there: the existence of
	// somebody else's conversation is not this caller's to learn. Sessions and turns the
	// chat started are kept — they are the audit, not the transcript.
	DeleteChat(context.Context, *connect.Request[v1.DeleteChatRequest]) (*connect.Response[v1.DeleteChatResponse], error)
	// SendChatMessage stores one human message and starts a turn on it. It is refused with
	// FailedPrecondition while a turn for that chat is already running, unless that turn is
	// awaiting a human reply (an interactive playbook asked a question): then the text is
	// injected into the running task and no second turn starts.
	SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error)
	// StreamChat replays a chat from from_seq and then follows it live. It never ends on its
	// own; the client cancels. Progress frames are ephemeral and are not replayed.
	StreamChat(context.Context, *connect.Request[v1.StreamChatRequest]) (*connect.ServerStreamForClient[v1.ChatFrame], error)
	// AttachChatPullRequest links a pull request to one of the caller's chats by hand, for
	// the one a turn never named or a related one a human wants on the conversation. A URL
	// that is not a GitHub pull request is invalid_argument; the same URL twice is one link.
	AttachChatPullRequest(context.Context, *connect.Request[v1.AttachChatPullRequestRequest]) (*connect.Response[v1.AttachChatPullRequestResponse], error)
	// DetachChatPullRequest takes one link off. A link a turn found stays off: the next turn
	// in the same chat will not put it back, because a human removing something means it.
	// Attaching it again is how it comes back.
	DetachChatPullRequest(context.Context, *connect.Request[v1.DetachChatPullRequestRequest]) (*connect.Response[v1.DetachChatPullRequestResponse], error)
}

// NewAgentServiceClient constructs a client for the podium.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+AgentServiceListSessionsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+AgentServiceGetSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listTurns: connect.NewClient[v1.ListTurnsRequest, v1.ListTurnsResponse](
			httpClient,
			baseURL+AgentServiceListTurnsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
			connect.WithClientOptions(opts...),
		),
		getUsage: connect.NewClient[v1.GetUsageRequest, v1.GetUsageResponse](
			httpClient,
			baseURL+AgentServiceGetUsageProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetUsage")),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[v1.GetSettingsRequest, v1.GetSettingsResponse](
			httpClient,
			baseURL+AgentServiceGetSettingsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		setProviderKey: connect.NewClient[v1.SetProviderKeyRequest, v1.SetProviderKeyResponse](
			httpClient,
			baseURL+AgentServiceSetProviderKeyProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetProviderKey")),
			connect.WithClientOptions(opts...),
		),
		clearProviderKey: connect.NewClient[v1.ClearProviderKeyRequest, v1.ClearProviderKeyResponse](
			httpClient,
			baseURL+AgentServiceClearProviderKeyProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ClearProviderKey")),
			connect.WithClientOptions(opts...),
		),
		startProviderOAuth: connect.NewClient[v1.StartProviderOAuthRequest, v1.StartProviderOAuthResponse](
			httpClient,
			baseURL+AgentServiceStartProviderOAuthProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StartProviderOAuth")),
			connect.WithClientOptions(opts...),
		),
		pollProviderOAuth: connect.NewClient[v1.PollProviderOAuthRequest, v1.PollProviderOAuthResponse](
			httpClient,
			baseURL+AgentServicePollProviderOAuthProcedure,
			connect.WithSchema(agentServiceMethods.ByName("PollProviderOAuth")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		listMemories: connect.NewClient[v1.ListMemoriesRequest, v1.ListMemoriesResponse](
			httpClient,
			baseURL+AgentServiceListMemoriesProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListMemories")),
			connect.WithClientOptions(opts...),
		),
		searchMemories: connect.NewClient[v1.SearchMemoriesRequest, v1.SearchMemoriesResponse](
			httpClient,
			baseURL+AgentServiceSearchMemoriesProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SearchMemories")),
			connect.WithClientOptions(opts...),
		),
		deleteMemory: connect.NewClient[v1.DeleteMemoryRequest, v1.DeleteMemoryResponse](
			httpClient,
			baseURL+AgentServiceDeleteMemoryProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteMemory")),
			connect.WithClientOptions(opts...),
		),
		listPlaybooks: connect.NewClient[v1.ListPlaybooksRequest, v1.ListPlaybooksResponse](
			httpClient,
			baseURL+AgentServiceListPlaybooksProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListPlaybooks")),
			connect.WithClientOptions(opts...),
		),
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.GetProfileResponse](
			httpClient,
			baseURL+AgentServiceGetProfileProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+AgentServiceUpdateProfileProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		reloadProfileDir: connect.NewClient[v1.ReloadProfileDirRequest, v1.ReloadProfileDirResponse](
			httpClient,
			baseURL+AgentServiceReloadProfileDirProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ReloadProfileDir")),
			connect.WithClientOptions(opts...),
		),
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+AgentServiceListSkillsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListSkills")),
			connect.WithClientOptions(opts...),
		),
		listMcpServers: connect.NewClient[v1.ListMcpServersRequest, v1.ListMcpServersResponse](
			httpClient,
			baseURL+AgentServiceListMcpServersProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListMcpServers")),
			connect.WithClientOptions(opts...),
		),
		createMcpServer: connect.NewClient[v1.CreateMcpServerRequest, v1.CreateMcpServerResponse](
			httpClient,
			baseURL+AgentServiceCreateMcpServerProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateMcpServer")),
			connect.WithClientOptions(opts...),
		),
		updateMcpServer: connect.NewClient[v1.UpdateMcpServerRequest, v1.UpdateMcpServerResponse](
			httpClient,
			baseURL+AgentServiceUpdateMcpServerProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateMcpServer")),
			connect.WithClientOptions(opts...),
		),
		deleteMcpServer: connect.NewClient[v1.DeleteMcpServerRequest, v1.DeleteMcpServerResponse](
			httpClient,
			baseURL+AgentServiceDeleteMcpServerProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteMcpServer")),
			connect.WithClientOptions(opts...),
		),
		setMcpServerToken: connect.NewClient[v1.SetMcpServerTokenRequest, v1.SetMcpServerTokenResponse](
			httpClient,
			baseURL+AgentServiceSetMcpServerTokenProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetMcpServerToken")),
			connect.WithClientOptions(opts...),
		),
		clearMcpServerToken: connect.NewClient[v1.ClearMcpServerTokenRequest, v1.ClearMcpServerTokenResponse](
			httpClient,
			baseURL+AgentServiceClearMcpServerTokenProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ClearMcpServerToken")),
			connect.WithClientOptions(opts...),
		),
		startMcpOAuth: connect.NewClient[v1.StartMcpOAuthRequest, v1.StartMcpOAuthResponse](
			httpClient,
			baseURL+AgentServiceStartMcpOAuthProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StartMcpOAuth")),
			connect.WithClientOptions(opts...),
		),
		completeMcpOAuth: connect.NewClient[v1.CompleteMcpOAuthRequest, v1.CompleteMcpOAuthResponse](
			httpClient,
			baseURL+AgentServiceCompleteMcpOAuthProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CompleteMcpOAuth")),
			connect.WithClientOptions(opts...),
		),
		createChat: connect.NewClient[v1.CreateChatRequest, v1.CreateChatResponse](
			httpClient,
			baseURL+AgentServiceCreateChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateChat")),
			connect.WithClientOptions(opts...),
		),
		listChats: connect.NewClient[v1.ListChatsRequest, v1.ListChatsResponse](
			httpClient,
			baseURL+AgentServiceListChatsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListChats")),
			connect.WithClientOptions(opts...),
		),
		renameChat: connect.NewClient[v1.RenameChatRequest, v1.RenameChatResponse](
			httpClient,
			baseURL+AgentServiceRenameChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RenameChat")),
			connect.WithClientOptions(opts...),
		),
		deleteChat: connect.NewClient[v1.DeleteChatRequest, v1.DeleteChatResponse](
			httpClient,
			baseURL+AgentServiceDeleteChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteChat")),
			connect.WithClientOptions(opts...),
		),
		sendChatMessage: connect.NewClient[v1.SendChatMessageRequest, v1.SendChatMessageResponse](
			httpClient,
			baseURL+AgentServiceSendChatMessageProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SendChatMessage")),
			connect.WithClientOptions(opts...),
		),
		streamChat: connect.NewClient[v1.StreamChatRequest, v1.ChatFrame](
			httpClient,
			baseURL+AgentServiceStreamChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamChat")),
			connect.WithClientOptions(opts...),
		),
		attachChatPullRequest: connect.NewClient[v1.AttachChatPullRequestRequest, v1.AttachChatPullRequestResponse](
			httpClient,
			baseURL+AgentServiceAttachChatPullRequestProcedure,
			connect.WithSchema(agentServiceMethods.ByName("AttachChatPullRequest")),
			connect.WithClientOptions(opts...),
		),
		detachChatPullRequest: connect.NewClient[v1.DetachChatPullRequestRequest, v1.DetachChatPullRequestResponse](
			httpClient,
			baseURL+AgentServiceDetachChatPullRequestProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DetachChatPullRequest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	listSessions          *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession            *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	listTurns             *connect.Client[v1.ListTurnsRequest, v1.ListTurnsResponse]
	getUsage              *connect.Client[v1.GetUsageRequest, v1.GetUsageResponse]
	getSettings           *connect.Client[v1.GetSettingsRequest, v1.GetSettingsResponse]
	setProviderKey        *connect.Client[v1.SetProviderKeyRequest, v1.SetProviderKeyResponse]
	clearProviderKey      *connect.Client[v1.ClearProviderKeyRequest, v1.ClearProviderKeyResponse]
	startProviderOAuth    *connect.Client[v1.StartProviderOAuthRequest, v1.StartProviderOAuthResponse]
	pollProviderOAuth     *connect.Client[v1.PollProviderOAuthRequest, v1.PollProviderOAuthResponse]
	listAgents            *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	listMemories          *connect.Client[v1.ListMemoriesRequest, v1.ListMemoriesResponse]
	searchMemories        *connect.Client[v1.SearchMemoriesRequest, v1.SearchMemoriesResponse]
	deleteMemory          *connect.Client[v1.DeleteMemoryRequest, v1.DeleteMemoryResponse]
	listPlaybooks         *connect.Client[v1.ListPlaybooksRequest, v1.ListPlaybooksResponse]
	getProfile            *connect.Client[v1.GetProfileRequest, v1.GetProfileResponse]
	updateProfile         *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
	reloadProfileDir      *connect.Client[v1.ReloadProfileDirRequest, v1.ReloadProfileDirResponse]
	listSkills            *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	listMcpServers        *connect.Client[v1.ListMcpServersRequest, v1.ListMcpServersResponse]
	createMcpServer       *connect.Client[v1.CreateMcpServerRequest, v1.CreateMcpServerResponse]
	updateMcpServer       *connect.Client[v1.UpdateMcpServerRequest, v1.UpdateMcpServerResponse]
	deleteMcpServer       *connect.Client[v1.DeleteMcpServerRequest, v1.DeleteMcpServerResponse]
	setMcpServerToken     *connect.Client[v1.SetMcpServerTokenRequest, v1.SetMcpServerTokenResponse]
	clearMcpServerToken   *connect.Client[v1.ClearMcpServerTokenRequest, v1.ClearMcpServerTokenResponse]
	startMcpOAuth         *connect.Client[v1.StartMcpOAuthRequest, v1.StartMcpOAuthResponse]
	completeMcpOAuth      *connect.Client[v1.CompleteMcpOAuthRequest, v1.CompleteMcpOAuthResponse]
	createChat            *connect.Client[v1.CreateChatRequest, v1.CreateChatResponse]
	listChats             *connect.Client[v1.ListChatsRequest, v1.ListChatsResponse]
	renameChat            *connect.Client[v1.RenameChatRequest, v1.RenameChatResponse]
	deleteChat            *connect.Client[v1.DeleteChatRequest, v1.DeleteChatResponse]
	sendChatMessage       *connect.Client[v1.SendChatMessageRequest, v1.SendChatMessageResponse]
	streamChat            *connect.Client[v1.StreamChatRequest, v1.ChatFrame]
	attachChatPullRequest *connect.Client[v1.AttachChatPullRequestRequest, v1.AttachChatPullRequestResponse]
	detachChatPullRequest *connect.Client[v1.DetachChatPullRequestRequest, v1.DetachChatPullRequestResponse]
}

// ListSessions calls podium.agent.v1.AgentService.ListSessions.
func (c *agentServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls podium.agent.v1.AgentService.GetSession.
func (c *agentServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListTurns calls podium.agent.v1.AgentService.ListTurns.
func (c *agentServiceClient) ListTurns(ctx context.Context, req *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return c.listTurns.CallUnary(ctx, req)
}

// GetUsage calls podium.agent.v1.AgentService.GetUsage.
func (c *agentServiceClient) GetUsage(ctx context.Context, req *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return c.getUsage.CallUnary(ctx, req)
}

// GetSettings calls podium.agent.v1.AgentService.GetSettings.
func (c *agentServiceClient) GetSettings(ctx context.Context, req *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return c.getSettings.CallUnary(ctx, req)
}

// SetProviderKey calls podium.agent.v1.AgentService.SetProviderKey.
func (c *agentServiceClient) SetProviderKey(ctx context.Context, req *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error) {
	return c.setProviderKey.CallUnary(ctx, req)
}

// ClearProviderKey calls podium.agent.v1.AgentService.ClearProviderKey.
func (c *agentServiceClient) ClearProviderKey(ctx context.Context, req *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error) {
	return c.clearProviderKey.CallUnary(ctx, req)
}

// StartProviderOAuth calls podium.agent.v1.AgentService.StartProviderOAuth.
func (c *agentServiceClient) StartProviderOAuth(ctx context.Context, req *connect.Request[v1.StartProviderOAuthRequest]) (*connect.Response[v1.StartProviderOAuthResponse], error) {
	return c.startProviderOAuth.CallUnary(ctx, req)
}

// PollProviderOAuth calls podium.agent.v1.AgentService.PollProviderOAuth.
func (c *agentServiceClient) PollProviderOAuth(ctx context.Context, req *connect.Request[v1.PollProviderOAuthRequest]) (*connect.Response[v1.PollProviderOAuthResponse], error) {
	return c.pollProviderOAuth.CallUnary(ctx, req)
}

// ListAgents calls podium.agent.v1.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// ListMemories calls podium.agent.v1.AgentService.ListMemories.
func (c *agentServiceClient) ListMemories(ctx context.Context, req *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error) {
	return c.listMemories.CallUnary(ctx, req)
}

// SearchMemories calls podium.agent.v1.AgentService.SearchMemories.
func (c *agentServiceClient) SearchMemories(ctx context.Context, req *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error) {
	return c.searchMemories.CallUnary(ctx, req)
}

// DeleteMemory calls podium.agent.v1.AgentService.DeleteMemory.
func (c *agentServiceClient) DeleteMemory(ctx context.Context, req *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error) {
	return c.deleteMemory.CallUnary(ctx, req)
}

// ListPlaybooks calls podium.agent.v1.AgentService.ListPlaybooks.
func (c *agentServiceClient) ListPlaybooks(ctx context.Context, req *connect.Request[v1.ListPlaybooksRequest]) (*connect.Response[v1.ListPlaybooksResponse], error) {
	return c.listPlaybooks.CallUnary(ctx, req)
}

// GetProfile calls podium.agent.v1.AgentService.GetProfile.
func (c *agentServiceClient) GetProfile(ctx context.Context, req *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// UpdateProfile calls podium.agent.v1.AgentService.UpdateProfile.
func (c *agentServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// ReloadProfileDir calls podium.agent.v1.AgentService.ReloadProfileDir.
func (c *agentServiceClient) ReloadProfileDir(ctx context.Context, req *connect.Request[v1.ReloadProfileDirRequest]) (*connect.Response[v1.ReloadProfileDirResponse], error) {
	return c.reloadProfileDir.CallUnary(ctx, req)
}

// ListSkills calls podium.agent.v1.AgentService.ListSkills.
func (c *agentServiceClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// ListMcpServers calls podium.agent.v1.AgentService.ListMcpServers.
func (c *agentServiceClient) ListMcpServers(ctx context.Context, req *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error) {
	return c.listMcpServers.CallUnary(ctx, req)
}

// CreateMcpServer calls podium.agent.v1.AgentService.CreateMcpServer.
func (c *agentServiceClient) CreateMcpServer(ctx context.Context, req *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error) {
	return c.createMcpServer.CallUnary(ctx, req)
}

// UpdateMcpServer calls podium.agent.v1.AgentService.UpdateMcpServer.
func (c *agentServiceClient) UpdateMcpServer(ctx context.Context, req *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error) {
	return c.updateMcpServer.CallUnary(ctx, req)
}

// DeleteMcpServer calls podium.agent.v1.AgentService.DeleteMcpServer.
func (c *agentServiceClient) DeleteMcpServer(ctx context.Context, req *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error) {
	return c.deleteMcpServer.CallUnary(ctx, req)
}

// SetMcpServerToken calls podium.agent.v1.AgentService.SetMcpServerToken.
func (c *agentServiceClient) SetMcpServerToken(ctx context.Context, req *connect.Request[v1.SetMcpServerTokenRequest]) (*connect.Response[v1.SetMcpServerTokenResponse], error) {
	return c.setMcpServerToken.CallUnary(ctx, req)
}

// ClearMcpServerToken calls podium.agent.v1.AgentService.ClearMcpServerToken.
func (c *agentServiceClient) ClearMcpServerToken(ctx context.Context, req *connect.Request[v1.ClearMcpServerTokenRequest]) (*connect.Response[v1.ClearMcpServerTokenResponse], error) {
	return c.clearMcpServerToken.CallUnary(ctx, req)
}

// StartMcpOAuth calls podium.agent.v1.AgentService.StartMcpOAuth.
func (c *agentServiceClient) StartMcpOAuth(ctx context.Context, req *connect.Request[v1.StartMcpOAuthRequest]) (*connect.Response[v1.StartMcpOAuthResponse], error) {
	return c.startMcpOAuth.CallUnary(ctx, req)
}

// CompleteMcpOAuth calls podium.agent.v1.AgentService.CompleteMcpOAuth.
func (c *agentServiceClient) CompleteMcpOAuth(ctx context.Context, req *connect.Request[v1.CompleteMcpOAuthRequest]) (*connect.Response[v1.CompleteMcpOAuthResponse], error) {
	return c.completeMcpOAuth.CallUnary(ctx, req)
}

// CreateChat calls podium.agent.v1.AgentService.CreateChat.
func (c *agentServiceClient) CreateChat(ctx context.Context, req *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error) {
	return c.createChat.CallUnary(ctx, req)
}

// ListChats calls podium.agent.v1.AgentService.ListChats.
func (c *agentServiceClient) ListChats(ctx context.Context, req *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error) {
	return c.listChats.CallUnary(ctx, req)
}

// RenameChat calls podium.agent.v1.AgentService.RenameChat.
func (c *agentServiceClient) RenameChat(ctx context.Context, req *connect.Request[v1.RenameChatRequest]) (*connect.Response[v1.RenameChatResponse], error) {
	return c.renameChat.CallUnary(ctx, req)
}

// DeleteChat calls podium.agent.v1.AgentService.DeleteChat.
func (c *agentServiceClient) DeleteChat(ctx context.Context, req *connect.Request[v1.DeleteChatRequest]) (*connect.Response[v1.DeleteChatResponse], error) {
	return c.deleteChat.CallUnary(ctx, req)
}

// SendChatMessage calls podium.agent.v1.AgentService.SendChatMessage.
func (c *agentServiceClient) SendChatMessage(ctx context.Context, req *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error) {
	return c.sendChatMessage.CallUnary(ctx, req)
}

// StreamChat calls podium.agent.v1.AgentService.StreamChat.
func (c *agentServiceClient) StreamChat(ctx context.Context, req *connect.Request[v1.StreamChatRequest]) (*connect.ServerStreamForClient[v1.ChatFrame], error) {
	return c.streamChat.CallServerStream(ctx, req)
}

// AttachChatPullRequest calls podium.agent.v1.AgentService.AttachChatPullRequest.
func (c *agentServiceClient) AttachChatPullRequest(ctx context.Context, req *connect.Request[v1.AttachChatPullRequestRequest]) (*connect.Response[v1.AttachChatPullRequestResponse], error) {
	return c.attachChatPullRequest.CallUnary(ctx, req)
}

// DetachChatPullRequest calls podium.agent.v1.AgentService.DetachChatPullRequest.
func (c *agentServiceClient) DetachChatPullRequest(ctx context.Context, req *connect.Request[v1.DetachChatPullRequestRequest]) (*connect.Response[v1.DetachChatPullRequestResponse], error) {
	return c.detachChatPullRequest.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the podium.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// ListSessions returns conversations the bot has taken part in, newest first.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// ListTurns returns one session's turns, newest first.
	ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error)
	// GetUsage reports what the conductor spent over a range: a total per day for the
	// calendar, and the cost of each individual turn keyed by the task it ran as.
	//
	// It answers only for turns. The tasks themselves live in the control plane's database,
	// which this one deliberately does not reference, so the browser asks both and joins them
	// on task_id — that is why a task with no turn behind it simply has no cost, rather than
	// a cost of zero.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
	// GetSettings reports what the conductor is configured with. It reads no secret value:
	// there is no read endpoint on the secret store, by design.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// SetProviderKey validates a provider key with the provider itself and, only if that
	// succeeds, stores it as a Podium secret. An unvalidated key is never saved.
	SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error)
	// ClearProviderKey removes the secret and the metadata. Calling it twice is not an error.
	ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error)
	// StartProviderOAuth begins a device-authorisation sign-in for a provider that takes a
	// subscription instead of an API key. It stores nothing: it returns the code and the URL
	// a human has to visit, and PollProviderOAuth is what finishes.
	StartProviderOAuth(context.Context, *connect.Request[v1.StartProviderOAuthRequest]) (*connect.Response[v1.StartProviderOAuthResponse], error)
	// PollProviderOAuth asks the provider whether the human has approved the sign-in yet. It
	// is the browser that polls, at the interval the start response asked for. Only the call
	// that comes back authorised stores anything.
	PollProviderOAuth(context.Context, *connect.Request[v1.PollProviderOAuthRequest]) (*connect.Response[v1.PollProviderOAuthResponse], error)
	// ListAgents reports the agent backends this conductor can run a turn on, the models each
	// offers and the effort levels each model accepts. It is the catalogue behind the UI's
	// picker, and it is the same list the write RPCs validate against.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// ListMemories pages through the shared memory, newest first.
	ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error)
	// SearchMemories is a semantic search of the same memory.
	SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error)
	// DeleteMemory takes one memory out of every future recall. It is a tombstone rather
	// than a row deletion: the memory engine keeps the record for audit and stops serving it.
	DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error)
	// ListPlaybooks reports the profile's playbooks so the chat can offer them. Nothing secret:
	// a name, an image and which one the chat starts with.
	ListPlaybooks(context.Context, *connect.Request[v1.ListPlaybooksRequest]) (*connect.Response[v1.ListPlaybooksResponse], error)
	// GetProfile reports the profile a turn actually runs from — profile.yaml and
	// playbooks/*.yaml, with the Assistant-screen overrides on top — and every playbook in
	// full, so a browser can read them. Playbooks are files; this RPC does not write one.
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	// UpdateProfile overrides profile.yaml's display name, model and default playbooks. An
	// empty field clears the override and returns that field to the file's value.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// ReloadProfileDir re-reads the conductor's profile directory — profile.yaml, every
	// playbooks/*.yaml and every prompt file they name — and swaps what it finds into the
	// running profile.
	//
	// It is what an operator who has just edited that YAML does instead of restarting the
	// process. Only an operator asks: a directory halfway through being saved does not load,
	// and a load failure is refused here and changes nothing, so a conductor is never left
	// running half a profile.
	ReloadProfileDir(context.Context, *connect.Request[v1.ReloadProfileDirRequest]) (*connect.Response[v1.ReloadProfileDirResponse], error)
	// ListSkills reports every Agent Skill under PODIUM_AGENT_SKILLS_DIR on this host. Skills
	// are directories with a SKILL.md; this RPC does not write one.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// ListMcpServers reports every MCP server registered on this conductor, with which
	// playbooks name each one. It never carries a token: a server's credential is a Podium
	// secret and the last four characters kept at save time are all any client ever sees.
	ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error)
	// CreateMcpServer registers a new one. The URL is validated as an absolute http(s) URL and
	// nothing else about it is assumed: whether the server answers is found out by a turn.
	CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error)
	// UpdateMcpServer replaces a registered server's definition, leaving its token alone.
	UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error)
	// DeleteMcpServer removes one and its stored token. A playbook that still names it fails
	// its turns saying so, which is why ListMcpServers reports who names what.
	DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error)
	// SetMcpServerToken stores the credential this server authenticates with, as a Podium
	// secret. It is never read back and never written into a turn's config file — the config
	// names the environment variable the conductor delivers it in.
	SetMcpServerToken(context.Context, *connect.Request[v1.SetMcpServerTokenRequest]) (*connect.Response[v1.SetMcpServerTokenResponse], error)
	// ClearMcpServerToken removes it. The server stays registered and reaches its turns with
	// no authorization header at all, which is what an unauthenticated server wants.
	ClearMcpServerToken(context.Context, *connect.Request[v1.ClearMcpServerTokenRequest]) (*connect.Response[v1.ClearMcpServerTokenResponse], error)
	// StartMcpOAuth begins an OAuth sign-in against an MCP server that wants one, and answers
	// with the URL to send the operator's browser to. Everything about the server's OAuth is
	// DISCOVERED — the protected-resource metadata names its authorization server, and that
	// server's own metadata names its endpoints — and the client is registered dynamically, so
	// no part of it is configuration an operator has to supply.
	//
	// The PKCE verifier stays on the conductor. A browser is handed a flow id and a URL, which
	// name a sign-in rather than bearing one.
	StartMcpOAuth(context.Context, *connect.Request[v1.StartMcpOAuthRequest]) (*connect.Response[v1.StartMcpOAuthResponse], error)
	// CompleteMcpOAuth trades the authorization code the browser came back with for a token,
	// and stores it exactly as a pasted one is stored. The code arrives over this API rather
	// than on a redirect the server would have to serve unauthenticated — see
	// docs/agent.md#signing-in-to-an-mcp-server.
	CompleteMcpOAuth(context.Context, *connect.Request[v1.CompleteMcpOAuthRequest]) (*connect.Response[v1.CompleteMcpOAuthResponse], error)
	// CreateChat opens a new web-chat conversation owned by the calling login.
	CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error)
	// ListChats returns the caller's own chats, newest first. Another login's chats are
	// never returned.
	ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error)
	// RenameChat changes the title of one of the caller's chats. Another login's chat is
	// not_found, the same as every other chat RPC. An empty title is refused.
	RenameChat(context.Context, *connect.Request[v1.RenameChatRequest]) (*connect.Response[v1.RenameChatResponse], error)
	// DeleteChat removes one of the caller's chats and every message in it. Another
	// login's chat is not_found, the same as a chat that is not there: the existence of
	// somebody else's conversation is not this caller's to learn. Sessions and turns the
	// chat started are kept — they are the audit, not the transcript.
	DeleteChat(context.Context, *connect.Request[v1.DeleteChatRequest]) (*connect.Response[v1.DeleteChatResponse], error)
	// SendChatMessage stores one human message and starts a turn on it. It is refused with
	// FailedPrecondition while a turn for that chat is already running, unless that turn is
	// awaiting a human reply (an interactive playbook asked a question): then the text is
	// injected into the running task and no second turn starts.
	SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error)
	// StreamChat replays a chat from from_seq and then follows it live. It never ends on its
	// own; the client cancels. Progress frames are ephemeral and are not replayed.
	StreamChat(context.Context, *connect.Request[v1.StreamChatRequest], *connect.ServerStream[v1.ChatFrame]) error
	// AttachChatPullRequest links a pull request to one of the caller's chats by hand, for
	// the one a turn never named or a related one a human wants on the conversation. A URL
	// that is not a GitHub pull request is invalid_argument; the same URL twice is one link.
	AttachChatPullRequest(context.Context, *connect.Request[v1.AttachChatPullRequestRequest]) (*connect.Response[v1.AttachChatPullRequestResponse], error)
	// DetachChatPullRequest takes one link off. A link a turn found stays off: the next turn
	// in the same chat will not put it back, because a human removing something means it.
	// Attaching it again is how it comes back.
	DetachChatPullRequest(context.Context, *connect.Request[v1.DetachChatPullRequestRequest]) (*connect.Response[v1.DetachChatPullRequestResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_podium_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceListSessionsHandler := connect.NewUnaryHandler(
		AgentServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(agentServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSessionHandler := connect.NewUnaryHandler(
		AgentServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(agentServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListTurnsHandler := connect.NewUnaryHandler(
		AgentServiceListTurnsProcedure,
		svc.ListTurns,
		connect.WithSchema(agentServiceMethods.ByName("ListTurns")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetUsageHandler := connect.NewUnaryHandler(
		AgentServiceGetUsageProcedure,
		svc.GetUsage,
		connect.WithSchema(agentServiceMethods.ByName("GetUsage")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSettingsHandler := connect.NewUnaryHandler(
		AgentServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(agentServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetProviderKeyHandler := connect.NewUnaryHandler(
		AgentServiceSetProviderKeyProcedure,
		svc.SetProviderKey,
		connect.WithSchema(agentServiceMethods.ByName("SetProviderKey")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceClearProviderKeyHandler := connect.NewUnaryHandler(
		AgentServiceClearProviderKeyProcedure,
		svc.ClearProviderKey,
		connect.WithSchema(agentServiceMethods.ByName("ClearProviderKey")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStartProviderOAuthHandler := connect.NewUnaryHandler(
		AgentServiceStartProviderOAuthProcedure,
		svc.StartProviderOAuth,
		connect.WithSchema(agentServiceMethods.ByName("StartProviderOAuth")),
		connect.WithHandlerOptions(opts...),
	)
	agentServicePollProviderOAuthHandler := connect.NewUnaryHandler(
		AgentServicePollProviderOAuthProcedure,
		svc.PollProviderOAuth,
		connect.WithSchema(agentServiceMethods.ByName("PollProviderOAuth")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListMemoriesHandler := connect.NewUnaryHandler(
		AgentServiceListMemoriesProcedure,
		svc.ListMemories,
		connect.WithSchema(agentServiceMethods.ByName("ListMemories")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSearchMemoriesHandler := connect.NewUnaryHandler(
		AgentServiceSearchMemoriesProcedure,
		svc.SearchMemories,
		connect.WithSchema(agentServiceMethods.ByName("SearchMemories")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteMemoryHandler := connect.NewUnaryHandler(
		AgentServiceDeleteMemoryProcedure,
		svc.DeleteMemory,
		connect.WithSchema(agentServiceMethods.ByName("DeleteMemory")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListPlaybooksHandler := connect.NewUnaryHandler(
		AgentServiceListPlaybooksProcedure,
		svc.ListPlaybooks,
		connect.WithSchema(agentServiceMethods.ByName("ListPlaybooks")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetProfileHandler := connect.NewUnaryHandler(
		AgentServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(agentServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateProfileHandler := connect.NewUnaryHandler(
		AgentServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(agentServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceReloadProfileDirHandler := connect.NewUnaryHandler(
		AgentServiceReloadProfileDirProcedure,
		svc.ReloadProfileDir,
		connect.WithSchema(agentServiceMethods.ByName("ReloadProfileDir")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListSkillsHandler := connect.NewUnaryHandler(
		AgentServiceListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(agentServiceMethods.ByName("ListSkills")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListMcpServersHandler := connect.NewUnaryHandler(
		AgentServiceListMcpServersProcedure,
		svc.ListMcpServers,
		connect.WithSchema(agentServiceMethods.ByName("ListMcpServers")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCreateMcpServerHandler := connect.NewUnaryHandler(
		AgentServiceCreateMcpServerProcedure,
		svc.CreateMcpServer,
		connect.WithSchema(agentServiceMethods.ByName("CreateMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateMcpServerHandler := connect.NewUnaryHandler(
		AgentServiceUpdateMcpServerProcedure,
		svc.UpdateMcpServer,
		connect.WithSchema(agentServiceMethods.ByName("UpdateMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteMcpServerHandler := connect.NewUnaryHandler(
		AgentServiceDeleteMcpServerProcedure,
		svc.DeleteMcpServer,
		connect.WithSchema(agentServiceMethods.ByName("DeleteMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetMcpServerTokenHandler := connect.NewUnaryHandler(
		AgentServiceSetMcpServerTokenProcedure,
		svc.SetMcpServerToken,
		connect.WithSchema(agentServiceMethods.ByName("SetMcpServerToken")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceClearMcpServerTokenHandler := connect.NewUnaryHandler(
		AgentServiceClearMcpServerTokenProcedure,
		svc.ClearMcpServerToken,
		connect.WithSchema(agentServiceMethods.ByName("ClearMcpServerToken")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStartMcpOAuthHandler := connect.NewUnaryHandler(
		AgentServiceStartMcpOAuthProcedure,
		svc.StartMcpOAuth,
		connect.WithSchema(agentServiceMethods.ByName("StartMcpOAuth")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCompleteMcpOAuthHandler := connect.NewUnaryHandler(
		AgentServiceCompleteMcpOAuthProcedure,
		svc.CompleteMcpOAuth,
		connect.WithSchema(agentServiceMethods.ByName("CompleteMcpOAuth")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCreateChatHandler := connect.NewUnaryHandler(
		AgentServiceCreateChatProcedure,
		svc.CreateChat,
		connect.WithSchema(agentServiceMethods.ByName("CreateChat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListChatsHandler := connect.NewUnaryHandler(
		AgentServiceListChatsProcedure,
		svc.ListChats,
		connect.WithSchema(agentServiceMethods.ByName("ListChats")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRenameChatHandler := connect.NewUnaryHandler(
		AgentServiceRenameChatProcedure,
		svc.RenameChat,
		connect.WithSchema(agentServiceMethods.ByName("RenameChat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteChatHandler := connect.NewUnaryHandler(
		AgentServiceDeleteChatProcedure,
		svc.DeleteChat,
		connect.WithSchema(agentServiceMethods.ByName("DeleteChat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSendChatMessageHandler := connect.NewUnaryHandler(
		AgentServiceSendChatMessageProcedure,
		svc.SendChatMessage,
		connect.WithSchema(agentServiceMethods.ByName("SendChatMessage")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamChatHandler := connect.NewServerStreamHandler(
		AgentServiceStreamChatProcedure,
		svc.StreamChat,
		connect.WithSchema(agentServiceMethods.ByName("StreamChat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceAttachChatPullRequestHandler := connect.NewUnaryHandler(
		AgentServiceAttachChatPullRequestProcedure,
		svc.AttachChatPullRequest,
		connect.WithSchema(agentServiceMethods.ByName("AttachChatPullRequest")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDetachChatPullRequestHandler := connect.NewUnaryHandler(
		AgentServiceDetachChatPullRequestProcedure,
		svc.DetachChatPullRequest,
		connect.WithSchema(agentServiceMethods.ByName("DetachChatPullRequest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListSessionsProcedure:
			agentServiceListSessionsHandler.ServeHTTP(w, r)
		case AgentServiceGetSessionProcedure:
			agentServiceGetSessionHandler.ServeHTTP(w, r)
		case AgentServiceListTurnsProcedure:
			agentServiceListTurnsHandler.ServeHTTP(w, r)
		case AgentServiceGetUsageProcedure:
			agentServiceGetUsageHandler.ServeHTTP(w, r)
		case AgentServiceGetSettingsProcedure:
			agentServiceGetSettingsHandler.ServeHTTP(w, r)
		case AgentServiceSetProviderKeyProcedure:
			agentServiceSetProviderKeyHandler.ServeHTTP(w, r)
		case AgentServiceClearProviderKeyProcedure:
			agentServiceClearProviderKeyHandler.ServeHTTP(w, r)
		case AgentServiceStartProviderOAuthProcedure:
			agentServiceStartProviderOAuthHandler.ServeHTTP(w, r)
		case AgentServicePollProviderOAuthProcedure:
			agentServicePollProviderOAuthHandler.ServeHTTP(w, r)
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceListMemoriesProcedure:
			agentServiceListMemoriesHandler.ServeHTTP(w, r)
		case AgentServiceSearchMemoriesProcedure:
			agentServiceSearchMemoriesHandler.ServeHTTP(w, r)
		case AgentServiceDeleteMemoryProcedure:
			agentServiceDeleteMemoryHandler.ServeHTTP(w, r)
		case AgentServiceListPlaybooksProcedure:
			agentServiceListPlaybooksHandler.ServeHTTP(w, r)
		case AgentServiceGetProfileProcedure:
			agentServiceGetProfileHandler.ServeHTTP(w, r)
		case AgentServiceUpdateProfileProcedure:
			agentServiceUpdateProfileHandler.ServeHTTP(w, r)
		case AgentServiceReloadProfileDirProcedure:
			agentServiceReloadProfileDirHandler.ServeHTTP(w, r)
		case AgentServiceListSkillsProcedure:
			agentServiceListSkillsHandler.ServeHTTP(w, r)
		case AgentServiceListMcpServersProcedure:
			agentServiceListMcpServersHandler.ServeHTTP(w, r)
		case AgentServiceCreateMcpServerProcedure:
			agentServiceCreateMcpServerHandler.ServeHTTP(w, r)
		case AgentServiceUpdateMcpServerProcedure:
			agentServiceUpdateMcpServerHandler.ServeHTTP(w, r)
		case AgentServiceDeleteMcpServerProcedure:
			agentServiceDeleteMcpServerHandler.ServeHTTP(w, r)
		case AgentServiceSetMcpServerTokenProcedure:
			agentServiceSetMcpServerTokenHandler.ServeHTTP(w, r)
		case AgentServiceClearMcpServerTokenProcedure:
			agentServiceClearMcpServerTokenHandler.ServeHTTP(w, r)
		case AgentServiceStartMcpOAuthProcedure:
			agentServiceStartMcpOAuthHandler.ServeHTTP(w, r)
		case AgentServiceCompleteMcpOAuthProcedure:
			agentServiceCompleteMcpOAuthHandler.ServeHTTP(w, r)
		case AgentServiceCreateChatProcedure:
			agentServiceCreateChatHandler.ServeHTTP(w, r)
		case AgentServiceListChatsProcedure:
			agentServiceListChatsHandler.ServeHTTP(w, r)
		case AgentServiceRenameChatProcedure:
			agentServiceRenameChatHandler.ServeHTTP(w, r)
		case AgentServiceDeleteChatProcedure:
			agentServiceDeleteChatHandler.ServeHTTP(w, r)
		case AgentServiceSendChatMessageProcedure:
			agentServiceSendChatMessageHandler.ServeHTTP(w, r)
		case AgentServiceStreamChatProcedure:
			agentServiceStreamChatHandler.ServeHTTP(w, r)
		case AgentServiceAttachChatPullRequestProcedure:
			agentServiceAttachChatPullRequestHandler.ServeHTTP(w, r)
		case AgentServiceDetachChatPullRequestProcedure:
			agentServiceDetachChatPullRequestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListSessions is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListTurns(context.Context, *connect.Request[v1.ListTurnsRequest]) (*connect.Response[v1.ListTurnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListTurns is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetUsage is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetSettings is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetProviderKey(context.Context, *connect.Request[v1.SetProviderKeyRequest]) (*connect.Response[v1.SetProviderKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SetProviderKey is not implemented"))
}

func (UnimplementedAgentServiceHandler) ClearProviderKey(context.Context, *connect.Request[v1.ClearProviderKeyRequest]) (*connect.Response[v1.ClearProviderKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ClearProviderKey is not implemented"))
}

func (UnimplementedAgentServiceHandler) StartProviderOAuth(context.Context, *connect.Request[v1.StartProviderOAuthRequest]) (*connect.Response[v1.StartProviderOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.StartProviderOAuth is not implemented"))
}

func (UnimplementedAgentServiceHandler) PollProviderOAuth(context.Context, *connect.Request[v1.PollProviderOAuthRequest]) (*connect.Response[v1.PollProviderOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.PollProviderOAuth is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListMemories(context.Context, *connect.Request[v1.ListMemoriesRequest]) (*connect.Response[v1.ListMemoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListMemories is not implemented"))
}

func (UnimplementedAgentServiceHandler) SearchMemories(context.Context, *connect.Request[v1.SearchMemoriesRequest]) (*connect.Response[v1.SearchMemoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SearchMemories is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteMemory(context.Context, *connect.Request[v1.DeleteMemoryRequest]) (*connect.Response[v1.DeleteMemoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DeleteMemory is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListPlaybooks(context.Context, *connect.Request[v1.ListPlaybooksRequest]) (*connect.Response[v1.ListPlaybooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListPlaybooks is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.GetProfile is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.UpdateProfile is not implemented"))
}

func (UnimplementedAgentServiceHandler) ReloadProfileDir(context.Context, *connect.Request[v1.ReloadProfileDirRequest]) (*connect.Response[v1.ReloadProfileDirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ReloadProfileDir is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListSkills is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListMcpServers is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.CreateMcpServer is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.UpdateMcpServer is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DeleteMcpServer is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetMcpServerToken(context.Context, *connect.Request[v1.SetMcpServerTokenRequest]) (*connect.Response[v1.SetMcpServerTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SetMcpServerToken is not implemented"))
}

func (UnimplementedAgentServiceHandler) ClearMcpServerToken(context.Context, *connect.Request[v1.ClearMcpServerTokenRequest]) (*connect.Response[v1.ClearMcpServerTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ClearMcpServerToken is not implemented"))
}

func (UnimplementedAgentServiceHandler) StartMcpOAuth(context.Context, *connect.Request[v1.StartMcpOAuthRequest]) (*connect.Response[v1.StartMcpOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.StartMcpOAuth is not implemented"))
}

func (UnimplementedAgentServiceHandler) CompleteMcpOAuth(context.Context, *connect.Request[v1.CompleteMcpOAuthRequest]) (*connect.Response[v1.CompleteMcpOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.CompleteMcpOAuth is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateChat(context.Context, *connect.Request[v1.CreateChatRequest]) (*connect.Response[v1.CreateChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.CreateChat is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListChats(context.Context, *connect.Request[v1.ListChatsRequest]) (*connect.Response[v1.ListChatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.ListChats is not implemented"))
}

func (UnimplementedAgentServiceHandler) RenameChat(context.Context, *connect.Request[v1.RenameChatRequest]) (*connect.Response[v1.RenameChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.RenameChat is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteChat(context.Context, *connect.Request[v1.DeleteChatRequest]) (*connect.Response[v1.DeleteChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DeleteChat is not implemented"))
}

func (UnimplementedAgentServiceHandler) SendChatMessage(context.Context, *connect.Request[v1.SendChatMessageRequest]) (*connect.Response[v1.SendChatMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.SendChatMessage is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamChat(context.Context, *connect.Request[v1.StreamChatRequest], *connect.ServerStream[v1.ChatFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.StreamChat is not implemented"))
}

func (UnimplementedAgentServiceHandler) AttachChatPullRequest(context.Context, *connect.Request[v1.AttachChatPullRequestRequest]) (*connect.Response[v1.AttachChatPullRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.AttachChatPullRequest is not implemented"))
}

func (UnimplementedAgentServiceHandler) DetachChatPullRequest(context.Context, *connect.Request[v1.DetachChatPullRequestRequest]) (*connect.Response[v1.DetachChatPullRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.AgentService.DetachChatPullRequest is not implemented"))
}
