// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/agent/v1/turn.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/podium-ade/podium/internal/proto/podium/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TurnServiceName is the fully-qualified name of the TurnService service.
	TurnServiceName = "podium.agent.v1.TurnService"
	// GitCredentialServiceName is the fully-qualified name of the GitCredentialService service.
	GitCredentialServiceName = "podium.agent.v1.GitCredentialService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TurnServiceDelegateProcedure is the fully-qualified name of the TurnService's Delegate RPC.
	TurnServiceDelegateProcedure = "/podium.agent.v1.TurnService/Delegate"
	// TurnServiceGetDelegationProcedure is the fully-qualified name of the TurnService's GetDelegation
	// RPC.
	TurnServiceGetDelegationProcedure = "/podium.agent.v1.TurnService/GetDelegation"
	// TurnServiceListDelegationsProcedure is the fully-qualified name of the TurnService's
	// ListDelegations RPC.
	TurnServiceListDelegationsProcedure = "/podium.agent.v1.TurnService/ListDelegations"
	// TurnServiceCancelDelegationProcedure is the fully-qualified name of the TurnService's
	// CancelDelegation RPC.
	TurnServiceCancelDelegationProcedure = "/podium.agent.v1.TurnService/CancelDelegation"
	// TurnServiceInjectDelegationProcedure is the fully-qualified name of the TurnService's
	// InjectDelegation RPC.
	TurnServiceInjectDelegationProcedure = "/podium.agent.v1.TurnService/InjectDelegation"
	// GitCredentialServiceMintTokenProcedure is the fully-qualified name of the GitCredentialService's
	// MintToken RPC.
	GitCredentialServiceMintTokenProcedure = "/podium.agent.v1.GitCredentialService/MintToken"
)

// TurnServiceClient is a client for the podium.agent.v1.TurnService service.
type TurnServiceClient interface {
	// Delegate starts a Podium task for this turn's conversation and returns immediately. A
	// task can run for hours; nothing here waits for one.
	Delegate(context.Context, *connect.Request[v1.DelegateRequest]) (*connect.Response[v1.DelegateResponse], error)
	// GetDelegation reports where a delegated task has got to, and its answer once it has
	// one. This is what a turn polls.
	GetDelegation(context.Context, *connect.Request[v1.GetDelegationRequest]) (*connect.Response[v1.GetDelegationResponse], error)
	// ListDelegations is this conversation's delegated tasks: everything this turn has
	// started, plus any still running from an earlier turn of the same conversation.
	ListDelegations(context.Context, *connect.Request[v1.ListDelegationsRequest]) (*connect.Response[v1.ListDelegationsResponse], error)
	// CancelDelegation stops a delegated task. The same cancel `podium task cancel` performs,
	// so the node sends the same SIGTERM and honours the same grace.
	CancelDelegation(context.Context, *connect.Request[v1.CancelDelegationRequest]) (*connect.Response[v1.CancelDelegationResponse], error)
	// InjectDelegation delivers one human message into a running delegated task of this
	// conversation. The container stays up; the runtime treats the text as a new user
	// message in the same workspace. Use it to correct or add to in-flight work rather
	// than starting a second task.
	InjectDelegation(context.Context, *connect.Request[v1.InjectDelegationRequest]) (*connect.Response[v1.InjectDelegationResponse], error)
}

// NewTurnServiceClient constructs a client for the podium.agent.v1.TurnService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTurnServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TurnServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	turnServiceMethods := v1.File_podium_agent_v1_turn_proto.Services().ByName("TurnService").Methods()
	return &turnServiceClient{
		delegate: connect.NewClient[v1.DelegateRequest, v1.DelegateResponse](
			httpClient,
			baseURL+TurnServiceDelegateProcedure,
			connect.WithSchema(turnServiceMethods.ByName("Delegate")),
			connect.WithClientOptions(opts...),
		),
		getDelegation: connect.NewClient[v1.GetDelegationRequest, v1.GetDelegationResponse](
			httpClient,
			baseURL+TurnServiceGetDelegationProcedure,
			connect.WithSchema(turnServiceMethods.ByName("GetDelegation")),
			connect.WithClientOptions(opts...),
		),
		listDelegations: connect.NewClient[v1.ListDelegationsRequest, v1.ListDelegationsResponse](
			httpClient,
			baseURL+TurnServiceListDelegationsProcedure,
			connect.WithSchema(turnServiceMethods.ByName("ListDelegations")),
			connect.WithClientOptions(opts...),
		),
		cancelDelegation: connect.NewClient[v1.CancelDelegationRequest, v1.CancelDelegationResponse](
			httpClient,
			baseURL+TurnServiceCancelDelegationProcedure,
			connect.WithSchema(turnServiceMethods.ByName("CancelDelegation")),
			connect.WithClientOptions(opts...),
		),
		injectDelegation: connect.NewClient[v1.InjectDelegationRequest, v1.InjectDelegationResponse](
			httpClient,
			baseURL+TurnServiceInjectDelegationProcedure,
			connect.WithSchema(turnServiceMethods.ByName("InjectDelegation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// turnServiceClient implements TurnServiceClient.
type turnServiceClient struct {
	delegate         *connect.Client[v1.DelegateRequest, v1.DelegateResponse]
	getDelegation    *connect.Client[v1.GetDelegationRequest, v1.GetDelegationResponse]
	listDelegations  *connect.Client[v1.ListDelegationsRequest, v1.ListDelegationsResponse]
	cancelDelegation *connect.Client[v1.CancelDelegationRequest, v1.CancelDelegationResponse]
	injectDelegation *connect.Client[v1.InjectDelegationRequest, v1.InjectDelegationResponse]
}

// Delegate calls podium.agent.v1.TurnService.Delegate.
func (c *turnServiceClient) Delegate(ctx context.Context, req *connect.Request[v1.DelegateRequest]) (*connect.Response[v1.DelegateResponse], error) {
	return c.delegate.CallUnary(ctx, req)
}

// GetDelegation calls podium.agent.v1.TurnService.GetDelegation.
func (c *turnServiceClient) GetDelegation(ctx context.Context, req *connect.Request[v1.GetDelegationRequest]) (*connect.Response[v1.GetDelegationResponse], error) {
	return c.getDelegation.CallUnary(ctx, req)
}

// ListDelegations calls podium.agent.v1.TurnService.ListDelegations.
func (c *turnServiceClient) ListDelegations(ctx context.Context, req *connect.Request[v1.ListDelegationsRequest]) (*connect.Response[v1.ListDelegationsResponse], error) {
	return c.listDelegations.CallUnary(ctx, req)
}

// CancelDelegation calls podium.agent.v1.TurnService.CancelDelegation.
func (c *turnServiceClient) CancelDelegation(ctx context.Context, req *connect.Request[v1.CancelDelegationRequest]) (*connect.Response[v1.CancelDelegationResponse], error) {
	return c.cancelDelegation.CallUnary(ctx, req)
}

// InjectDelegation calls podium.agent.v1.TurnService.InjectDelegation.
func (c *turnServiceClient) InjectDelegation(ctx context.Context, req *connect.Request[v1.InjectDelegationRequest]) (*connect.Response[v1.InjectDelegationResponse], error) {
	return c.injectDelegation.CallUnary(ctx, req)
}

// TurnServiceHandler is an implementation of the podium.agent.v1.TurnService service.
type TurnServiceHandler interface {
	// Delegate starts a Podium task for this turn's conversation and returns immediately. A
	// task can run for hours; nothing here waits for one.
	Delegate(context.Context, *connect.Request[v1.DelegateRequest]) (*connect.Response[v1.DelegateResponse], error)
	// GetDelegation reports where a delegated task has got to, and its answer once it has
	// one. This is what a turn polls.
	GetDelegation(context.Context, *connect.Request[v1.GetDelegationRequest]) (*connect.Response[v1.GetDelegationResponse], error)
	// ListDelegations is this conversation's delegated tasks: everything this turn has
	// started, plus any still running from an earlier turn of the same conversation.
	ListDelegations(context.Context, *connect.Request[v1.ListDelegationsRequest]) (*connect.Response[v1.ListDelegationsResponse], error)
	// CancelDelegation stops a delegated task. The same cancel `podium task cancel` performs,
	// so the node sends the same SIGTERM and honours the same grace.
	CancelDelegation(context.Context, *connect.Request[v1.CancelDelegationRequest]) (*connect.Response[v1.CancelDelegationResponse], error)
	// InjectDelegation delivers one human message into a running delegated task of this
	// conversation. The container stays up; the runtime treats the text as a new user
	// message in the same workspace. Use it to correct or add to in-flight work rather
	// than starting a second task.
	InjectDelegation(context.Context, *connect.Request[v1.InjectDelegationRequest]) (*connect.Response[v1.InjectDelegationResponse], error)
}

// NewTurnServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTurnServiceHandler(svc TurnServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	turnServiceMethods := v1.File_podium_agent_v1_turn_proto.Services().ByName("TurnService").Methods()
	turnServiceDelegateHandler := connect.NewUnaryHandler(
		TurnServiceDelegateProcedure,
		svc.Delegate,
		connect.WithSchema(turnServiceMethods.ByName("Delegate")),
		connect.WithHandlerOptions(opts...),
	)
	turnServiceGetDelegationHandler := connect.NewUnaryHandler(
		TurnServiceGetDelegationProcedure,
		svc.GetDelegation,
		connect.WithSchema(turnServiceMethods.ByName("GetDelegation")),
		connect.WithHandlerOptions(opts...),
	)
	turnServiceListDelegationsHandler := connect.NewUnaryHandler(
		TurnServiceListDelegationsProcedure,
		svc.ListDelegations,
		connect.WithSchema(turnServiceMethods.ByName("ListDelegations")),
		connect.WithHandlerOptions(opts...),
	)
	turnServiceCancelDelegationHandler := connect.NewUnaryHandler(
		TurnServiceCancelDelegationProcedure,
		svc.CancelDelegation,
		connect.WithSchema(turnServiceMethods.ByName("CancelDelegation")),
		connect.WithHandlerOptions(opts...),
	)
	turnServiceInjectDelegationHandler := connect.NewUnaryHandler(
		TurnServiceInjectDelegationProcedure,
		svc.InjectDelegation,
		connect.WithSchema(turnServiceMethods.ByName("InjectDelegation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.agent.v1.TurnService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TurnServiceDelegateProcedure:
			turnServiceDelegateHandler.ServeHTTP(w, r)
		case TurnServiceGetDelegationProcedure:
			turnServiceGetDelegationHandler.ServeHTTP(w, r)
		case TurnServiceListDelegationsProcedure:
			turnServiceListDelegationsHandler.ServeHTTP(w, r)
		case TurnServiceCancelDelegationProcedure:
			turnServiceCancelDelegationHandler.ServeHTTP(w, r)
		case TurnServiceInjectDelegationProcedure:
			turnServiceInjectDelegationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTurnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTurnServiceHandler struct{}

func (UnimplementedTurnServiceHandler) Delegate(context.Context, *connect.Request[v1.DelegateRequest]) (*connect.Response[v1.DelegateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.TurnService.Delegate is not implemented"))
}

func (UnimplementedTurnServiceHandler) GetDelegation(context.Context, *connect.Request[v1.GetDelegationRequest]) (*connect.Response[v1.GetDelegationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.TurnService.GetDelegation is not implemented"))
}

func (UnimplementedTurnServiceHandler) ListDelegations(context.Context, *connect.Request[v1.ListDelegationsRequest]) (*connect.Response[v1.ListDelegationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.TurnService.ListDelegations is not implemented"))
}

func (UnimplementedTurnServiceHandler) CancelDelegation(context.Context, *connect.Request[v1.CancelDelegationRequest]) (*connect.Response[v1.CancelDelegationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.TurnService.CancelDelegation is not implemented"))
}

func (UnimplementedTurnServiceHandler) InjectDelegation(context.Context, *connect.Request[v1.InjectDelegationRequest]) (*connect.Response[v1.InjectDelegationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.TurnService.InjectDelegation is not implemented"))
}

// GitCredentialServiceClient is a client for the podium.agent.v1.GitCredentialService service.
type GitCredentialServiceClient interface {
	// MintToken issues a GitHub installation token for the calling turn.
	MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error)
}

// NewGitCredentialServiceClient constructs a client for the podium.agent.v1.GitCredentialService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGitCredentialServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GitCredentialServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gitCredentialServiceMethods := v1.File_podium_agent_v1_turn_proto.Services().ByName("GitCredentialService").Methods()
	return &gitCredentialServiceClient{
		mintToken: connect.NewClient[v1.MintTokenRequest, v1.MintTokenResponse](
			httpClient,
			baseURL+GitCredentialServiceMintTokenProcedure,
			connect.WithSchema(gitCredentialServiceMethods.ByName("MintToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gitCredentialServiceClient implements GitCredentialServiceClient.
type gitCredentialServiceClient struct {
	mintToken *connect.Client[v1.MintTokenRequest, v1.MintTokenResponse]
}

// MintToken calls podium.agent.v1.GitCredentialService.MintToken.
func (c *gitCredentialServiceClient) MintToken(ctx context.Context, req *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error) {
	return c.mintToken.CallUnary(ctx, req)
}

// GitCredentialServiceHandler is an implementation of the podium.agent.v1.GitCredentialService
// service.
type GitCredentialServiceHandler interface {
	// MintToken issues a GitHub installation token for the calling turn.
	MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error)
}

// NewGitCredentialServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGitCredentialServiceHandler(svc GitCredentialServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gitCredentialServiceMethods := v1.File_podium_agent_v1_turn_proto.Services().ByName("GitCredentialService").Methods()
	gitCredentialServiceMintTokenHandler := connect.NewUnaryHandler(
		GitCredentialServiceMintTokenProcedure,
		svc.MintToken,
		connect.WithSchema(gitCredentialServiceMethods.ByName("MintToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.agent.v1.GitCredentialService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GitCredentialServiceMintTokenProcedure:
			gitCredentialServiceMintTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGitCredentialServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGitCredentialServiceHandler struct{}

func (UnimplementedGitCredentialServiceHandler) MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.agent.v1.GitCredentialService.MintToken is not implemented"))
}
