// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: podium/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session is one conversation: a Slack thread, a Linear issue, a web chat. Its identity is
// source_key, which the source computes and the conductor never parses.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// source_kind is "slack", "dev", and later "linear" or "chat".
	SourceKind string `protobuf:"bytes,2,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	SourceKey  string `protobuf:"bytes,3,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Profile    string `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	// skill is fixed when the session is created: one session, one skill.
	Skill         string                 `protobuf:"bytes,5,opt,name=skill,proto3" json:"skill,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastTurnAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_turn_at,json=lastTurnAt,proto3" json:"last_turn_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *Session) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *Session) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Session) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastTurnAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTurnAt
	}
	return nil
}

// Turn is one inbound message turned into one Podium task.
type Turn struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// task_id is empty for the moment between the turn being recorded and the task being
	// created, and stays empty for a turn whose task could not be created at all.
	TaskId string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// trigger_ref is the source's own reference to the message that started this turn.
	TriggerRef string `protobuf:"bytes,4,opt,name=trigger_ref,json=triggerRef,proto3" json:"trigger_ref,omitempty"`
	// status is running, succeeded, failed, lost, cancelled or timeout.
	Status     string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// num_turns and cost_usd come from the runtime's turn.json and are unset until it lands.
	NumTurns *int32   `protobuf:"varint,8,opt,name=num_turns,json=numTurns,proto3,oneof" json:"num_turns,omitempty"`
	CostUsd  *float64 `protobuf:"fixed64,9,opt,name=cost_usd,json=costUsd,proto3,oneof" json:"cost_usd,omitempty"`
	// final_text is what the bot said, as it was relayed. It is content, never instructions.
	FinalText     string `protobuf:"bytes,10,opt,name=final_text,json=finalText,proto3" json:"final_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Turn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Turn) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Turn) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Turn) GetTriggerRef() string {
	if x != nil {
		return x.TriggerRef
	}
	return ""
}

func (x *Turn) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Turn) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Turn) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Turn) GetNumTurns() int32 {
	if x != nil && x.NumTurns != nil {
		return *x.NumTurns
	}
	return 0
}

func (x *Turn) GetCostUsd() float64 {
	if x != nil && x.CostUsd != nil {
		return *x.CostUsd
	}
	return 0
}

func (x *Turn) GetFinalText() string {
	if x != nil {
		return x.FinalText
	}
	return ""
}

// Page is the same cursor shape podium.v1 uses: an opaque cursor and a bounded limit.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Page) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSessionsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sessions []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Empty when there is no further page.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListTurnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsRequest) Reset() {
	*x = ListTurnsRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsRequest) ProtoMessage() {}

func (x *ListTurnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsRequest.ProtoReflect.Descriptor instead.
func (*ListTurnsRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListTurnsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListTurnsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTurnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*Turn                `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsResponse) Reset() {
	*x = ListTurnsResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsResponse) ProtoMessage() {}

func (x *ListTurnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsResponse.ProtoReflect.Descriptor instead.
func (*ListTurnsResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListTurnsResponse) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

// ProviderSettings is everything the UI may know about a stored provider key. key_hint is
// the last four characters, computed once at save time: that is the only form in which any
// part of the key is ever read back.
type ProviderSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider is "anthropic" — the only value this track knows. The field is the BYOK seam.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	KeySet   bool   `protobuf:"varint,2,opt,name=key_set,json=keySet,proto3" json:"key_set,omitempty"`
	// key_hint is the last four characters of the key, or "" when no key is set.
	KeyHint string `protobuf:"bytes,3,opt,name=key_hint,json=keyHint,proto3" json:"key_hint,omitempty"`
	// model is profile.yaml's model. Informational: the UI is not a model picker.
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// set_by is the X-Podium-Login at the time of SetProviderKey, or "unknown".
	SetBy         string                 `protobuf:"bytes,5,opt,name=set_by,json=setBy,proto3" json:"set_by,omitempty"`
	SetAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=set_at,json=setAt,proto3" json:"set_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSettings) Reset() {
	*x = ProviderSettings{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSettings) ProtoMessage() {}

func (x *ProviderSettings) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSettings.ProtoReflect.Descriptor instead.
func (*ProviderSettings) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderSettings) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderSettings) GetKeySet() bool {
	if x != nil {
		return x.KeySet
	}
	return false
}

func (x *ProviderSettings) GetKeyHint() string {
	if x != nil {
		return x.KeyHint
	}
	return ""
}

func (x *ProviderSettings) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderSettings) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *ProviderSettings) GetSetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SetAt
	}
	return nil
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderSettings      `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GetSettingsResponse) GetProvider() *ProviderSettings {
	if x != nil {
		return x.Provider
	}
	return nil
}

type SetProviderKeyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// SENSITIVE: never log this field. The handler wraps the request in a redacting
	// slog.LogValuer so no log site has to remember.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderKeyRequest) Reset() {
	*x = SetProviderKeyRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderKeyRequest) ProtoMessage() {}

func (x *SetProviderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderKeyRequest.ProtoReflect.Descriptor instead.
func (*SetProviderKeyRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SetProviderKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SetProviderKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetProviderKeyResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider *ProviderSettings      `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// models is the ids the provider says this key can see, capped at 20. It exists so the UI
	// can show proof that the key works.
	Models []string `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	// status is a human sentence about the save, or "" when there is nothing to add.
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderKeyResponse) Reset() {
	*x = SetProviderKeyResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderKeyResponse) ProtoMessage() {}

func (x *SetProviderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderKeyResponse.ProtoReflect.Descriptor instead.
func (*SetProviderKeyResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SetProviderKeyResponse) GetProvider() *ProviderSettings {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *SetProviderKeyResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *SetProviderKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClearProviderKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearProviderKeyRequest) Reset() {
	*x = ClearProviderKeyRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearProviderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearProviderKeyRequest) ProtoMessage() {}

func (x *ClearProviderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearProviderKeyRequest.ProtoReflect.Descriptor instead.
func (*ClearProviderKeyRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ClearProviderKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ClearProviderKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearProviderKeyResponse) Reset() {
	*x = ClearProviderKeyResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearProviderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearProviderKeyResponse) ProtoMessage() {}

func (x *ClearProviderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearProviderKeyResponse.ProtoReflect.Descriptor instead.
func (*ClearProviderKeyResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

// Memory is one thing the organisation remembers, shared by every agent turn.
//
// EVERY FIELD IS CONTENT. A memory was written by a task, out of material a human, a
// repository or a ticket supplied; nothing in Podium interprets it. The provenance fields
// exist so a person can tell where a memory came from and forget one that should not be
// there — which is the only defence there is against a turn planting a false memory.
type Memory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text  string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// fact_type is world, experience or observation. An observation is derived by the memory
	// engine from the facts under it.
	FactType string `protobuf:"bytes,3,opt,name=fact_type,json=factType,proto3" json:"fact_type,omitempty"`
	// tags are recorded by the conductor (source:<kind>, skill:<name>) and never filtered on.
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// metadata is the provenance the conductor set: session_id, turn_id, task_id, source_ref
	// and source_url.
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// created_at is when the memory was learned.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// entities are the people, systems and concepts the memory engine linked this to.
	Entities []string `protobuf:"bytes,7,rep,name=entities,proto3" json:"entities,omitempty"`
	// context is the retaining caller's note about where the memory came from.
	Context string `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	// document_id is what the retainer grouped the memory under: the turn id, for anything
	// the conductor retained.
	DocumentId    string `protobuf:"bytes,9,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memory) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Memory) GetFactType() string {
	if x != nil {
		return x.FactType
	}
	return ""
}

func (x *Memory) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Memory) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Memory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Memory) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Memory) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Memory) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListMemoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cursor is opaque and comes from a previous response.
	Cursor        string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesRequest) Reset() {
	*x = ListMemoriesRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesRequest) ProtoMessage() {}

func (x *ListMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ListMemoriesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMemoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*Memory              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Empty when there is no further page.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesResponse) Reset() {
	*x = ListMemoriesResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesResponse) ProtoMessage() {}

func (x *ListMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ListMemoriesResponse) GetItems() []*Memory {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMemoriesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type SearchMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesRequest) Reset() {
	*x = SearchMemoriesRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesRequest) ProtoMessage() {}

func (x *SearchMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *SearchMemoriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Memory              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesResponse) Reset() {
	*x = SearchMemoriesResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesResponse) ProtoMessage() {}

func (x *SearchMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SearchMemoriesResponse) GetItems() []*Memory {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteMemoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_podium_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

var File_podium_agent_v1_agent_proto protoreflect.FileDescriptor

const file_podium_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bpodium/agent/v1/agent.proto\x12\x0fpodium.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsource_kind\x18\x02 \x01(\tR\n" +
	"sourceKind\x12\x1d\n" +
	"\n" +
	"source_key\x18\x03 \x01(\tR\tsourceKey\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x14\n" +
	"\x05skill\x18\x05 \x01(\tR\x05skill\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_turn_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastTurnAt\"\xfb\x02\n" +
	"\x04Turn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vtrigger_ref\x18\x04 \x01(\tR\n" +
	"triggerRef\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12 \n" +
	"\tnum_turns\x18\b \x01(\x05H\x00R\bnumTurns\x88\x01\x01\x12\x1e\n" +
	"\bcost_usd\x18\t \x01(\x01H\x01R\acostUsd\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"final_text\x18\n" +
	" \x01(\tR\tfinalTextB\f\n" +
	"\n" +
	"_num_turnsB\v\n" +
	"\t_cost_usd\"4\n" +
	"\x04Page\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"@\n" +
	"\x13ListSessionsRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.podium.agent.v1.PageR\x04page\"m\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.podium.agent.v1.SessionR\bsessions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"H\n" +
	"\x12GetSessionResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.podium.agent.v1.SessionR\asession\"G\n" +
	"\x10ListTurnsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x11ListTurnsResponse\x12+\n" +
	"\x05turns\x18\x01 \x03(\v2\x15.podium.agent.v1.TurnR\x05turns\"\x14\n" +
	"\x12GetSettingsRequest\"\xc2\x01\n" +
	"\x10ProviderSettings\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x17\n" +
	"\akey_set\x18\x02 \x01(\bR\x06keySet\x12\x19\n" +
	"\bkey_hint\x18\x03 \x01(\tR\akeyHint\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x15\n" +
	"\x06set_by\x18\x05 \x01(\tR\x05setBy\x121\n" +
	"\x06set_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05setAt\"T\n" +
	"\x13GetSettingsResponse\x12=\n" +
	"\bprovider\x18\x01 \x01(\v2!.podium.agent.v1.ProviderSettingsR\bprovider\"E\n" +
	"\x15SetProviderKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x87\x01\n" +
	"\x16SetProviderKeyResponse\x12=\n" +
	"\bprovider\x18\x01 \x01(\v2!.podium.agent.v1.ProviderSettingsR\bprovider\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"5\n" +
	"\x17ClearProviderKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\x1a\n" +
	"\x18ClearProviderKeyResponse\"\xef\x02\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\tfact_type\x18\x03 \x01(\tR\bfactType\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.podium.agent.v1.Memory.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bentities\x18\a \x03(\tR\bentities\x12\x18\n" +
	"\acontext\x18\b \x01(\tR\acontext\x12\x1f\n" +
	"\vdocument_id\x18\t \x01(\tR\n" +
	"documentId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x13ListMemoriesRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"f\n" +
	"\x14ListMemoriesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.podium.agent.v1.MemoryR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"C\n" +
	"\x15SearchMemoriesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"G\n" +
	"\x16SearchMemoriesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.podium.agent.v1.MemoryR\x05items\"%\n" +
	"\x13DeleteMemoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteMemoryResponse2\xd9\x06\n" +
	"\fAgentService\x12[\n" +
	"\fListSessions\x12$.podium.agent.v1.ListSessionsRequest\x1a%.podium.agent.v1.ListSessionsResponse\x12U\n" +
	"\n" +
	"GetSession\x12\".podium.agent.v1.GetSessionRequest\x1a#.podium.agent.v1.GetSessionResponse\x12R\n" +
	"\tListTurns\x12!.podium.agent.v1.ListTurnsRequest\x1a\".podium.agent.v1.ListTurnsResponse\x12X\n" +
	"\vGetSettings\x12#.podium.agent.v1.GetSettingsRequest\x1a$.podium.agent.v1.GetSettingsResponse\x12a\n" +
	"\x0eSetProviderKey\x12&.podium.agent.v1.SetProviderKeyRequest\x1a'.podium.agent.v1.SetProviderKeyResponse\x12g\n" +
	"\x10ClearProviderKey\x12(.podium.agent.v1.ClearProviderKeyRequest\x1a).podium.agent.v1.ClearProviderKeyResponse\x12[\n" +
	"\fListMemories\x12$.podium.agent.v1.ListMemoriesRequest\x1a%.podium.agent.v1.ListMemoriesResponse\x12a\n" +
	"\x0eSearchMemories\x12&.podium.agent.v1.SearchMemoriesRequest\x1a'.podium.agent.v1.SearchMemoriesResponse\x12[\n" +
	"\fDeleteMemory\x12$.podium.agent.v1.DeleteMemoryRequest\x1a%.podium.agent.v1.DeleteMemoryResponseB\xc8\x01\n" +
	"\x13com.podium.agent.v1B\n" +
	"AgentProtoP\x01ZGgithub.com/alvaroibarguen/podium/internal/proto/podium/agent/v1;agentv1\xa2\x02\x03PAX\xaa\x02\x0fPodium.Agent.V1\xca\x02\x0fPodium\\Agent\\V1\xe2\x02\x1bPodium\\Agent\\V1\\GPBMetadata\xea\x02\x11Podium::Agent::V1b\x06proto3"

var (
	file_podium_agent_v1_agent_proto_rawDescOnce sync.Once
	file_podium_agent_v1_agent_proto_rawDescData []byte
)

func file_podium_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_podium_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_podium_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podium_agent_v1_agent_proto_rawDesc), len(file_podium_agent_v1_agent_proto_rawDesc)))
	})
	return file_podium_agent_v1_agent_proto_rawDescData
}

var file_podium_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_podium_agent_v1_agent_proto_goTypes = []any{
	(*Session)(nil),                  // 0: podium.agent.v1.Session
	(*Turn)(nil),                     // 1: podium.agent.v1.Turn
	(*Page)(nil),                     // 2: podium.agent.v1.Page
	(*ListSessionsRequest)(nil),      // 3: podium.agent.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),     // 4: podium.agent.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),        // 5: podium.agent.v1.GetSessionRequest
	(*GetSessionResponse)(nil),       // 6: podium.agent.v1.GetSessionResponse
	(*ListTurnsRequest)(nil),         // 7: podium.agent.v1.ListTurnsRequest
	(*ListTurnsResponse)(nil),        // 8: podium.agent.v1.ListTurnsResponse
	(*GetSettingsRequest)(nil),       // 9: podium.agent.v1.GetSettingsRequest
	(*ProviderSettings)(nil),         // 10: podium.agent.v1.ProviderSettings
	(*GetSettingsResponse)(nil),      // 11: podium.agent.v1.GetSettingsResponse
	(*SetProviderKeyRequest)(nil),    // 12: podium.agent.v1.SetProviderKeyRequest
	(*SetProviderKeyResponse)(nil),   // 13: podium.agent.v1.SetProviderKeyResponse
	(*ClearProviderKeyRequest)(nil),  // 14: podium.agent.v1.ClearProviderKeyRequest
	(*ClearProviderKeyResponse)(nil), // 15: podium.agent.v1.ClearProviderKeyResponse
	(*Memory)(nil),                   // 16: podium.agent.v1.Memory
	(*ListMemoriesRequest)(nil),      // 17: podium.agent.v1.ListMemoriesRequest
	(*ListMemoriesResponse)(nil),     // 18: podium.agent.v1.ListMemoriesResponse
	(*SearchMemoriesRequest)(nil),    // 19: podium.agent.v1.SearchMemoriesRequest
	(*SearchMemoriesResponse)(nil),   // 20: podium.agent.v1.SearchMemoriesResponse
	(*DeleteMemoryRequest)(nil),      // 21: podium.agent.v1.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),     // 22: podium.agent.v1.DeleteMemoryResponse
	nil,                              // 23: podium.agent.v1.Memory.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 24: google.protobuf.Timestamp
}
var file_podium_agent_v1_agent_proto_depIdxs = []int32{
	24, // 0: podium.agent.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: podium.agent.v1.Session.last_turn_at:type_name -> google.protobuf.Timestamp
	24, // 2: podium.agent.v1.Turn.started_at:type_name -> google.protobuf.Timestamp
	24, // 3: podium.agent.v1.Turn.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 4: podium.agent.v1.ListSessionsRequest.page:type_name -> podium.agent.v1.Page
	0,  // 5: podium.agent.v1.ListSessionsResponse.sessions:type_name -> podium.agent.v1.Session
	0,  // 6: podium.agent.v1.GetSessionResponse.session:type_name -> podium.agent.v1.Session
	1,  // 7: podium.agent.v1.ListTurnsResponse.turns:type_name -> podium.agent.v1.Turn
	24, // 8: podium.agent.v1.ProviderSettings.set_at:type_name -> google.protobuf.Timestamp
	10, // 9: podium.agent.v1.GetSettingsResponse.provider:type_name -> podium.agent.v1.ProviderSettings
	10, // 10: podium.agent.v1.SetProviderKeyResponse.provider:type_name -> podium.agent.v1.ProviderSettings
	23, // 11: podium.agent.v1.Memory.metadata:type_name -> podium.agent.v1.Memory.MetadataEntry
	24, // 12: podium.agent.v1.Memory.created_at:type_name -> google.protobuf.Timestamp
	16, // 13: podium.agent.v1.ListMemoriesResponse.items:type_name -> podium.agent.v1.Memory
	16, // 14: podium.agent.v1.SearchMemoriesResponse.items:type_name -> podium.agent.v1.Memory
	3,  // 15: podium.agent.v1.AgentService.ListSessions:input_type -> podium.agent.v1.ListSessionsRequest
	5,  // 16: podium.agent.v1.AgentService.GetSession:input_type -> podium.agent.v1.GetSessionRequest
	7,  // 17: podium.agent.v1.AgentService.ListTurns:input_type -> podium.agent.v1.ListTurnsRequest
	9,  // 18: podium.agent.v1.AgentService.GetSettings:input_type -> podium.agent.v1.GetSettingsRequest
	12, // 19: podium.agent.v1.AgentService.SetProviderKey:input_type -> podium.agent.v1.SetProviderKeyRequest
	14, // 20: podium.agent.v1.AgentService.ClearProviderKey:input_type -> podium.agent.v1.ClearProviderKeyRequest
	17, // 21: podium.agent.v1.AgentService.ListMemories:input_type -> podium.agent.v1.ListMemoriesRequest
	19, // 22: podium.agent.v1.AgentService.SearchMemories:input_type -> podium.agent.v1.SearchMemoriesRequest
	21, // 23: podium.agent.v1.AgentService.DeleteMemory:input_type -> podium.agent.v1.DeleteMemoryRequest
	4,  // 24: podium.agent.v1.AgentService.ListSessions:output_type -> podium.agent.v1.ListSessionsResponse
	6,  // 25: podium.agent.v1.AgentService.GetSession:output_type -> podium.agent.v1.GetSessionResponse
	8,  // 26: podium.agent.v1.AgentService.ListTurns:output_type -> podium.agent.v1.ListTurnsResponse
	11, // 27: podium.agent.v1.AgentService.GetSettings:output_type -> podium.agent.v1.GetSettingsResponse
	13, // 28: podium.agent.v1.AgentService.SetProviderKey:output_type -> podium.agent.v1.SetProviderKeyResponse
	15, // 29: podium.agent.v1.AgentService.ClearProviderKey:output_type -> podium.agent.v1.ClearProviderKeyResponse
	18, // 30: podium.agent.v1.AgentService.ListMemories:output_type -> podium.agent.v1.ListMemoriesResponse
	20, // 31: podium.agent.v1.AgentService.SearchMemories:output_type -> podium.agent.v1.SearchMemoriesResponse
	22, // 32: podium.agent.v1.AgentService.DeleteMemory:output_type -> podium.agent.v1.DeleteMemoryResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_podium_agent_v1_agent_proto_init() }
func file_podium_agent_v1_agent_proto_init() {
	if File_podium_agent_v1_agent_proto != nil {
		return
	}
	file_podium_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podium_agent_v1_agent_proto_rawDesc), len(file_podium_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podium_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_podium_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_podium_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_podium_agent_v1_agent_proto = out.File
	file_podium_agent_v1_agent_proto_goTypes = nil
	file_podium_agent_v1_agent_proto_depIdxs = nil
}
