// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: podium/agent/v1/turn.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Delegation is one task a turn asked for.
type Delegation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// playbook is the playbook the task runs, which decides its image, its tools, its
	// credentials and the node it can be placed on.
	Playbook string `protobuf:"bytes,2,opt,name=playbook,proto3" json:"playbook,omitempty"`
	// instruction is what the turn asked for, verbatim.
	Instruction string `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// task_id is empty only in the moment between the delegation being recorded and the
	// control plane accepting the task.
	TaskId string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// status is running, succeeded, failed, lost, cancelled or timeout — the turns table's
	// vocabulary, because one classify() maps a terminal task onto both.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// final_text is what the task said as its answer. Empty until it says something, and it
	// stays empty for a task that never did.
	FinalText     string                 `protobuf:"bytes,6,opt,name=final_text,json=finalText,proto3" json:"final_text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delegation) Reset() {
	*x = Delegation{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegation) ProtoMessage() {}

func (x *Delegation) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delegation.ProtoReflect.Descriptor instead.
func (*Delegation) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{0}
}

func (x *Delegation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delegation) GetPlaybook() string {
	if x != nil {
		return x.Playbook
	}
	return ""
}

func (x *Delegation) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Delegation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Delegation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Delegation) GetFinalText() string {
	if x != nil {
		return x.FinalText
	}
	return ""
}

func (x *Delegation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delegation) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type DelegateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// playbook must be one of the playbooks this turn's brief offered. A name that is not on
	// that list is refused rather than resolved, so a turn cannot reach a playbook by
	// guessing at its name.
	Playbook string `protobuf:"bytes,1,opt,name=playbook,proto3" json:"playbook,omitempty"`
	// instruction is the whole brief for the delegated task: it is the only thing the task is
	// told beyond the conversation it belongs to, so a turn that writes two words gets a task
	// that knows two words.
	Instruction   string `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateRequest) Reset() {
	*x = DelegateRequest{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateRequest) ProtoMessage() {}

func (x *DelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateRequest.ProtoReflect.Descriptor instead.
func (*DelegateRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{1}
}

func (x *DelegateRequest) GetPlaybook() string {
	if x != nil {
		return x.Playbook
	}
	return ""
}

func (x *DelegateRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type DelegateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegation    *Delegation            `protobuf:"bytes,1,opt,name=delegation,proto3" json:"delegation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateResponse) Reset() {
	*x = DelegateResponse{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateResponse) ProtoMessage() {}

func (x *DelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateResponse.ProtoReflect.Descriptor instead.
func (*DelegateResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{2}
}

func (x *DelegateResponse) GetDelegation() *Delegation {
	if x != nil {
		return x.Delegation
	}
	return nil
}

type GetDelegationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegationRequest) Reset() {
	*x = GetDelegationRequest{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegationRequest) ProtoMessage() {}

func (x *GetDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegationRequest.ProtoReflect.Descriptor instead.
func (*GetDelegationRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{3}
}

func (x *GetDelegationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDelegationResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Delegation *Delegation            `protobuf:"bytes,1,opt,name=delegation,proto3" json:"delegation,omitempty"`
	// progress is the last thing the task said on its way to an answer, so a turn polling
	// this can see movement rather than only "running". It is untrusted content: a task
	// wrote it.
	Progress      string `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegationResponse) Reset() {
	*x = GetDelegationResponse{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegationResponse) ProtoMessage() {}

func (x *GetDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegationResponse.ProtoReflect.Descriptor instead.
func (*GetDelegationResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{4}
}

func (x *GetDelegationResponse) GetDelegation() *Delegation {
	if x != nil {
		return x.Delegation
	}
	return nil
}

func (x *GetDelegationResponse) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

type ListDelegationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDelegationsRequest) Reset() {
	*x = ListDelegationsRequest{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDelegationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegationsRequest) ProtoMessage() {}

func (x *ListDelegationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegationsRequest.ProtoReflect.Descriptor instead.
func (*ListDelegationsRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{5}
}

type ListDelegationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegations   []*Delegation          `protobuf:"bytes,1,rep,name=delegations,proto3" json:"delegations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDelegationsResponse) Reset() {
	*x = ListDelegationsResponse{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDelegationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegationsResponse) ProtoMessage() {}

func (x *ListDelegationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegationsResponse.ProtoReflect.Descriptor instead.
func (*ListDelegationsResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{6}
}

func (x *ListDelegationsResponse) GetDelegations() []*Delegation {
	if x != nil {
		return x.Delegations
	}
	return nil
}

type CancelDelegationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// reason is recorded on the task and shown to the operator. Optional.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDelegationRequest) Reset() {
	*x = CancelDelegationRequest{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDelegationRequest) ProtoMessage() {}

func (x *CancelDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDelegationRequest.ProtoReflect.Descriptor instead.
func (*CancelDelegationRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{7}
}

func (x *CancelDelegationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelDelegationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelDelegationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegation    *Delegation            `protobuf:"bytes,1,opt,name=delegation,proto3" json:"delegation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDelegationResponse) Reset() {
	*x = CancelDelegationResponse{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDelegationResponse) ProtoMessage() {}

func (x *CancelDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDelegationResponse.ProtoReflect.Descriptor instead.
func (*CancelDelegationResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{8}
}

func (x *CancelDelegationResponse) GetDelegation() *Delegation {
	if x != nil {
		return x.Delegation
	}
	return nil
}

type InjectDelegationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// text is what the person said, handed to the running task as a new user message.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectDelegationRequest) Reset() {
	*x = InjectDelegationRequest{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectDelegationRequest) ProtoMessage() {}

func (x *InjectDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectDelegationRequest.ProtoReflect.Descriptor instead.
func (*InjectDelegationRequest) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{9}
}

func (x *InjectDelegationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InjectDelegationRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type InjectDelegationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegation    *Delegation            `protobuf:"bytes,1,opt,name=delegation,proto3" json:"delegation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectDelegationResponse) Reset() {
	*x = InjectDelegationResponse{}
	mi := &file_podium_agent_v1_turn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectDelegationResponse) ProtoMessage() {}

func (x *InjectDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podium_agent_v1_turn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectDelegationResponse.ProtoReflect.Descriptor instead.
func (*InjectDelegationResponse) Descriptor() ([]byte, []int) {
	return file_podium_agent_v1_turn_proto_rawDescGZIP(), []int{10}
}

func (x *InjectDelegationResponse) GetDelegation() *Delegation {
	if x != nil {
		return x.Delegation
	}
	return nil
}

var File_podium_agent_v1_turn_proto protoreflect.FileDescriptor

const file_podium_agent_v1_turn_proto_rawDesc = "" +
	"\n" +
	"\x1apodium/agent/v1/turn.proto\x12\x0fpodium.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\n" +
	"Delegation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bplaybook\x18\x02 \x01(\tR\bplaybook\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"final_text\x18\x06 \x01(\tR\tfinalText\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"O\n" +
	"\x0fDelegateRequest\x12\x1a\n" +
	"\bplaybook\x18\x01 \x01(\tR\bplaybook\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\"O\n" +
	"\x10DelegateResponse\x12;\n" +
	"\n" +
	"delegation\x18\x01 \x01(\v2\x1b.podium.agent.v1.DelegationR\n" +
	"delegation\"&\n" +
	"\x14GetDelegationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\x15GetDelegationResponse\x12;\n" +
	"\n" +
	"delegation\x18\x01 \x01(\v2\x1b.podium.agent.v1.DelegationR\n" +
	"delegation\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\tR\bprogress\"\x18\n" +
	"\x16ListDelegationsRequest\"X\n" +
	"\x17ListDelegationsResponse\x12=\n" +
	"\vdelegations\x18\x01 \x03(\v2\x1b.podium.agent.v1.DelegationR\vdelegations\"A\n" +
	"\x17CancelDelegationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"W\n" +
	"\x18CancelDelegationResponse\x12;\n" +
	"\n" +
	"delegation\x18\x01 \x01(\v2\x1b.podium.agent.v1.DelegationR\n" +
	"delegation\"=\n" +
	"\x17InjectDelegationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"W\n" +
	"\x18InjectDelegationResponse\x12;\n" +
	"\n" +
	"delegation\x18\x01 \x01(\v2\x1b.podium.agent.v1.DelegationR\n" +
	"delegation2\xf6\x03\n" +
	"\vTurnService\x12O\n" +
	"\bDelegate\x12 .podium.agent.v1.DelegateRequest\x1a!.podium.agent.v1.DelegateResponse\x12^\n" +
	"\rGetDelegation\x12%.podium.agent.v1.GetDelegationRequest\x1a&.podium.agent.v1.GetDelegationResponse\x12d\n" +
	"\x0fListDelegations\x12'.podium.agent.v1.ListDelegationsRequest\x1a(.podium.agent.v1.ListDelegationsResponse\x12g\n" +
	"\x10CancelDelegation\x12(.podium.agent.v1.CancelDelegationRequest\x1a).podium.agent.v1.CancelDelegationResponse\x12g\n" +
	"\x10InjectDelegation\x12(.podium.agent.v1.InjectDelegationRequest\x1a).podium.agent.v1.InjectDelegationResponseB\xc3\x01\n" +
	"\x13com.podium.agent.v1B\tTurnProtoP\x01ZCgithub.com/podium-ade/podium/internal/proto/podium/agent/v1;agentv1\xa2\x02\x03PAX\xaa\x02\x0fPodium.Agent.V1\xca\x02\x0fPodium\\Agent\\V1\xe2\x02\x1bPodium\\Agent\\V1\\GPBMetadata\xea\x02\x11Podium::Agent::V1b\x06proto3"

var (
	file_podium_agent_v1_turn_proto_rawDescOnce sync.Once
	file_podium_agent_v1_turn_proto_rawDescData []byte
)

func file_podium_agent_v1_turn_proto_rawDescGZIP() []byte {
	file_podium_agent_v1_turn_proto_rawDescOnce.Do(func() {
		file_podium_agent_v1_turn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podium_agent_v1_turn_proto_rawDesc), len(file_podium_agent_v1_turn_proto_rawDesc)))
	})
	return file_podium_agent_v1_turn_proto_rawDescData
}

var file_podium_agent_v1_turn_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_podium_agent_v1_turn_proto_goTypes = []any{
	(*Delegation)(nil),               // 0: podium.agent.v1.Delegation
	(*DelegateRequest)(nil),          // 1: podium.agent.v1.DelegateRequest
	(*DelegateResponse)(nil),         // 2: podium.agent.v1.DelegateResponse
	(*GetDelegationRequest)(nil),     // 3: podium.agent.v1.GetDelegationRequest
	(*GetDelegationResponse)(nil),    // 4: podium.agent.v1.GetDelegationResponse
	(*ListDelegationsRequest)(nil),   // 5: podium.agent.v1.ListDelegationsRequest
	(*ListDelegationsResponse)(nil),  // 6: podium.agent.v1.ListDelegationsResponse
	(*CancelDelegationRequest)(nil),  // 7: podium.agent.v1.CancelDelegationRequest
	(*CancelDelegationResponse)(nil), // 8: podium.agent.v1.CancelDelegationResponse
	(*InjectDelegationRequest)(nil),  // 9: podium.agent.v1.InjectDelegationRequest
	(*InjectDelegationResponse)(nil), // 10: podium.agent.v1.InjectDelegationResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_podium_agent_v1_turn_proto_depIdxs = []int32{
	11, // 0: podium.agent.v1.Delegation.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: podium.agent.v1.Delegation.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 2: podium.agent.v1.DelegateResponse.delegation:type_name -> podium.agent.v1.Delegation
	0,  // 3: podium.agent.v1.GetDelegationResponse.delegation:type_name -> podium.agent.v1.Delegation
	0,  // 4: podium.agent.v1.ListDelegationsResponse.delegations:type_name -> podium.agent.v1.Delegation
	0,  // 5: podium.agent.v1.CancelDelegationResponse.delegation:type_name -> podium.agent.v1.Delegation
	0,  // 6: podium.agent.v1.InjectDelegationResponse.delegation:type_name -> podium.agent.v1.Delegation
	1,  // 7: podium.agent.v1.TurnService.Delegate:input_type -> podium.agent.v1.DelegateRequest
	3,  // 8: podium.agent.v1.TurnService.GetDelegation:input_type -> podium.agent.v1.GetDelegationRequest
	5,  // 9: podium.agent.v1.TurnService.ListDelegations:input_type -> podium.agent.v1.ListDelegationsRequest
	7,  // 10: podium.agent.v1.TurnService.CancelDelegation:input_type -> podium.agent.v1.CancelDelegationRequest
	9,  // 11: podium.agent.v1.TurnService.InjectDelegation:input_type -> podium.agent.v1.InjectDelegationRequest
	2,  // 12: podium.agent.v1.TurnService.Delegate:output_type -> podium.agent.v1.DelegateResponse
	4,  // 13: podium.agent.v1.TurnService.GetDelegation:output_type -> podium.agent.v1.GetDelegationResponse
	6,  // 14: podium.agent.v1.TurnService.ListDelegations:output_type -> podium.agent.v1.ListDelegationsResponse
	8,  // 15: podium.agent.v1.TurnService.CancelDelegation:output_type -> podium.agent.v1.CancelDelegationResponse
	10, // 16: podium.agent.v1.TurnService.InjectDelegation:output_type -> podium.agent.v1.InjectDelegationResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_podium_agent_v1_turn_proto_init() }
func file_podium_agent_v1_turn_proto_init() {
	if File_podium_agent_v1_turn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podium_agent_v1_turn_proto_rawDesc), len(file_podium_agent_v1_turn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podium_agent_v1_turn_proto_goTypes,
		DependencyIndexes: file_podium_agent_v1_turn_proto_depIdxs,
		MessageInfos:      file_podium_agent_v1_turn_proto_msgTypes,
	}.Build()
	File_podium_agent_v1_turn_proto = out.File
	file_podium_agent_v1_turn_proto_goTypes = nil
	file_podium_agent_v1_turn_proto_depIdxs = nil
}
