// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegations.sql

package agentdb

import (
	"context"
	"time"
)

const createDelegation = `-- name: CreateDelegation :one
insert into delegations (id, session_id, turn_id, trigger_ref, playbook, instruction, status,
                         created_at, agent, model, effort, provider)
values ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12)
returning id, session_id, turn_id, trigger_ref, playbook, instruction, task_id, status, final_text, created_at, finished_at, num_turns, cost_usd, agent, model, effort, provider
`

type CreateDelegationParams struct {
	ID          string
	SessionID   string
	TurnID      string
	TriggerRef  string
	Playbook    string
	Instruction string
	Status      string
	CreatedAt   time.Time
	Agent       *string
	Model       *string
	Effort      *string
	Provider    *string
}

// CreateDelegation records the backend as the row is written, for the same reason a turn
// does: a playbook's model is a default, and editing the playbook later would otherwise
// relabel every delegation that ever ran under it.
func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, createDelegation,
		arg.ID,
		arg.SessionID,
		arg.TurnID,
		arg.TriggerRef,
		arg.Playbook,
		arg.Instruction,
		arg.Status,
		arg.CreatedAt,
		arg.Agent,
		arg.Model,
		arg.Effort,
		arg.Provider,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.TriggerRef,
		&i.Playbook,
		&i.Instruction,
		&i.TaskID,
		&i.Status,
		&i.FinalText,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.Agent,
		&i.Model,
		&i.Effort,
		&i.Provider,
	)
	return i, err
}

const finishDelegation = `-- name: FinishDelegation :exec
update delegations
set status      = $1,
    finished_at = $2,
    final_text  = $3,
    num_turns   = $4,
    cost_usd    = $5
where id = $6
`

type FinishDelegationParams struct {
	Status     string
	FinishedAt *time.Time
	FinalText  *string
	NumTurns   *int32
	CostUsd    *float64
	ID         string
}

func (q *Queries) FinishDelegation(ctx context.Context, arg FinishDelegationParams) error {
	_, err := q.db.Exec(ctx, finishDelegation,
		arg.Status,
		arg.FinishedAt,
		arg.FinalText,
		arg.NumTurns,
		arg.CostUsd,
		arg.ID,
	)
	return err
}

const getDelegation = `-- name: GetDelegation :one
select id, session_id, turn_id, trigger_ref, playbook, instruction, task_id, status, final_text, created_at, finished_at, num_turns, cost_usd, agent, model, effort, provider from delegations where id = $1
`

func (q *Queries) GetDelegation(ctx context.Context, id string) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegation, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.TriggerRef,
		&i.Playbook,
		&i.Instruction,
		&i.TaskID,
		&i.Status,
		&i.FinalText,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.Agent,
		&i.Model,
		&i.Effort,
		&i.Provider,
	)
	return i, err
}

const listDelegationsForTurn = `-- name: ListDelegationsForTurn :many
select id, session_id, turn_id, trigger_ref, playbook, instruction, task_id, status, final_text, created_at, finished_at, num_turns, cost_usd, agent, model, effort, provider from delegations where turn_id = $1 order by created_at, id
`

func (q *Queries) ListDelegationsForTurn(ctx context.Context, turnID string) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listDelegationsForTurn, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.TriggerRef,
			&i.Playbook,
			&i.Instruction,
			&i.TaskID,
			&i.Status,
			&i.FinalText,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDelegations = `-- name: ListRunningDelegations :many
select id, session_id, turn_id, trigger_ref, playbook, instruction, task_id, status, final_text, created_at, finished_at, num_turns, cost_usd, agent, model, effort, provider from delegations where status = 'running' order by created_at
`

func (q *Queries) ListRunningDelegations(ctx context.Context) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listRunningDelegations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.TriggerRef,
			&i.Playbook,
			&i.Instruction,
			&i.TaskID,
			&i.Status,
			&i.FinalText,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDelegationsForRef = `-- name: ListRunningDelegationsForRef :many
select id, session_id, turn_id, trigger_ref, playbook, instruction, task_id, status, final_text, created_at, finished_at, num_turns, cost_usd, agent, model, effort, provider from delegations
where trigger_ref = $1 and status = 'running'
order by created_at
`

func (q *Queries) ListRunningDelegationsForRef(ctx context.Context, triggerRef string) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listRunningDelegationsForRef, triggerRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.TriggerRef,
			&i.Playbook,
			&i.Instruction,
			&i.TaskID,
			&i.Status,
			&i.FinalText,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDelegationTask = `-- name: SetDelegationTask :exec
update delegations set task_id = $1 where id = $2
`

type SetDelegationTaskParams struct {
	TaskID *string
	ID     string
}

func (q *Queries) SetDelegationTask(ctx context.Context, arg SetDelegationTaskParams) error {
	_, err := q.db.Exec(ctx, setDelegationTask, arg.TaskID, arg.ID)
	return err
}
