// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_accounts.sql

package agentdb

import (
	"context"
	"time"
)

const deleteGitHubAccount = `-- name: DeleteGitHubAccount :exec
delete from github_accounts where login = $1
`

func (q *Queries) DeleteGitHubAccount(ctx context.Context, login string) error {
	_, err := q.db.Exec(ctx, deleteGitHubAccount, login)
	return err
}

const getGitHubAccount = `-- name: GetGitHubAccount :one
select login, github_id, github_login, name, connected_at, needs_reconnect
from github_accounts
where login = $1
`

func (q *Queries) GetGitHubAccount(ctx context.Context, login string) (GithubAccount, error) {
	row := q.db.QueryRow(ctx, getGitHubAccount, login)
	var i GithubAccount
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.GithubLogin,
		&i.Name,
		&i.ConnectedAt,
		&i.NeedsReconnect,
	)
	return i, err
}

const setGitHubAccountNeedsReconnect = `-- name: SetGitHubAccountNeedsReconnect :exec
update github_accounts set needs_reconnect = true where login = $1
`

func (q *Queries) SetGitHubAccountNeedsReconnect(ctx context.Context, login string) error {
	_, err := q.db.Exec(ctx, setGitHubAccountNeedsReconnect, login)
	return err
}

const upsertGitHubAccount = `-- name: UpsertGitHubAccount :exec
insert into github_accounts (login, github_id, github_login, name, connected_at, needs_reconnect)
values ($1, $2, $3, $4, $5, false)
on conflict (login) do update
  set github_id = excluded.github_id,
      github_login = excluded.github_login,
      name = excluded.name,
      connected_at = excluded.connected_at,
      needs_reconnect = false
`

type UpsertGitHubAccountParams struct {
	Login       string
	GithubID    int64
	GithubLogin string
	Name        string
	ConnectedAt time.Time
}

func (q *Queries) UpsertGitHubAccount(ctx context.Context, arg UpsertGitHubAccountParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubAccount,
		arg.Login,
		arg.GithubID,
		arg.GithubLogin,
		arg.Name,
		arg.ConnectedAt,
	)
	return err
}
