// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package agentdb

import (
	"time"
)

type AgentSkill struct {
	Name        string
	Description string
	Sha256      string
	SizeBytes   int64
	FileCount   int32
	Enabled     bool
	Document    []byte
	UploadedBy  string
	UploadedAt  time.Time
}

type Chat struct {
	ID        string
	Title     string
	Login     string
	CreatedAt time.Time
	AutoTitle bool
}

type ChatMessage struct {
	ChatID      string
	Seq         int64
	Role        string
	Text        string
	Attachments []byte
	Ts          time.Time
	TaskID      string
}

type ChatPullRequest struct {
	ChatID     string
	Url        string
	Owner      string
	Repo       string
	Number     int32
	Source     string
	CreatedAt  time.Time
	DetachedAt *time.Time
}

type Delegation struct {
	ID          string
	SessionID   string
	TurnID      string
	TriggerRef  string
	Playbook    string
	Instruction string
	TaskID      *string
	Status      string
	FinalText   *string
	CreatedAt   time.Time
	FinishedAt  *time.Time
}

type LinearCursor struct {
	Key       string
	UpdatedAt time.Time
}

type Playbook struct {
	Name       string
	Definition []byte
	UpdatedAt  time.Time
	UpdatedBy  string
}

type Relayed struct {
	TaskID string
	Seq    int64
}

type Session struct {
	ID         string
	SourceKind string
	SourceKey  string
	Profile    string
	Playbook   string
	CreatedAt  time.Time
	LastTurnAt *time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

type Turn struct {
	ID         string
	SessionID  string
	TaskID     *string
	TriggerRef string
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
	NumTurns   *int32
	CostUsd    *float64
	FinalText  *string
	Agent      *string
	Model      *string
	Effort     *string
	Provider   *string
}
