// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playbooks.sql

package agentdb

import (
	"context"
	"time"
)

const deleteStoredPlaybook = `-- name: DeleteStoredPlaybook :execrows
delete from playbooks where name = $1
`

func (q *Queries) DeleteStoredPlaybook(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoredPlaybook, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStoredPlaybook = `-- name: InsertStoredPlaybook :execrows

insert into playbooks (name, definition, updated_at, updated_by)
values ($1, $2, $3, $4)
on conflict (name) do nothing
`

type InsertStoredPlaybookParams struct {
	Name       string
	Definition []byte
	UpdatedAt  time.Time
	UpdatedBy  string
}

// Insert and update are separate statements rather than one upsert so that "create" and
// "replace" cannot be confused: the row count says whether the name was already taken, and
// whether it was there to replace, without a read before the write.
func (q *Queries) InsertStoredPlaybook(ctx context.Context, arg InsertStoredPlaybookParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStoredPlaybook,
		arg.Name,
		arg.Definition,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStoredPlaybooks = `-- name: ListStoredPlaybooks :many
select name, definition, updated_at, updated_by from playbooks order by name
`

func (q *Queries) ListStoredPlaybooks(ctx context.Context) ([]Playbook, error) {
	rows, err := q.db.Query(ctx, listStoredPlaybooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playbook{}
	for rows.Next() {
		var i Playbook
		if err := rows.Scan(
			&i.Name,
			&i.Definition,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoredPlaybook = `-- name: UpdateStoredPlaybook :execrows
update playbooks
set definition = $1, updated_at = $2, updated_by = $3
where name = $4
`

type UpdateStoredPlaybookParams struct {
	Definition []byte
	UpdatedAt  time.Time
	UpdatedBy  string
	Name       string
}

func (q *Queries) UpdateStoredPlaybook(ctx context.Context, arg UpdateStoredPlaybookParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStoredPlaybook,
		arg.Definition,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
