// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relayed.sql

package agentdb

import (
	"context"
)

const countRelayed = `-- name: CountRelayed :one
select count(*)::bigint from relayed where task_id = $1
`

func (q *Queries) CountRelayed(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRelayed, taskID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const markRelayed = `-- name: MarkRelayed :one
insert into relayed (task_id, seq) values ($1, $2)
on conflict (task_id, seq) do nothing
returning seq
`

type MarkRelayedParams struct {
	TaskID string
	Seq    int64
}

// MarkRelayed is the whole of the relay's exactly-once guarantee: the insert either takes
// the (task_id, seq) pair or finds it already taken, and the caller posts only when it
// took it. A replayed stream returns no rows and therefore says nothing twice.
func (q *Queries) MarkRelayed(ctx context.Context, arg MarkRelayedParams) (int64, error) {
	row := q.db.QueryRow(ctx, markRelayed, arg.TaskID, arg.Seq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const maxRelayedSeq = `-- name: MaxRelayedSeq :one
select coalesce(max(seq), 0)::bigint as high_seq from relayed where task_id = $1
`

func (q *Queries) MaxRelayedSeq(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxRelayedSeq, taskID)
	var high_seq int64
	err := row.Scan(&high_seq)
	return high_seq, err
}
