// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_surfaces.sql

package agentdb

import (
	"context"
	"time"
)

const bindReviewSurface = `-- name: BindReviewSurface :exec
insert into review_surfaces (source_key, kind, ref, created_at)
values ($1, $2, $3, $4)
on conflict (kind, ref) do nothing
`

type BindReviewSurfaceParams struct {
	SourceKey string
	Kind      string
	Ref       string
	CreatedAt time.Time
}

func (q *Queries) BindReviewSurface(ctx context.Context, arg BindReviewSurfaceParams) error {
	_, err := q.db.Exec(ctx, bindReviewSurface,
		arg.SourceKey,
		arg.Kind,
		arg.Ref,
		arg.CreatedAt,
	)
	return err
}

const getReviewSurface = `-- name: GetReviewSurface :one
select source_key, kind, ref, created_at
from review_surfaces
where kind = $1 and ref = $2
`

type GetReviewSurfaceParams struct {
	Kind string
	Ref  string
}

func (q *Queries) GetReviewSurface(ctx context.Context, arg GetReviewSurfaceParams) (ReviewSurface, error) {
	row := q.db.QueryRow(ctx, getReviewSurface, arg.Kind, arg.Ref)
	var i ReviewSurface
	err := row.Scan(
		&i.SourceKey,
		&i.Kind,
		&i.Ref,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewSurfaces = `-- name: ListReviewSurfaces :many
select source_key, kind, ref, created_at
from review_surfaces
where source_key = $1 and kind = $2
order by created_at
`

type ListReviewSurfacesParams struct {
	SourceKey string
	Kind      string
}

func (q *Queries) ListReviewSurfaces(ctx context.Context, arg ListReviewSurfacesParams) ([]ReviewSurface, error) {
	rows, err := q.db.Query(ctx, listReviewSurfaces, arg.SourceKey, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewSurface{}
	for rows.Next() {
		var i ReviewSurface
		if err := rows.Scan(
			&i.SourceKey,
			&i.Kind,
			&i.Ref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
