// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package agentdb

import (
	"context"
	"time"
)

const getSetting = `-- name: GetSetting :one
select value from settings where key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const putSetting = `-- name: PutSetting :exec
insert into settings (key, value, updated_at) values ($1, $2, $3)
on conflict (key) do update set value = excluded.value, updated_at = excluded.updated_at
`

type PutSettingParams struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
