// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package agentdb

import (
	"context"
	"time"
)

const deleteStoredSkill = `-- name: DeleteStoredSkill :execrows
delete from agent_skills where name = $1
`

func (q *Queries) DeleteStoredSkill(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoredSkill, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStoredSkill = `-- name: GetStoredSkill :one
select name, description, sha256, size_bytes, file_count, enabled, document, uploaded_by, uploaded_at
from agent_skills
where name = $1
`

func (q *Queries) GetStoredSkill(ctx context.Context, name string) (AgentSkill, error) {
	row := q.db.QueryRow(ctx, getStoredSkill, name)
	var i AgentSkill
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Sha256,
		&i.SizeBytes,
		&i.FileCount,
		&i.Enabled,
		&i.Document,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const insertStoredSkill = `-- name: InsertStoredSkill :execrows

insert into agent_skills (name, description, sha256, size_bytes, file_count, document, uploaded_by, uploaded_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (name) do nothing
`

type InsertStoredSkillParams struct {
	Name        string
	Description string
	Sha256      string
	SizeBytes   int64
	FileCount   int32
	Document    []byte
	UploadedBy  string
	UploadedAt  time.Time
}

// Insert and replace are separate statements rather than one upsert, exactly as the playbook
// queries are: the row count says whether the name was already taken without a read before
// the write, and "upload" and "replace this skill" stay two different requests.
func (q *Queries) InsertStoredSkill(ctx context.Context, arg InsertStoredSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStoredSkill,
		arg.Name,
		arg.Description,
		arg.Sha256,
		arg.SizeBytes,
		arg.FileCount,
		arg.Document,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStoredSkills = `-- name: ListStoredSkills :many
select name, description, sha256, size_bytes, file_count, enabled, uploaded_by, uploaded_at
from agent_skills
order by name
`

type ListStoredSkillsRow struct {
	Name        string
	Description string
	Sha256      string
	SizeBytes   int64
	FileCount   int32
	Enabled     bool
	UploadedBy  string
	UploadedAt  time.Time
}

// Deliberately without `document`: a listing of twenty skills has no business carrying
// twenty bundles, and nothing the UI shows comes out of the bundle itself.
func (q *Queries) ListStoredSkills(ctx context.Context) ([]ListStoredSkillsRow, error) {
	rows, err := q.db.Query(ctx, listStoredSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoredSkillsRow{}
	for rows.Next() {
		var i ListStoredSkillsRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Sha256,
			&i.SizeBytes,
			&i.FileCount,
			&i.Enabled,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceStoredSkill = `-- name: ReplaceStoredSkill :execrows
update agent_skills
set description = $1,
    sha256 = $2,
    size_bytes = $3,
    file_count = $4,
    document = $5,
    uploaded_by = $6,
    uploaded_at = $7
where name = $8
`

type ReplaceStoredSkillParams struct {
	Description string
	Sha256      string
	SizeBytes   int64
	FileCount   int32
	Document    []byte
	UploadedBy  string
	UploadedAt  time.Time
	Name        string
}

// `enabled` is not in the set list: replacing the bundle of a skill somebody turned off must
// not turn it back on.
func (q *Queries) ReplaceStoredSkill(ctx context.Context, arg ReplaceStoredSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceStoredSkill,
		arg.Description,
		arg.Sha256,
		arg.SizeBytes,
		arg.FileCount,
		arg.Document,
		arg.UploadedBy,
		arg.UploadedAt,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStoredSkillEnabled = `-- name: SetStoredSkillEnabled :execrows
update agent_skills set enabled = $1 where name = $2
`

type SetStoredSkillEnabledParams struct {
	Enabled bool
	Name    string
}

func (q *Queries) SetStoredSkillEnabled(ctx context.Context, arg SetStoredSkillEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStoredSkillEnabled, arg.Enabled, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
