// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package agentdb

import (
	"context"
	"time"
)

const createTurn = `-- name: CreateTurn :one
insert into turns (id, session_id, task_id, trigger_ref, status, started_at,
                   agent, model, effort, provider)
values ($1, $2, $3, $4, $5, $6,
        nullif($7::text, ''), nullif($8::text, ''), nullif($9::text, ''), nullif($10::text, ''))
returning id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text, agent, model, effort, provider
`

type CreateTurnParams struct {
	ID         string
	SessionID  string
	TaskID     *string
	TriggerRef string
	Status     string
	StartedAt  time.Time
	Agent      string
	Model      string
	Effort     string
	Provider   string
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.ID,
		arg.SessionID,
		arg.TaskID,
		arg.TriggerRef,
		arg.Status,
		arg.StartedAt,
		arg.Agent,
		arg.Model,
		arg.Effort,
		arg.Provider,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TaskID,
		&i.TriggerRef,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.FinalText,
		&i.Agent,
		&i.Model,
		&i.Effort,
		&i.Provider,
	)
	return i, err
}

const finishTurn = `-- name: FinishTurn :exec
update turns
set status      = $1,
    finished_at = $2,
    num_turns   = $3,
    cost_usd    = $4,
    final_text  = $5
where id = $6
`

type FinishTurnParams struct {
	Status     string
	FinishedAt *time.Time
	NumTurns   *int32
	CostUsd    *float64
	FinalText  *string
	ID         string
}

func (q *Queries) FinishTurn(ctx context.Context, arg FinishTurnParams) error {
	_, err := q.db.Exec(ctx, finishTurn,
		arg.Status,
		arg.FinishedAt,
		arg.NumTurns,
		arg.CostUsd,
		arg.FinalText,
		arg.ID,
	)
	return err
}

const getTurn = `-- name: GetTurn :one
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text, agent, model, effort, provider from turns where id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id string) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TaskID,
		&i.TriggerRef,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.FinalText,
		&i.Agent,
		&i.Model,
		&i.Effort,
		&i.Provider,
	)
	return i, err
}

const listRunningTurns = `-- name: ListRunningTurns :many
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text, agent, model, effort, provider from turns where status = 'running' order by started_at
`

func (q *Queries) ListRunningTurns(ctx context.Context) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listRunningTurns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TaskID,
			&i.TriggerRef,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.FinalText,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnCosts = `-- name: ListTurnCosts :many
select t.id, t.task_id, t.session_id, t.status, t.started_at, t.finished_at,
       t.num_turns, t.cost_usd, t.agent, t.model, t.effort, t.provider,
       s.source_kind, s.source_key, s.playbook, s.profile
from turns t
join sessions s on s.id = t.session_id
where t.started_at >= $1 and t.started_at < $2
order by t.started_at desc, t.id desc
limit $3::int
`

type ListTurnCostsParams struct {
	FromTime  time.Time
	ToTime    time.Time
	PageLimit int32
}

type ListTurnCostsRow struct {
	ID         string
	TaskID     *string
	SessionID  string
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
	NumTurns   *int32
	CostUsd    *float64
	Agent      *string
	Model      *string
	Effort     *string
	Provider   *string
	SourceKind string
	SourceKey  string
	Playbook   string
	Profile    string
}

// ListTurnCosts is one row per turn in the range, with the session fields that say what
// spent it. The join is to sessions and no further: a task_id is a string this database has
// no opinion about, and the browser is what puts the two halves together.
func (q *Queries) ListTurnCosts(ctx context.Context, arg ListTurnCostsParams) ([]ListTurnCostsRow, error) {
	rows, err := q.db.Query(ctx, listTurnCosts, arg.FromTime, arg.ToTime, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTurnCostsRow{}
	for rows.Next() {
		var i ListTurnCostsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SessionID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
			&i.SourceKind,
			&i.SourceKey,
			&i.Playbook,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurns = `-- name: ListTurns :many
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text, agent, model, effort, provider from turns
where session_id = $1
order by started_at desc, id desc
limit $2::int
`

type ListTurnsParams struct {
	SessionID string
	PageLimit int32
}

func (q *Queries) ListTurns(ctx context.Context, arg ListTurnsParams) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listTurns, arg.SessionID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TaskID,
			&i.TriggerRef,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.FinalText,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTurnTask = `-- name: SetTurnTask :exec
update turns set task_id = $1 where id = $2
`

type SetTurnTaskParams struct {
	TaskID *string
	ID     string
}

func (q *Queries) SetTurnTask(ctx context.Context, arg SetTurnTaskParams) error {
	_, err := q.db.Exec(ctx, setTurnTask, arg.TaskID, arg.ID)
	return err
}

const usageByBackend = `-- name: UsageByBackend :many
select coalesce(provider, '')::text                as provider,
       coalesce(agent, '')::text                   as agent,
       coalesce(model, '')::text                   as model,
       coalesce(effort, '')::text                  as effort,
       coalesce(sum(cost_usd), 0)::float8          as cost_usd,
       count(*)::int                               as turns,
       coalesce(sum(num_turns), 0)::int            as model_turns,
       count(*) filter (where cost_usd is null)::int as unpriced
from turns
where started_at >= $1 and started_at < $2
group by provider, agent, model, effort
order by cost_usd desc, turns desc
`

type UsageByBackendParams struct {
	FromTime time.Time
	ToTime   time.Time
}

type UsageByBackendRow struct {
	Provider   string
	Agent      string
	Model      string
	Effort     string
	CostUsd    float64
	Turns      int32
	ModelTurns int32
	Unpriced   int32
}

// UsageByBackend is spend grouped by what actually ran it. It is a server-side aggregate for
// the same reason the day rows are: the costs page is capped, and grouping a capped page
// would under-report whichever model happened to fall off the end of it.
//
// Turns from before the columns existed group under empty strings, which the API reports as
// unrecorded rather than as a model named "".
func (q *Queries) UsageByBackend(ctx context.Context, arg UsageByBackendParams) ([]UsageByBackendRow, error) {
	rows, err := q.db.Query(ctx, usageByBackend, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByBackendRow{}
	for rows.Next() {
		var i UsageByBackendRow
		if err := rows.Scan(
			&i.Provider,
			&i.Agent,
			&i.Model,
			&i.Effort,
			&i.CostUsd,
			&i.Turns,
			&i.ModelTurns,
			&i.Unpriced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageByDay = `-- name: UsageByDay :many
select to_char((t.started_at + make_interval(mins => $1::int))::date,
               'YYYY-MM-DD')::text                                           as day,
       coalesce(sum(t.cost_usd), 0)::float8                                  as cost_usd,
       count(*)::int                                                         as turns,
       coalesce(sum(t.num_turns), 0)::int                                    as model_turns,
       count(*) filter (where t.cost_usd is null)::int                       as unpriced
from turns t
where t.started_at >= $2 and t.started_at < $3
group by day
order by day
`

type UsageByDayParams struct {
	TzOffsetMinutes int32
	FromTime        time.Time
	ToTime          time.Time
}

type UsageByDayRow struct {
	Day        string
	CostUsd    float64
	Turns      int32
	ModelTurns int32
	Unpriced   int32
}

// UsageByDay buckets spend into the caller's own days. The offset is added to the stored
// UTC instant before the date is taken, so a turn at 23:30 in New York lands on the day the
// operator ran it rather than on the next one.
// The day leaves as text rather than as a date, because a date would arrive as pgtype.Date
// and the point of the overrides in sqlc.yaml is that no store signature speaks pgx.
func (q *Queries) UsageByDay(ctx context.Context, arg UsageByDayParams) ([]UsageByDayRow, error) {
	rows, err := q.db.Query(ctx, usageByDay, arg.TzOffsetMinutes, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByDayRow{}
	for rows.Next() {
		var i UsageByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.CostUsd,
			&i.Turns,
			&i.ModelTurns,
			&i.Unpriced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
