// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package agentdb

import (
	"context"
	"time"
)

const createTurn = `-- name: CreateTurn :one
insert into turns (id, session_id, task_id, trigger_ref, status, started_at)
values ($1, $2, $3, $4, $5, $6)
returning id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text
`

type CreateTurnParams struct {
	ID         string
	SessionID  string
	TaskID     *string
	TriggerRef string
	Status     string
	StartedAt  time.Time
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.ID,
		arg.SessionID,
		arg.TaskID,
		arg.TriggerRef,
		arg.Status,
		arg.StartedAt,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TaskID,
		&i.TriggerRef,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.FinalText,
	)
	return i, err
}

const finishTurn = `-- name: FinishTurn :exec
update turns
set status      = $1,
    finished_at = $2,
    num_turns   = $3,
    cost_usd    = $4,
    final_text  = $5
where id = $6
`

type FinishTurnParams struct {
	Status     string
	FinishedAt *time.Time
	NumTurns   *int32
	CostUsd    *float64
	FinalText  *string
	ID         string
}

func (q *Queries) FinishTurn(ctx context.Context, arg FinishTurnParams) error {
	_, err := q.db.Exec(ctx, finishTurn,
		arg.Status,
		arg.FinishedAt,
		arg.NumTurns,
		arg.CostUsd,
		arg.FinalText,
		arg.ID,
	)
	return err
}

const getTurn = `-- name: GetTurn :one
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text from turns where id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id string) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TaskID,
		&i.TriggerRef,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NumTurns,
		&i.CostUsd,
		&i.FinalText,
	)
	return i, err
}

const listRunningTurns = `-- name: ListRunningTurns :many
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text from turns where status = 'running' order by started_at
`

func (q *Queries) ListRunningTurns(ctx context.Context) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listRunningTurns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TaskID,
			&i.TriggerRef,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.FinalText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurns = `-- name: ListTurns :many
select id, session_id, task_id, trigger_ref, status, started_at, finished_at, num_turns, cost_usd, final_text from turns
where session_id = $1
order by started_at desc, id desc
limit $2::int
`

type ListTurnsParams struct {
	SessionID string
	PageLimit int32
}

func (q *Queries) ListTurns(ctx context.Context, arg ListTurnsParams) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listTurns, arg.SessionID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TaskID,
			&i.TriggerRef,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.NumTurns,
			&i.CostUsd,
			&i.FinalText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTurnTask = `-- name: SetTurnTask :exec
update turns set task_id = $1 where id = $2
`

type SetTurnTaskParams struct {
	TaskID *string
	ID     string
}

func (q *Queries) SetTurnTask(ctx context.Context, arg SetTurnTaskParams) error {
	_, err := q.db.Exec(ctx, setTurnTask, arg.TaskID, arg.ID)
	return err
}
