// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/v1/admin.proto

package podiumv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alvaroibarguen/podium/internal/proto/podium/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeAdminServiceName is the fully-qualified name of the NodeAdminService service.
	NodeAdminServiceName = "podium.v1.NodeAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeAdminServiceCreateEnrollmentTokenProcedure is the fully-qualified name of the
	// NodeAdminService's CreateEnrollmentToken RPC.
	NodeAdminServiceCreateEnrollmentTokenProcedure = "/podium.v1.NodeAdminService/CreateEnrollmentToken"
	// NodeAdminServiceListNodesProcedure is the fully-qualified name of the NodeAdminService's
	// ListNodes RPC.
	NodeAdminServiceListNodesProcedure = "/podium.v1.NodeAdminService/ListNodes"
)

// NodeAdminServiceClient is a client for the podium.v1.NodeAdminService service.
type NodeAdminServiceClient interface {
	CreateEnrollmentToken(context.Context, *connect.Request[v1.CreateEnrollmentTokenRequest]) (*connect.Response[v1.CreateEnrollmentTokenResponse], error)
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
}

// NewNodeAdminServiceClient constructs a client for the podium.v1.NodeAdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeAdminServiceMethods := v1.File_podium_v1_admin_proto.Services().ByName("NodeAdminService").Methods()
	return &nodeAdminServiceClient{
		createEnrollmentToken: connect.NewClient[v1.CreateEnrollmentTokenRequest, v1.CreateEnrollmentTokenResponse](
			httpClient,
			baseURL+NodeAdminServiceCreateEnrollmentTokenProcedure,
			connect.WithSchema(nodeAdminServiceMethods.ByName("CreateEnrollmentToken")),
			connect.WithClientOptions(opts...),
		),
		listNodes: connect.NewClient[v1.ListNodesRequest, v1.ListNodesResponse](
			httpClient,
			baseURL+NodeAdminServiceListNodesProcedure,
			connect.WithSchema(nodeAdminServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeAdminServiceClient implements NodeAdminServiceClient.
type nodeAdminServiceClient struct {
	createEnrollmentToken *connect.Client[v1.CreateEnrollmentTokenRequest, v1.CreateEnrollmentTokenResponse]
	listNodes             *connect.Client[v1.ListNodesRequest, v1.ListNodesResponse]
}

// CreateEnrollmentToken calls podium.v1.NodeAdminService.CreateEnrollmentToken.
func (c *nodeAdminServiceClient) CreateEnrollmentToken(ctx context.Context, req *connect.Request[v1.CreateEnrollmentTokenRequest]) (*connect.Response[v1.CreateEnrollmentTokenResponse], error) {
	return c.createEnrollmentToken.CallUnary(ctx, req)
}

// ListNodes calls podium.v1.NodeAdminService.ListNodes.
func (c *nodeAdminServiceClient) ListNodes(ctx context.Context, req *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// NodeAdminServiceHandler is an implementation of the podium.v1.NodeAdminService service.
type NodeAdminServiceHandler interface {
	CreateEnrollmentToken(context.Context, *connect.Request[v1.CreateEnrollmentTokenRequest]) (*connect.Response[v1.CreateEnrollmentTokenResponse], error)
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
}

// NewNodeAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeAdminServiceHandler(svc NodeAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeAdminServiceMethods := v1.File_podium_v1_admin_proto.Services().ByName("NodeAdminService").Methods()
	nodeAdminServiceCreateEnrollmentTokenHandler := connect.NewUnaryHandler(
		NodeAdminServiceCreateEnrollmentTokenProcedure,
		svc.CreateEnrollmentToken,
		connect.WithSchema(nodeAdminServiceMethods.ByName("CreateEnrollmentToken")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAdminServiceListNodesHandler := connect.NewUnaryHandler(
		NodeAdminServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(nodeAdminServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.v1.NodeAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeAdminServiceCreateEnrollmentTokenProcedure:
			nodeAdminServiceCreateEnrollmentTokenHandler.ServeHTTP(w, r)
		case NodeAdminServiceListNodesProcedure:
			nodeAdminServiceListNodesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeAdminServiceHandler struct{}

func (UnimplementedNodeAdminServiceHandler) CreateEnrollmentToken(context.Context, *connect.Request[v1.CreateEnrollmentTokenRequest]) (*connect.Response[v1.CreateEnrollmentTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.NodeAdminService.CreateEnrollmentToken is not implemented"))
}

func (UnimplementedNodeAdminServiceHandler) ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.NodeAdminService.ListNodes is not implemented"))
}
