// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/v1/artifact.proto

package podiumv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alvaroibarguen/podium/internal/proto/podium/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "podium.v1.ArtifactService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactServiceListArtifactsProcedure is the fully-qualified name of the ArtifactService's
	// ListArtifacts RPC.
	ArtifactServiceListArtifactsProcedure = "/podium.v1.ArtifactService/ListArtifacts"
	// ArtifactServiceGetArtifactURLProcedure is the fully-qualified name of the ArtifactService's
	// GetArtifactURL RPC.
	ArtifactServiceGetArtifactURLProcedure = "/podium.v1.ArtifactService/GetArtifactURL"
)

// ArtifactServiceClient is a client for the podium.v1.ArtifactService service.
type ArtifactServiceClient interface {
	ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error)
	// GetArtifactURL mints a short-lived presigned GET for one artifact. A caller with no
	// route to the object store can fetch the same bytes from the server instead, at
	// GET /artifacts/{artifact_id}, which is what `podium artifact get` does by default.
	GetArtifactURL(context.Context, *connect.Request[v1.GetArtifactURLRequest]) (*connect.Response[v1.GetArtifactURLResponse], error)
}

// NewArtifactServiceClient constructs a client for the podium.v1.ArtifactService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := v1.File_podium_v1_artifact_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		listArtifacts: connect.NewClient[v1.ListArtifactsRequest, v1.ListArtifactsResponse](
			httpClient,
			baseURL+ArtifactServiceListArtifactsProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("ListArtifacts")),
			connect.WithClientOptions(opts...),
		),
		getArtifactURL: connect.NewClient[v1.GetArtifactURLRequest, v1.GetArtifactURLResponse](
			httpClient,
			baseURL+ArtifactServiceGetArtifactURLProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("GetArtifactURL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	listArtifacts  *connect.Client[v1.ListArtifactsRequest, v1.ListArtifactsResponse]
	getArtifactURL *connect.Client[v1.GetArtifactURLRequest, v1.GetArtifactURLResponse]
}

// ListArtifacts calls podium.v1.ArtifactService.ListArtifacts.
func (c *artifactServiceClient) ListArtifacts(ctx context.Context, req *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error) {
	return c.listArtifacts.CallUnary(ctx, req)
}

// GetArtifactURL calls podium.v1.ArtifactService.GetArtifactURL.
func (c *artifactServiceClient) GetArtifactURL(ctx context.Context, req *connect.Request[v1.GetArtifactURLRequest]) (*connect.Response[v1.GetArtifactURLResponse], error) {
	return c.getArtifactURL.CallUnary(ctx, req)
}

// ArtifactServiceHandler is an implementation of the podium.v1.ArtifactService service.
type ArtifactServiceHandler interface {
	ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error)
	// GetArtifactURL mints a short-lived presigned GET for one artifact. A caller with no
	// route to the object store can fetch the same bytes from the server instead, at
	// GET /artifacts/{artifact_id}, which is what `podium artifact get` does by default.
	GetArtifactURL(context.Context, *connect.Request[v1.GetArtifactURLRequest]) (*connect.Response[v1.GetArtifactURLResponse], error)
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := v1.File_podium_v1_artifact_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceListArtifactsHandler := connect.NewUnaryHandler(
		ArtifactServiceListArtifactsProcedure,
		svc.ListArtifacts,
		connect.WithSchema(artifactServiceMethods.ByName("ListArtifacts")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceGetArtifactURLHandler := connect.NewUnaryHandler(
		ArtifactServiceGetArtifactURLProcedure,
		svc.GetArtifactURL,
		connect.WithSchema(artifactServiceMethods.ByName("GetArtifactURL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.v1.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceListArtifactsProcedure:
			artifactServiceListArtifactsHandler.ServeHTTP(w, r)
		case ArtifactServiceGetArtifactURLProcedure:
			artifactServiceGetArtifactURLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.ArtifactService.ListArtifacts is not implemented"))
}

func (UnimplementedArtifactServiceHandler) GetArtifactURL(context.Context, *connect.Request[v1.GetArtifactURLRequest]) (*connect.Response[v1.GetArtifactURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.ArtifactService.GetArtifactURL is not implemented"))
}
