// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: podium/v1/task.proto

package podiumv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alvaroibarguen/podium/internal/proto/podium/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "podium.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceCreateTaskProcedure is the fully-qualified name of the TaskService's CreateTask RPC.
	TaskServiceCreateTaskProcedure = "/podium.v1.TaskService/CreateTask"
	// TaskServiceGetTaskProcedure is the fully-qualified name of the TaskService's GetTask RPC.
	TaskServiceGetTaskProcedure = "/podium.v1.TaskService/GetTask"
	// TaskServiceListTasksProcedure is the fully-qualified name of the TaskService's ListTasks RPC.
	TaskServiceListTasksProcedure = "/podium.v1.TaskService/ListTasks"
	// TaskServiceCancelTaskProcedure is the fully-qualified name of the TaskService's CancelTask RPC.
	TaskServiceCancelTaskProcedure = "/podium.v1.TaskService/CancelTask"
	// TaskServiceStreamTaskEventsProcedure is the fully-qualified name of the TaskService's
	// StreamTaskEvents RPC.
	TaskServiceStreamTaskEventsProcedure = "/podium.v1.TaskService/StreamTaskEvents"
)

// TaskServiceClient is a client for the podium.v1.TaskService service.
type TaskServiceClient interface {
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	// StreamTaskEvents replays stored events from from_seq and then follows live ones.
	StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error)
}

// NewTaskServiceClient constructs a client for the podium.v1.TaskService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_podium_v1_task_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+TaskServiceCreateTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+TaskServiceGetTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+TaskServiceListTasksProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		cancelTask: connect.NewClient[v1.CancelTaskRequest, v1.CancelTaskResponse](
			httpClient,
			baseURL+TaskServiceCancelTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CancelTask")),
			connect.WithClientOptions(opts...),
		),
		streamTaskEvents: connect.NewClient[v1.StreamTaskEventsRequest, v1.TaskEvent](
			httpClient,
			baseURL+TaskServiceStreamTaskEventsProcedure,
			connect.WithSchema(taskServiceMethods.ByName("StreamTaskEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	createTask       *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	getTask          *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	listTasks        *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	cancelTask       *connect.Client[v1.CancelTaskRequest, v1.CancelTaskResponse]
	streamTaskEvents *connect.Client[v1.StreamTaskEventsRequest, v1.TaskEvent]
}

// CreateTask calls podium.v1.TaskService.CreateTask.
func (c *taskServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// GetTask calls podium.v1.TaskService.GetTask.
func (c *taskServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// ListTasks calls podium.v1.TaskService.ListTasks.
func (c *taskServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// CancelTask calls podium.v1.TaskService.CancelTask.
func (c *taskServiceClient) CancelTask(ctx context.Context, req *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return c.cancelTask.CallUnary(ctx, req)
}

// StreamTaskEvents calls podium.v1.TaskService.StreamTaskEvents.
func (c *taskServiceClient) StreamTaskEvents(ctx context.Context, req *connect.Request[v1.StreamTaskEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error) {
	return c.streamTaskEvents.CallServerStream(ctx, req)
}

// TaskServiceHandler is an implementation of the podium.v1.TaskService service.
type TaskServiceHandler interface {
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	// StreamTaskEvents replays stored events from from_seq and then follows live ones.
	StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest], *connect.ServerStream[v1.TaskEvent]) error
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_podium_v1_task_proto.Services().ByName("TaskService").Methods()
	taskServiceCreateTaskHandler := connect.NewUnaryHandler(
		TaskServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(taskServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListTasksHandler := connect.NewUnaryHandler(
		TaskServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCancelTaskHandler := connect.NewUnaryHandler(
		TaskServiceCancelTaskProcedure,
		svc.CancelTask,
		connect.WithSchema(taskServiceMethods.ByName("CancelTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceStreamTaskEventsHandler := connect.NewServerStreamHandler(
		TaskServiceStreamTaskEventsProcedure,
		svc.StreamTaskEvents,
		connect.WithSchema(taskServiceMethods.ByName("StreamTaskEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/podium.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceCreateTaskProcedure:
			taskServiceCreateTaskHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskProcedure:
			taskServiceGetTaskHandler.ServeHTTP(w, r)
		case TaskServiceListTasksProcedure:
			taskServiceListTasksHandler.ServeHTTP(w, r)
		case TaskServiceCancelTaskProcedure:
			taskServiceCancelTaskHandler.ServeHTTP(w, r)
		case TaskServiceStreamTaskEventsProcedure:
			taskServiceStreamTaskEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.TaskService.CreateTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.TaskService.GetTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.TaskService.ListTasks is not implemented"))
}

func (UnimplementedTaskServiceHandler) CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.TaskService.CancelTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest], *connect.ServerStream[v1.TaskEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("podium.v1.TaskService.StreamTaskEvents is not implemented"))
}
