// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"
	"time"
)

const createArtifact = `-- name: CreateArtifact :one
insert into artifacts (id, task_id, kind, name, object_key, size_bytes, content_type, sha256)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, task_id, kind, name, object_key, size_bytes, content_type, sha256, created_at
`

type CreateArtifactParams struct {
	ID          string
	TaskID      string
	Kind        string
	Name        string
	ObjectKey   string
	SizeBytes   int64
	ContentType string
	Sha256      string
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.TaskID,
		arg.Kind,
		arg.Name,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentType,
		arg.Sha256,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Name,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentType,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
select id, task_id, kind, name, object_key, size_bytes, content_type, sha256, created_at from artifacts where id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Name,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentType,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
select id, task_id, kind, name, object_key, size_bytes, content_type, sha256, created_at from artifacts where task_id = $1 order by created_at, id
`

func (q *Queries) ListArtifacts(ctx context.Context, taskID string) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Name,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentType,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByKind = `-- name: ListArtifactsByKind :many
select id, task_id, kind, name, object_key, size_bytes, content_type, sha256, created_at from artifacts where task_id = $1 and kind = $2 order by name
`

type ListArtifactsByKindParams struct {
	TaskID string
	Kind   string
}

// ListArtifactsByKind is how the roll-up finds the objects it wrote for a task, so a
// pruned task's logs can be served back from the object store.
func (q *Queries) ListArtifactsByKind(ctx context.Context, arg ListArtifactsByKindParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByKind, arg.TaskID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Name,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentType,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLogsRolledUp = `-- name: MarkLogsRolledUp :exec
update tasks
set logs_rolled_up_at  = now(),
    logs_high_seq      = greatest(logs_high_seq, $1),
    logs_stdout_offset = greatest(logs_stdout_offset, $2),
    logs_stderr_offset = greatest(logs_stderr_offset, $3)
where id = $4
`

type MarkLogsRolledUpParams struct {
	HighSeq      int64
	StdoutOffset int64
	StderrOffset int64
	ID           string
}

func (q *Queries) MarkLogsRolledUp(ctx context.Context, arg MarkLogsRolledUpParams) error {
	_, err := q.db.Exec(ctx, markLogsRolledUp,
		arg.HighSeq,
		arg.StdoutOffset,
		arg.StderrOffset,
		arg.ID,
	)
	return err
}

const pruneRolledUpLogChunks = `-- name: PruneRolledUpLogChunks :execrows
delete from task_log_chunks c
using tasks t
where c.task_id = t.id
  and t.logs_rolled_up_at is not null
  and t.logs_rolled_up_at < $1::timestamptz
`

// PruneRolledUpLogChunks drops the hot rows of tasks whose logs are safely in the object
// store and have been for longer than the grace period. It is deliberately scoped by task
// rather than by chunk age: a task still running after the horizon would otherwise have
// its own log truncated under it.
func (q *Queries) PruneRolledUpLogChunks(ctx context.Context, olderThan time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRolledUpLogChunks, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const taskLogRollUp = `-- name: TaskLogRollUp :one
select logs_rolled_up_at, logs_high_seq, logs_stdout_offset, logs_stderr_offset
from tasks where id = $1
`

type TaskLogRollUpRow struct {
	LogsRolledUpAt   *time.Time
	LogsHighSeq      int64
	LogsStdoutOffset int64
	LogsStderrOffset int64
}

func (q *Queries) TaskLogRollUp(ctx context.Context, id string) (TaskLogRollUpRow, error) {
	row := q.db.QueryRow(ctx, taskLogRollUp, id)
	var i TaskLogRollUpRow
	err := row.Scan(
		&i.LogsRolledUpAt,
		&i.LogsHighSeq,
		&i.LogsStdoutOffset,
		&i.LogsStderrOffset,
	)
	return i, err
}

const tasksPendingLogRollUp = `-- name: TasksPendingLogRollUp :many
select id from tasks
where logs_rolled_up_at is null
  and status in ('succeeded', 'failed', 'cancelled', 'lost')
  and coalesce(finished_at, created_at) < $1::timestamptz
order by coalesce(finished_at, created_at)
limit $2::int
`

type TasksPendingLogRollUpParams struct {
	FinishedBefore time.Time
	PageLimit      int32
}

// TasksPendingLogRollUp is every terminal task whose logs are still only in Postgres.
// finished_at is null for a task the control plane wrote off without a node event, so
// coalesce it to created_at rather than skipping the task forever.
func (q *Queries) TasksPendingLogRollUp(ctx context.Context, arg TasksPendingLogRollUpParams) ([]string, error) {
	rows, err := q.db.Query(ctx, tasksPendingLogRollUp, arg.FinishedBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
