// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment_tokens.sql

package db

import (
	"context"
	"time"
)

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :one
update enrollment_tokens
set used_at = now(), used_by_node_id = $1
where token_hash = $2 and used_at is null and expires_at > now()
returning id, token_hash, labels, expires_at, used_at, used_by_node_id, created_by, created_at
`

type ConsumeEnrollmentTokenParams struct {
	UsedByNodeID *string
	TokenHash    []byte
}

// ConsumeEnrollmentToken is the whole single-use check: one statement, so two racing
// enrollments cannot both win.
func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentToken, arg.UsedByNodeID, arg.TokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Labels,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByNodeID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
insert into enrollment_tokens (id, token_hash, labels, expires_at, created_by)
values ($1, $2, $3, $4, $5)
returning id, token_hash, labels, expires_at, used_at, used_by_node_id, created_by, created_at
`

type CreateEnrollmentTokenParams struct {
	ID        string
	TokenHash []byte
	Labels    []byte
	ExpiresAt time.Time
	CreatedBy string
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken,
		arg.ID,
		arg.TokenHash,
		arg.Labels,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Labels,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByNodeID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
select id, token_hash, labels, expires_at, used_at, used_by_node_id, created_by, created_at from enrollment_tokens where token_hash = $1
`

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash []byte) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByHash, tokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Labels,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByNodeID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
