// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
)

const getInstance = `-- name: GetInstance :one
select id, hosted_domain, claimed_by, claimed_at from instance where id = 1
`

func (q *Queries) GetInstance(ctx context.Context) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.HostedDomain,
		&i.ClaimedBy,
		&i.ClaimedAt,
	)
	return i, err
}

const insertInstance = `-- name: InsertInstance :one
insert into instance (hosted_domain, claimed_by)
values ($1, $2)
returning id, hosted_domain, claimed_by, claimed_at
`

type InsertInstanceParams struct {
	HostedDomain string
	ClaimedBy    string
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, insertInstance, arg.HostedDomain, arg.ClaimedBy)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.HostedDomain,
		&i.ClaimedBy,
		&i.ClaimedAt,
	)
	return i, err
}
