// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log_chunks.sql

package db

import (
	"context"
)

const listLogChunks = `-- name: ListLogChunks :many
select task_id, seq, stream, sidecar, ts, bytes, source_offset from task_log_chunks
where task_id = $1 and seq >= $2
order by seq
limit $3::int
`

type ListLogChunksParams struct {
	TaskID    string
	FromSeq   int64
	PageLimit int32
}

func (q *Queries) ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]TaskLogChunk, error) {
	rows, err := q.db.Query(ctx, listLogChunks, arg.TaskID, arg.FromSeq, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLogChunk{}
	for rows.Next() {
		var i TaskLogChunk
		if err := rows.Scan(
			&i.TaskID,
			&i.Seq,
			&i.Stream,
			&i.Sidecar,
			&i.Ts,
			&i.Bytes,
			&i.SourceOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLogChunkSeq = `-- name: MaxLogChunkSeq :one
select coalesce(max(seq), 0)::bigint as high_seq from task_log_chunks where task_id = $1
`

func (q *Queries) MaxLogChunkSeq(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxLogChunkSeq, taskID)
	var high_seq int64
	err := row.Scan(&high_seq)
	return high_seq, err
}

const maxTaskSeq = `-- name: MaxTaskSeq :one
select greatest(
  (select coalesce(max(e.seq), 0) from task_events e     where e.task_id = $1),
  (select coalesce(max(c.seq), 0) from task_log_chunks c where c.task_id = $1),
  (select coalesce(max(t.logs_high_seq), 0) from tasks t where t.id = $1)
)::bigint as high_seq
`

// MaxTaskSeq folds in tasks.logs_high_seq for the same reason TaskStreamOffsets folds in
// the offsets: pruning a rolled-up task's chunks must not let the high-water mark drop, or
// a synthetic event would collide with a sequence number that is already spent.
func (q *Queries) MaxTaskSeq(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxTaskSeq, taskID)
	var high_seq int64
	err := row.Scan(&high_seq)
	return high_seq, err
}

const taskStreamOffsets = `-- name: TaskStreamOffsets :one
select
  greatest(
    (select coalesce(max(c.source_offset), 0) from task_log_chunks c
      where c.task_id = $1 and c.stream = 'stdout' and coalesce(c.sidecar, '') = ''),
    t.logs_stdout_offset)::bigint as stdout_offset,
  greatest(
    (select coalesce(max(c.source_offset), 0) from task_log_chunks c
      where c.task_id = $1 and c.stream = 'stderr' and coalesce(c.sidecar, '') = ''),
    t.logs_stderr_offset)::bigint as stderr_offset
from tasks t
where t.id = $1
`

type TaskStreamOffsetsRow struct {
	StdoutOffset int64
	StderrOffset int64
}

// TaskStreamOffsets is the reconciliation answer for one task: how far into each of the
// container's own streams the control plane has committed. Sidecar chunks are excluded —
// an adopted task's sidecars are never re-attached, so their offsets mean nothing.
//
// The stored roll-up watermarks are folded in with greatest() so the answer cannot go
// backwards when a rolled-up task's chunks are pruned. A node resumed from a smaller
// offset would re-send the whole container log under fresh sequence numbers, which is
// exactly the duplicate step 12 exists to have fixed.
func (q *Queries) TaskStreamOffsets(ctx context.Context, taskID string) (TaskStreamOffsetsRow, error) {
	row := q.db.QueryRow(ctx, taskStreamOffsets, taskID)
	var i TaskStreamOffsetsRow
	err := row.Scan(&i.StdoutOffset, &i.StderrOffset)
	return i, err
}
