// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Artifact struct {
	ID          string
	TaskID      string
	Kind        string
	Name        string
	ObjectKey   string
	SizeBytes   int64
	ContentType string
	Sha256      string
	CreatedAt   time.Time
}

type AuditLog struct {
	ID      int64
	Ts      time.Time
	Actor   string
	Action  string
	Subject string
	Details []byte
}

type EnrollmentToken struct {
	ID           string
	TokenHash    []byte
	Labels       []byte
	ExpiresAt    time.Time
	UsedAt       *time.Time
	UsedByNodeID *string
	CreatedBy    string
	CreatedAt    time.Time
}

type Node struct {
	ID               string
	Name             string
	Tags             []string
	Labels           []byte
	Capacity         []byte
	NodeKeyHash      []byte
	Status           string
	Version          *string
	LastHeartbeatAt  *time.Time
	CreatedAt        time.Time
	TsStableID       *string
	Draining         bool
	MaxTasksOverride *int32
}

type Registry struct {
	Host       string
	Username   string
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	CreatedBy  string
	UpdatedAt  time.Time
}

type Secret struct {
	Name       string
	Ciphertext []byte
	Nonce      []byte
	Version    int32
	KeyID      string
	CreatedBy  string
	UpdatedAt  time.Time
}

type Task struct {
	ID                    string
	Spec                  []byte
	Status                string
	Priority              int32
	RequestedBy           string
	NodeID                *string
	LeaseID               *string
	LeaseExpiresAt        *time.Time
	Attempts              int32
	MaxAttempts           int32
	CreatedAt             time.Time
	ScheduledAt           *time.Time
	StartedAt             *time.Time
	FinishedAt            *time.Time
	ExitCode              *int32
	Usage                 []byte
	FailureReason         *string
	LastScheduleAttemptAt *time.Time
	QueuedReason          *string
	CancelRequestedAt     *time.Time
	CancelReason          *string
	CancelStatus          *string
	LogsRolledUpAt        *time.Time
	LogsHighSeq           int64
	LogsStdoutOffset      int64
	LogsStderrOffset      int64
}

type TaskEvent struct {
	TaskID  string
	Seq     int64
	Kind    string
	Ts      time.Time
	Payload []byte
}

type TaskLogChunk struct {
	TaskID       string
	Seq          int64
	Stream       string
	Sidecar      *string
	Ts           time.Time
	Bytes        []byte
	SourceOffset int64
}

type User struct {
	Login       string
	DisplayName *string
	Roles       []string
	FirstSeenAt time.Time
}
