// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
)

const createNode = `-- name: CreateNode :one
insert into nodes (id, name, tags, labels, capacity, node_key_hash, status, version, ts_stable_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9::text)
returning id, name, tags, labels, capacity, node_key_hash, status, version, last_heartbeat_at, created_at, ts_stable_id, draining, max_tasks_override
`

type CreateNodeParams struct {
	ID          string
	Name        string
	Tags        []string
	Labels      []byte
	Capacity    []byte
	NodeKeyHash []byte
	Status      string
	Version     *string
	TsStableID  *string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Tags,
		arg.Labels,
		arg.Capacity,
		arg.NodeKeyHash,
		arg.Status,
		arg.Version,
		arg.TsStableID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Labels,
		&i.Capacity,
		&i.NodeKeyHash,
		&i.Status,
		&i.Version,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.TsStableID,
		&i.Draining,
		&i.MaxTasksOverride,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :execrows
delete from nodes where id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNode = `-- name: GetNode :one
select id, name, tags, labels, capacity, node_key_hash, status, version, last_heartbeat_at, created_at, ts_stable_id, draining, max_tasks_override from nodes where id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Labels,
		&i.Capacity,
		&i.NodeKeyHash,
		&i.Status,
		&i.Version,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.TsStableID,
		&i.Draining,
		&i.MaxTasksOverride,
	)
	return i, err
}

const getNodeByKeyHash = `-- name: GetNodeByKeyHash :one
select id, name, tags, labels, capacity, node_key_hash, status, version, last_heartbeat_at, created_at, ts_stable_id, draining, max_tasks_override from nodes where node_key_hash = $1
`

func (q *Queries) GetNodeByKeyHash(ctx context.Context, nodeKeyHash []byte) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByKeyHash, nodeKeyHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Labels,
		&i.Capacity,
		&i.NodeKeyHash,
		&i.Status,
		&i.Version,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.TsStableID,
		&i.Draining,
		&i.MaxTasksOverride,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
select id, name, tags, labels, capacity, node_key_hash, status, version, last_heartbeat_at, created_at, ts_stable_id, draining, max_tasks_override from nodes order by created_at, id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tags,
			&i.Labels,
			&i.Capacity,
			&i.NodeKeyHash,
			&i.Status,
			&i.Version,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.TsStableID,
			&i.Draining,
			&i.MaxTasksOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeDraining = `-- name: SetNodeDraining :execrows
update nodes set draining = $1 where id = $2
`

type SetNodeDrainingParams struct {
	Draining bool
	ID       string
}

func (q *Queries) SetNodeDraining(ctx context.Context, arg SetNodeDrainingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeDraining, arg.Draining, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeMaxTasks = `-- name: SetNodeMaxTasks :execrows
update nodes set max_tasks_override = $1::int where id = $2
`

type SetNodeMaxTasksParams struct {
	MaxTasksOverride *int32
	ID               string
}

func (q *Queries) SetNodeMaxTasks(ctx context.Context, arg SetNodeMaxTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeMaxTasks, arg.MaxTasksOverride, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeStatus = `-- name: SetNodeStatus :execrows
update nodes set status = $1 where id = $2
`

type SetNodeStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeTSStableID = `-- name: SetNodeTSStableID :execrows
update nodes set ts_stable_id = $1::text where id = $2
`

type SetNodeTSStableIDParams struct {
	TsStableID *string
	ID         string
}

func (q *Queries) SetNodeTSStableID(ctx context.Context, arg SetNodeTSStableIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeTSStableID, arg.TsStableID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :one
update nodes
set status            = $1,
    capacity          = coalesce($2::jsonb, capacity),
    version           = coalesce($3::text, version),
    last_heartbeat_at = now()
where id = $4
returning id, name, tags, labels, capacity, node_key_hash, status, version, last_heartbeat_at, created_at, ts_stable_id, draining, max_tasks_override
`

type UpdateNodeHeartbeatParams struct {
	Status   string
	Capacity []byte
	Version  *string
	ID       string
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeHeartbeat,
		arg.Status,
		arg.Capacity,
		arg.Version,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Labels,
		&i.Capacity,
		&i.NodeKeyHash,
		&i.Status,
		&i.Version,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.TsStableID,
		&i.Draining,
		&i.MaxTasksOverride,
	)
	return i, err
}
