// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package db

import (
	"context"
	"time"
)

const expiredPreviews = `-- name: ExpiredPreviews :many
select task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at from previews
where released_at is null and expires_at is not null and expires_at <= $1::timestamptz
order by expires_at
limit 100
`

func (q *Queries) ExpiredPreviews(ctx context.Context, now time.Time) ([]Preview, error) {
	rows, err := q.db.Query(ctx, expiredPreviews, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.TaskID,
			&i.NodeID,
			&i.Via,
			&i.Address,
			&i.Urls,
			&i.TtlMs,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.ReleaseReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreview = `-- name: GetPreview :one
select task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at from previews where task_id = $1
`

func (q *Queries) GetPreview(ctx context.Context, taskID string) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreview, taskID)
	var i Preview
	err := row.Scan(
		&i.TaskID,
		&i.NodeID,
		&i.Via,
		&i.Address,
		&i.Urls,
		&i.TtlMs,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
	)
	return i, err
}

const holdPreview = `-- name: HoldPreview :one
update previews
set expires_at = $1::timestamptz + ttl_ms * interval '1 millisecond'
where task_id = $2 and released_at is null and expires_at is null
returning task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at
`

type HoldPreviewParams struct {
	ExitedAt time.Time
	TaskID   string
}

// HoldPreview starts a live preview's ttl, from the moment its command exited.
func (q *Queries) HoldPreview(ctx context.Context, arg HoldPreviewParams) (Preview, error) {
	row := q.db.QueryRow(ctx, holdPreview, arg.ExitedAt, arg.TaskID)
	var i Preview
	err := row.Scan(
		&i.TaskID,
		&i.NodeID,
		&i.Via,
		&i.Address,
		&i.Urls,
		&i.TtlMs,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPreviews = `-- name: ListPreviews :many
select task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at from previews where task_id = any($1::text[])
`

func (q *Queries) ListPreviews(ctx context.Context, taskIds []string) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listPreviews, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.TaskID,
			&i.NodeID,
			&i.Via,
			&i.Address,
			&i.Urls,
			&i.TtlMs,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.ReleaseReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanedPreviews = `-- name: OrphanedPreviews :many
select p.task_id, p.node_id, p.via, p.address, p.urls, p.ttl_ms, p.expires_at, p.released_at, p.release_reason, p.created_at from previews p join tasks t on t.id = p.task_id
where p.released_at is null and p.expires_at is null
  and t.status in ('succeeded', 'failed', 'cancelled', 'lost')
limit 100
`

// OrphanedPreviews is every live preview whose task ended without its command finishing
// held — cancelled, lost, failed before it ran — so there is nothing on a node to keep.
func (q *Queries) OrphanedPreviews(ctx context.Context) ([]Preview, error) {
	rows, err := q.db.Query(ctx, orphanedPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.TaskID,
			&i.NodeID,
			&i.Via,
			&i.Address,
			&i.Urls,
			&i.TtlMs,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.ReleaseReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePreview = `-- name: ReleasePreview :one
update previews
set released_at = now(), release_reason = $1
where task_id = $2 and released_at is null
returning task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at
`

type ReleasePreviewParams struct {
	ReleaseReason string
	TaskID        string
}

func (q *Queries) ReleasePreview(ctx context.Context, arg ReleasePreviewParams) (Preview, error) {
	row := q.db.QueryRow(ctx, releasePreview, arg.ReleaseReason, arg.TaskID)
	var i Preview
	err := row.Scan(
		&i.TaskID,
		&i.NodeID,
		&i.Via,
		&i.Address,
		&i.Urls,
		&i.TtlMs,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPreview = `-- name: UpsertPreview :one
insert into previews (task_id, node_id, via, address, urls, ttl_ms)
values ($1, $2, $3, $4, $5, $6)
on conflict (task_id) do update
set node_id = excluded.node_id, via = excluded.via, address = excluded.address,
    urls = excluded.urls, ttl_ms = excluded.ttl_ms,
    expires_at = null, released_at = null, release_reason = ''
returning task_id, node_id, via, address, urls, ttl_ms, expires_at, released_at, release_reason, created_at
`

type UpsertPreviewParams struct {
	TaskID  string
	NodeID  string
	Via     string
	Address string
	Urls    []byte
	TtlMs   int64
}

// UpsertPreview records where a task's ports were published. The node reports it once per
// run, before the command starts, so a row that is already there belongs to an earlier
// attempt and this one replaces it.
func (q *Queries) UpsertPreview(ctx context.Context, arg UpsertPreviewParams) (Preview, error) {
	row := q.db.QueryRow(ctx, upsertPreview,
		arg.TaskID,
		arg.NodeID,
		arg.Via,
		arg.Address,
		arg.Urls,
		arg.TtlMs,
	)
	var i Preview
	err := row.Scan(
		&i.TaskID,
		&i.NodeID,
		&i.Via,
		&i.Address,
		&i.Urls,
		&i.TtlMs,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
	)
	return i, err
}
