// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registries.sql

package db

import (
	"context"
)

const deleteRegistry = `-- name: DeleteRegistry :execrows
delete from registries where host = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, host string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegistry, host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistries = `-- name: GetRegistries :many
select host, username, ciphertext, nonce, key_id, created_by, updated_at from registries where host = any($1::text[]) order by host
`

func (q *Queries) GetRegistries(ctx context.Context, hosts []string) ([]Registry, error) {
	rows, err := q.db.Query(ctx, getRegistries, hosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.Host,
			&i.Username,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistries = `-- name: ListRegistries :many
select host, username, ciphertext, nonce, key_id, created_by, updated_at from registries order by host
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.Host,
			&i.Username,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistriesForUpdate = `-- name: ListRegistriesForUpdate :many
select host, username, ciphertext, nonce, key_id, created_by, updated_at from registries order by host for update
`

func (q *Queries) ListRegistriesForUpdate(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistriesForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.Host,
			&i.Username,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reEncryptRegistry = `-- name: ReEncryptRegistry :execrows
update registries
set ciphertext = $1,
    nonce      = $2,
    key_id     = $3
where host = $4
`

type ReEncryptRegistryParams struct {
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	Host       string
}

func (q *Queries) ReEncryptRegistry(ctx context.Context, arg ReEncryptRegistryParams) (int64, error) {
	result, err := q.db.Exec(ctx, reEncryptRegistry,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyID,
		arg.Host,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRegistry = `-- name: UpsertRegistry :one
insert into registries (host, username, ciphertext, nonce, key_id, created_by, updated_at)
values ($1, $2, $3, $4, $5, $6, now())
on conflict (host) do update
  set username   = excluded.username,
      ciphertext = excluded.ciphertext,
      nonce      = excluded.nonce,
      key_id     = excluded.key_id,
      updated_at = now()
returning host, username, ciphertext, nonce, key_id, created_by, updated_at
`

type UpsertRegistryParams struct {
	Host       string
	Username   string
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	CreatedBy  string
}

func (q *Queries) UpsertRegistry(ctx context.Context, arg UpsertRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, upsertRegistry,
		arg.Host,
		arg.Username,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyID,
		arg.CreatedBy,
	)
	var i Registry
	err := row.Scan(
		&i.Host,
		&i.Username,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyID,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
