// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
)

const deleteSecret = `-- name: DeleteSecret :execrows
delete from secrets where name = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSecret = `-- name: GetSecret :one
select name, ciphertext, nonce, version, key_id, created_by, updated_at from secrets where name = $1
`

func (q *Queries) GetSecret(ctx context.Context, name string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, name)
	var i Secret
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.Version,
		&i.KeyID,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecrets = `-- name: GetSecrets :many
select name, ciphertext, nonce, version, key_id, created_by, updated_at from secrets where name = any($1::text[]) order by name
`

func (q *Queries) GetSecrets(ctx context.Context, names []string) ([]Secret, error) {
	rows, err := q.db.Query(ctx, getSecrets, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.Version,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
select name, ciphertext, nonce, version, key_id, created_by, updated_at from secrets order by name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.Version,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsForUpdate = `-- name: ListSecretsForUpdate :many
select name, ciphertext, nonce, version, key_id, created_by, updated_at from secrets order by name for update
`

// ListSecretsForUpdate is the rotation read: it locks every row so a concurrent SetSecret
// waits rather than being re-encrypted under a key it did not use.
func (q *Queries) ListSecretsForUpdate(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecretsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.Version,
			&i.KeyID,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reEncryptSecret = `-- name: ReEncryptSecret :execrows
update secrets
set ciphertext = $1,
    nonce      = $2,
    key_id     = $3
where name = $4
`

type ReEncryptSecretParams struct {
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	Name       string
}

func (q *Queries) ReEncryptSecret(ctx context.Context, arg ReEncryptSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, reEncryptSecret,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSecret = `-- name: UpsertSecret :one
insert into secrets (name, ciphertext, nonce, version, key_id, created_by, updated_at)
values ($1, $2, $3, 1, $4, $5, now())
on conflict (name) do update
  set ciphertext = excluded.ciphertext,
      nonce      = excluded.nonce,
      version    = secrets.version + 1,
      key_id     = excluded.key_id,
      updated_at = now()
returning name, ciphertext, nonce, version, key_id, created_by, updated_at
`

type UpsertSecretParams struct {
	Name       string
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	CreatedBy  string
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, upsertSecret,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyID,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.Version,
		&i.KeyID,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
