// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
insert into sessions (id, token_hash, login, expires_at)
values ($1, $2, $3, $4)
returning id, token_hash, login, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	TokenHash []byte
	Login     string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.Login,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Login,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, token_hash, login, expires_at, created_at from sessions
where token_hash = $1 and expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Login,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
